<?php
/**
 * @file
 * USA Network widgets
 */

/**
 * Implementation of hook_init().
 */
function usanetwork_widget_init() {
  $cors_urls = variable_get('usanetwork_widget_cors_urls', 'http://player.theplatform.com');
  
  if (!empty($cors_urls)) {
    drupal_add_http_header('Access-Control-Allow-Origin', $cors_urls);
  }
}

/**
 * Implementation of hook_menu().
 */
function usanetwork_widget_menu() {
  $items['navbar'] = array(
    'page callback' => 'usanetwork_widget_navbar',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['navbar/syndicate_styled'] = array(
    'page callback' => 'usanetwork_widget_navbar_ajax_styled',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['navbar/plain'] = array(
    'page callback' => 'usanetwork_widget_navbar_plain',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['navbar/syndicate_plain'] = array(
    'page callback' => 'usanetwork_widget_navbar_ajax_plain',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['navbar/docs'] = array(
    'page callback' => 'usanetwork_widget_navbar_docs',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/navbar'] = array(
    'page arguments' => array(1),
    'page callback' => 'usanetwork_widget_show_navbar',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/navbar/syndicate_styled'] = array(
    'page arguments' => array(1),
    'page callback' => 'usanetwork_widget_show_navbar_ajax_styled',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/navbar/plain'] = array(
    'page arguments' => array(1),
    'page callback' => 'usanetwork_widget_show_navbar_plain',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/navbar/syndicate_plain'] = array(
    'page arguments' => array(1),
    'page callback' => 'usanetwork_widget_show_navbar_ajax_plain',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/navbar/only'] = array(
    'page arguments' => array(1),
    'page callback' => 'usanetwork_widget_show_navbar_only',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/navbar/syndicate_only'] = array(
    'page arguments' => array(1),
    'page callback' => 'usanetwork_widget_show_navbar_ajax_only',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/navbar/docs'] = array(
    'page arguments' => array(1),
    'page callback' => 'usanetwork_widget_show_navbar_docs',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/usanetwork/syndicate-links'] = array(
    'title' => t('Syndicate Links'),
    'page callback' => 'usanetwork_widget_navbar_links',
    'access arguments' => array('administer usanetwork'),
  );
  $items['admin/usanetwork/cross-domain-settings'] = array(
    'title' => t('Cross Domain Access Control Settings'),
    'description' => t('Administer USA Network Cross Domain Access Control list.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('usanetwork_widget_settings_form'),
    'access arguments' => array('administer usanetwork'),
  );

  return $items;
}

/**
 * Helper to generate and output the main menu bar
 */
function usanetwork_widget_navbar() {
  // TODO: change the 'stage' part of each URL to www & remove time() after testing is complete
  $site_base_url = 'http://stage.usanetwork.com/';
  $style_css_path = $site_base_url . drupal_get_path('theme', 'aurora_usa') . '/stylesheets/navbar.css?'.time();
  $widget_js_path = $site_base_url . drupal_get_path('module', 'usanetwork_widget') . '/js/usanetwork_widget_styled.js?'.time();
  $library_js_path = $site_base_url . drupal_get_path('theme', 'aurora_usa') . '/javascripts/main-navigation-syndicate.js?'.time();

  // get collected styles
  $styles = _usanetwork_widget_styles();

  echo '<!DOCTYPE html>';
  echo '<head>';
  echo '<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">';
  echo $styles;
  echo '<script src="'.$library_js_path.'"></script>';
  echo '<script src="'.$widget_js_path.'"></script>';
  echo '</head>';
  echo '<!--[if IE 9]>';
  echo '<div class="ie ie9">';
  echo '<![endif]-->';
  echo '<h3>page body goes here..</h3>';
  echo '<div id="usanetwork-main-menu"></div>';
  echo '<!--[if IE 9]>';
  echo '</div>';
  echo '<![endif]-->';
  echo '</html>';
  exit;
}

/**
 * Helper to generate and output the main menu bar in styled html
 */
function usanetwork_widget_navbar_ajax_styled() {
  // TODO: change the 'stage' part of each URL to www & remove time() after testing is complete
  $nav_styles = '<style>@import url("http://stage.usanetwork.com/sites/usanetwork/themes/aurora_usa/stylesheets/navbar.css?'.time().'");</style>';

  // get collected styles
  $styles = _usanetwork_widget_styles();

  echo $styles;
  $markup_wrapper = '
  <header role="banner" id="page-header">
    <div role="navigation" id="mega-nav" class="slide-container" data-module-type="Nav">
      <div class="primary-nav">
        <div id="logo">
          <a href="http://www.usanetwork.com" title="Home" rel="home">USA</a>
        </div>
        <div class="region region-header">
          <div id="block-usanetwork-blocks-usa-meganav" class="block block-usanetwork-blocks">
            %s
          </div>
        </div>
      </div>
    </div>
  </header>';
  $main_menu = module_invoke('usanetwork_blocks', 'block_view', 'usa_meganav_syndicate');
  $main_menu = $main_menu['content']['meganav_syndicate']['#markup'];
  $main_menu = preg_replace('/href="\//', 'href="http://www.usanetwork.com/', $main_menu);
  echo sprintf($markup_wrapper, $main_menu);
  exit;
}

/**
 * Helper to generate and output the main menu bar in plain html
 */
function usanetwork_widget_navbar_plain() {
  // TODO: change the 'stage' part of each URL to www & remove time() after testing is complete
  $site_base_url = 'http://stage.usanetwork.com/';
  $widget_js_path = $site_base_url . drupal_get_path('module', 'usanetwork_widget') . '/js/usanetwork_widget_plain.js?'.time();
  echo '<script src="'.$widget_js_path.'"></script>';
  echo '<div id="usanetwork-main-menu"></div>';
  exit;
}

/**
 * Helper to generate and output the main menu bar in plain html
 */
function usanetwork_widget_navbar_ajax_plain() {
  $markup_wrapper = '
  <header role="banner" id="page-header">
    <div role="navigation" id="mega-nav" class="slide-container" data-module-type="Nav">
      <div class="primary-nav">
        <div id="logo">
          <a href="http://www.usanetwork.com" title="Home" rel="home">USA</a>
        </div>
        <div class="region region-header">
          <div id="block-usanetwork-blocks-usa-meganav" class="block block-usanetwork-blocks">
            %s
          </div>
        </div>
      </div>
    </div>
  </header>';
  $main_menu = module_invoke('usanetwork_blocks', 'block_view', 'usa_meganav');
  $main_menu = $main_menu['content']['meganav']['#markup'];
  $main_menu = preg_replace('/href="\//', 'href="http://www.usanetwork.com/', $main_menu);
  echo sprintf($markup_wrapper, $main_menu);
  exit;
}

/**
 * Helper to generate the main menu documentation
 */
function usanetwork_widget_navbar_docs() {
  // get collected styles
  $styles = _usanetwork_widget_styles();

  $docs_markup = '
  <h1>Syndicating the USANetwork navigation bar.</h1>
  <h2>Main Navigation</h2>
  <p><a href="/navbar">demo</a></p>
  <p>Add the following style tag to your site. </p>
  <code><pre>
'. htmlentities($styles) .'
  </pre></code>
  <p>Add the following script tag to your site. </p>
  <code><pre>
'. htmlentities('<!--[if IE 9]>') .'
'. htmlentities('<div class="ie ie9">') .'
'. htmlentities('<![endif]-->') .'
'. htmlentities('<div id="usanetwork-main-menu"></div>') .'
'. htmlentities('<!--[if IE 9]>') .'
'. htmlentities('</div>') .'
'. htmlentities('<![endif]-->') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/themes/aurora_usa/javascripts/main-navigation-syndicate.js"></script>') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/modules/custom/usanetwork_widget/js/usanetwork_widget_styled.js"></script>') .'
  </pre></code>
  <h2>Main Navigation - No Styles</h2>
  <p><a href="/navbar/plain">demo</a></p>
  <p>Add the following script tag to your site. </p>
  <code><pre>
'. htmlentities('<div id="usanetwork-main-menu"></div>') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/themes/aurora_usa/javascripts/main-navigation-syndicate.js"></script>') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/modules/custom/usanetwork_widget/js/usanetwork_widget_plain.js"></script>') .'
  </pre></code>
  ';
  return $docs_markup;
}

/**
 * Helper to generate and output the show menu bar
 */
function usanetwork_widget_show_navbar($node) {
  // TODO: change the 'stage' part of each URL to www & remove time() after testing is complete
  $site_base_url = 'http://stage.usanetwork.com/';
  $style_css_path = $site_base_url . drupal_get_path('theme', 'aurora_usa') . '/stylesheets/navbar.css?'.time();
  $widget_js_path = $site_base_url . drupal_get_path('module', 'usanetwork_widget') . '/js/usanetwork_widget_show_styled.js?'.time();
  $library_js_path = $site_base_url . drupal_get_path('theme', 'aurora_usa') . '/javascripts/main-navigation-syndicate.js?'.time();

  // get collected styles
  $styles = _usanetwork_widget_styles($node);

  echo '<!DOCTYPE html>';
  echo '<head>';
  echo '<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">';
  echo $styles;
  echo '<script type="text/javascript"> var $show_id = '. $node->nid .'; </script>';
  echo '<script src="'.$widget_js_path.'"></script>';
  echo '<script src="'.$library_js_path.'"></script>';
  echo '</head>';
  echo '<!--[if IE 9]>';
  echo '<div class="ie ie9">';
  echo '<![endif]-->';
  echo '<h3>page body goes here..</h3>';
  echo '<div id="usanetwork-main-menu"></div>';
  echo '<!--[if IE 9]>';
  echo '</div>';
  echo '<![endif]-->';
  echo '</html>';
  exit;
}

/**
 * Helper to generate and output the show menu bar
 */
function usanetwork_widget_show_navbar_ajax_styled($node) {
  // TODO: change the 'stage' part of each URL to www & remove time() after testing is complete
  $nav_styles = '<style>@import url("http://stage.usanetwork.com/sites/usanetwork/themes/aurora_usa/stylesheets/navbar.css?'.time().'");</style>';

  // get collected styles
  $styles = _usanetwork_widget_styles($node);

  echo $styles;
  $markup_wrapper = '
  <header role="banner" id="page-header">
    <div role="navigation" id="mega-nav" class="slide-container" data-module-type="Nav">
      <div class="primary-nav">
        <div id="logo">
          <a href="http://www.usanetwork.com" title="Home" rel="home">USA</a>
        </div>
        <div class="region region-header">
          <div id="block-usanetwork-blocks-usa-tv-show-menu" class="block block-usanetwork-blocks"><div class="content">
            %s
          </div></div>
          <div id="block-usanetwork-blocks-usa-meganav" class="block block-usanetwork-blocks"><div class="content">
            %s
          </div></div>
        </div>
      </div>
    </div>
  </header>';
  $show_menu = module_invoke('usanetwork_blocks', 'block_view', 'usa_tv_show_menu');
  $show_menu = $show_menu['content'];
  $show_menu = preg_replace('/href="\//', 'href="http://www.usanetwork.com/', $show_menu); 
  $main_menu = module_invoke('usanetwork_blocks', 'block_view', 'usa_meganav_syndicate');
  $main_menu = $main_menu['content']['meganav_syndicate']['#markup'];
  $main_menu = preg_replace('/href="\//', 'href="http://www.usanetwork.com/', $main_menu);
  echo sprintf($markup_wrapper, $show_menu, $main_menu);
  exit;
}

/**
 * Helper to generate and output the show menu bar in plain html
 */
function usanetwork_widget_show_navbar_plain($node) {
  // TODO: change the 'stage' part of each URL to www & remove time() after testing is complete
  $site_base_url = 'http://stage.usanetwork.com/';
  $widget_js_path = $site_base_url . drupal_get_path('module', 'usanetwork_widget') . '/js/usanetwork_widget_show_plain.js?'.time();
  echo '<script type="text/javascript"> var $show_id = '. $node->nid .'; </script>';
  echo '<script src="'.$widget_js_path.'"></script>';
  echo '<div id="usanetwork-main-menu"></div>';
  exit;
}

/**
 * Helper to generate and output the main menu bar in plain html
 */
function usanetwork_widget_show_navbar_ajax_plain($node) {
  $markup_wrapper = '
  <header role="banner" id="page-header">
    <div role="navigation" id="mega-nav" class="slide-container" data-module-type="Nav">
      <div class="primary-nav">
        <div id="logo">
          <a href="http://www.usanetwork.com" title="Home" rel="home">USA</a>
        </div>
        <div class="region region-header">
          <div id="block-usanetwork-blocks-usa-tv-show-menu" class="block block-usanetwork-blocks"><div class="content">
            %s
          </div></div>
          <div id="block-usanetwork-blocks-usa-meganav" class="block block-usanetwork-blocks"><div class="content">
            %s
          </div></div>
        </div>
      </div>
    </div>
  </header>';
  $show_menu = module_invoke('usanetwork_blocks', 'block_view', 'usa_tv_show_menu');
  $show_menu = $show_menu['content'];
  $show_menu = preg_replace('/href="\//', 'href="http://www.usanetwork.com/', $show_menu); 
  $main_menu = module_invoke('usanetwork_blocks', 'block_view', 'usa_meganav');
  $main_menu = $main_menu['content']['meganav']['#markup'];
  $main_menu = preg_replace('/href="\//', 'href="http://www.usanetwork.com/', $main_menu);
  echo sprintf($markup_wrapper, $show_menu, $main_menu);
  exit;
}

/**
 * Helper to generate and output the show menu bar in plain html
 */
function usanetwork_widget_show_navbar_only($node) {
  // TODO: change the 'stage' part of each URL to www & remove time() after testing is complete
  $site_base_url = 'http://stage.usanetwork.com/';
  $widget_js_path = $site_base_url . drupal_get_path('module', 'usanetwork_widget') . '/js/usanetwork_widget_show_only.js?'.time();
  echo '<script type="text/javascript"> var $show_id = '. $node->nid .'; </script>';
  echo '<script src="'.$widget_js_path.'"></script>';
  echo '<div id="usanetwork-main-menu"></div>';
  exit;
}

/**
 * Helper to generate and output the main menu bar in plain html
 */
function usanetwork_widget_show_navbar_ajax_only($node) {
  $show_menu = module_invoke('usanetwork_blocks', 'block_view', 'usa_tv_show_menu');
  $show_menu = $show_menu['content'];
  $show_menu = preg_replace('/href="\//', 'href="http://www.usanetwork.com/', $show_menu); 
  print $show_menu;
  exit;
}

/**
 * Helper to generate the show menu documentation
 */
function usanetwork_widget_show_navbar_docs($node) {
  // get collected styles
  $styles = _usanetwork_widget_styles($node);

  $docs_markup = '
  <h1>Syndicating the USANetwork show navigation bar.</h1>
  <h2>Show and Main Navigation</h2>
  <p><a href="/node/'. $node->nid .'/navbar">demo</a></p>
  <p>Add the following style tag to your site.</p>
  <code><pre>
'. htmlentities($styles) .'
    </pre></code>
  <p>Add the following script tags to your site.</p>
  <code><pre>
'. htmlentities('<!--[if IE 9]>') .'
'. htmlentities('<div class="ie ie9">') .'
'. htmlentities('<![endif]-->') .'
'. htmlentities('<div id="usanetwork-main-menu"></div>') .'
'. htmlentities('<!--[if IE 9]>') .'
'. htmlentities('</div>') .'
'. htmlentities('<![endif]-->') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/themes/aurora_usa/javascripts/main-navigation-syndicate.js"></script>') .'
'. htmlentities('<script type="text/javascript">var $show_id = '. $node->nid .'; </script>') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/modules/custom/usanetwork_widget/js/usanetwork_widget_show_styled.js"></script>') .'
  </pre></code>

  <h2>Show and Main Navigation - No Styles</h2>
  <p><a href="/node/'. $node->nid .'/navbar/plain">demo</a></p>
  <p>Add the following script tags to your site.</p>
  <code><pre>
'. htmlentities('<div id="usanetwork-main-menu"></div>') .'  
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/themes/aurora_usa/javascripts/main-navigation-syndicate.js"></script>') .'
'. htmlentities('<script type="text/javascript">var $show_id = '. $node->nid .'; </script>') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/modules/custom/usanetwork_widget/js/usanetwork_widget_show_plain.js"></script>') .'
  </pre></code>

  <h2>Show Navigation Only - No Styles</h2>
  <p><a href="/node/'. $node->nid .'/navbar/only">demo</a></p>
  <p>Add the following script tags to your site.</p>
  <code><pre>
'. htmlentities('<div id="usanetwork-main-menu"></div>') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/themes/aurora_usa/javascripts/main-navigation-syndicate.js"></script>') .'
'. htmlentities('<script src="http://usanetwork.com/sites/usanetwork/modules/custom/usanetwork_widget/js/usanetwork_widget_show_only.js"></script>') .'
  </pre></code>
  ';
  return $docs_markup;
}

/**
 * Helper to generate the admin syndicate links
 */
function usanetwork_widget_navbar_links() {
  $links = array();
  $output = '';
   
  $links[] = l(t('Global Navbar'), 'navbar');
  $links[] = l(t('Global Navbar Plain'), 'navbar/plain');
  $links[] = l(t('Global Navbar Docs'), 'navbar/docs');

  $output .= '<b>' . t('Global Menu Links') . '</b>';
  $output .= theme('item_list', array('items' => $links));

  $output .= '<b>' . t('Show Menu Links') . '</b>';
  $links = array();
  $shows = _usanetwork_widget_get_nodes('tv_show');  
  foreach ($shows as $show) {
    $show_path = drupal_get_path_alias('node/'.$show->nid);
    $links[] = l($show->title .': Styled Navbar', $show_path . '/navbar');
    $links[] = l($show->title .': Plain Navbar', $show_path . '/navbar/plain');
    $links[] = l($show->title .': Plain Navbar Only', $show_path . '/navbar/only');
    $links[] = l($show->title .': Navbar Docs', $show_path . '/navbar/docs');
    $links[] = '<br/>';
  }
  $output .= theme('item_list', array('items' => $links));

  return $output;
}

/**
 * Helper that returns nodes of a given type.
 */
function _usanetwork_widget_get_nodes($node_type) {

  $nodes_query = new EntityFieldQuery();
  $nodes_query->entityCondition('entity_type', 'node');
  $nodes_query->entityCondition('bundle', $node_type);
  $nodes_query->propertyCondition('status', 1);
  $nodes_query->propertyOrderBy('title', 'ASC');
  $nodes_result = $nodes_query->execute();

  $nodes = array();

  if (isset($nodes_result['node'])) {
    foreach ($nodes_result['node'] as $result) {
      $nodes[ $result->nid ] = node_load($result->nid, $result->vid);
    }
  }

  return $nodes;
}

/**
 * USA Network settings form
 */
function usanetwork_widget_settings_form() {
  $form['usanetwork_widget_cors_urls'] = array(
    '#type' => 'textarea',
    '#title' => t('CORS URL List'),
    '#default_value' => variable_get('usanetwork_widget_cors_urls', 'http://player.theplatform.com'),
    '#description' => t('Enter the list of all urls you need to add to the cross domain access control list seperated using comma (,).'),
  );

  return system_settings_form($form);
}

/**
 * Returns rendered styles
 */
function _usanetwork_widget_styles($show = null) {
  $css = &drupal_static('drupal_add_css', array());
  $copy_css = $css;
  // Empty all styles
  $css = array();
  // Add initial styles
  drupal_add_css(drupal_get_path('theme', 'aurora_usa') . '/stylesheets/navbar.css');
  // Get styling info from other modules
  module_invoke_all('usanetwork_widget_style', $show);
  $output = drupal_get_css($css);
  $css = $copy_css;
  return $output;
}
