<?php

/**
 * Implementation of hook_menu().
 */
function usanetwork_tv_schedule_menu() {
  // admin pages
  $items['admin/usanetwork/tv-schedule-settings'] = array(
    'title' => t('TV Schedule Settings'),
    'description' => t('Administer TV schedule settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('usanetwork_tv_schedule_settings_form'),
    'access arguments' => array('administer usanetwork'),
    'file' =>  'usanetwork_tv_schedule.admin.inc',
  );
  $items['schedule'] = array(
    'title' => t('Schedule'),
    'page callback' => 'usanetwork_tv_schedule_schedule_page',
    'access arguments' => array('access content'),
  );
  $items['usa-on-now-panel-js'] = array(
    'page callback' => 'usanetwork_on_now_panel_js',
    'access arguments' => array('access content'),
  );
  $items['usa-on-now-social-block'] = array(
    'page callback' => 'usanetwork_on_now_social_block',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function usanetwork_tv_schedule_block_info() {
  $blocks = array();
  $blocks['usa_on_now_block'] = array(
    'info' => t('USA: on now block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['usa_on_now_panel'] = array(
    'info' => t('USA: on now panel'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_tv_schedule_block_view($delta) {
  $block = array();
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'usa_on_now_block':
      $block['subject'] = '';
      $block['content'] = usanetwork_tv_schedule_on_now_block();
      break;
    case 'usa_on_now_panel':
      $block['subject'] = '';
      $block['content'] = usanetwork_tv_schedule_on_now_panel();
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function usanetwork_tv_schedule_theme() {
  return array(
    'usanetwork_tv_schedule_navigation' => array(
      'file' => 'usanetwork_tv_schedule.theme.inc',
      'variables' => array(
        'timestamp' => null,
        'first_day' => 'sun',
      ),
    ),
    'usanetwork_tv_schedule_navigation_week' => array(
      'file' => 'usanetwork_tv_schedule.theme.inc',
      'variables' => array(
        'timestamp' => null,
        'first_day' => 'sun',
        'offset' => 0,
      ),
    ),
    'usanetwork_tv_schedule_navigation_weekday' => array(
      'file' => 'usanetwork_tv_schedule.theme.inc',
      'variables' => array(
        'timestamp' => null,
      ),
    ),
  );
}

/**
 * Block callback for the On Now block
 */
function usanetwork_tv_schedule_on_now_block() {
  $show_name = '';
  $lang = LANGUAGE_NONE;
  $render = array();

  // JS to determine the current timezone from the user browser
  drupal_add_js(drupal_get_path('module', 'usanetwork_tv_schedule') . '/js/jstz-1.0.4.min.js');

  // switch to ET timezone to perform calculations and then switch back to original timezone
  $orginal_tz = date_default_timezone_get();
  date_default_timezone_set('America/New_York');
  $et_time = floatval(date('U'));

  $today = date('Y-m-d');

  // fetch today's schedule
  $tv_schedule = usanetwork_tv_schedule_fetch_schedule(date('Y_m_d'));
  if (empty($tv_schedule)) {
    return;
  }

  // fetch yesterday's schedule to load the schedule from 00:00 AM till 5:59 AM
  $tv_schedule_prev_day = usanetwork_tv_schedule_fetch_schedule(date('Y_m_d', time() - 60 * 60 * 24));

  // return empty block if the tv schedule is empty
  if (empty($tv_schedule) || empty($tv_schedule_prev_day)) {
    // switch back to original server time zone
    date_default_timezone_set($orginal_tz);
    return '';
  }

  $full_tv_schedule = array();
  // get the tv schedule from 00:00 AM till 5:59 AM
  foreach ($tv_schedule_prev_day as $item) {
    $cal_date = (array) $item->CalendarScheduleDate;

    if ($cal_date[0] == $today) {
      $end_time = (array) $item->EndTime;
      $program = (array) $item->ProgramName;
      $episode = (array) $item->TitleName;
      $tv_show = trim(preg_replace('/\(.*\)/', '', $program[0]));
      $tv_show_name = $tv_show;
      $nid = _usanetwork_tv_schedule_get_nid_by_title($tv_show, 'tv_show');
      $episode_name_clean = check_plain($episode[0]);
      $episode_name_clean = ucwords(strtolower($episode_name_clean));
      $arrow = '';
      if (!empty($nid)) {
        $arrow = 'class="trigger"';
      }
      $on_now_icon = '<span id="on-now" ' . $arrow . '>onnow</span>';
      $tv_show = '<div id="on-now-show-episode"><span id="on-now-show-name" class="on-now-show-name">' . check_plain($tv_show) . '</span> <span id="on-now-episode" class="on-now-episode">'. $episode_name_clean . '</span></div>';

      if (empty($nid)) {
        if (strtoupper($tv_show_name) == 'USA MOVIE') {
          $tv_show = $on_now_icon . l($tv_show, 'movies', array('html' => true));
        } else {
          $tv_show = $on_now_icon . '<div id="on-now-show-episode"><span id="on-now-show-name" class="on-now-show-name">' . $tv_show_name . '</span></div>';
        }
      }
      else {
        $path = drupal_get_path_alias('node/'.$nid);
        $show_node = node_load($nid);
        if (isset($show_node->field_display_title[$lang][0]['value']) && !empty($show_node->field_display_title[$lang][0]['value'])) {
          // check for identical program and episode name, if they match hide the episode
          if (trim($program[0]) === trim($episode[0])) {
            $tv_show = '<div id="on-now-show-episode"><span id="on-now-show-name" class="on-now-show-name">' . check_plain($show_node->field_display_title[$lang][0]['value']) . '</span> <span id="on-now-episode" class="on-now-episode">&nbsp;</span></div>';
          }
          else {
            $tv_show = '<div id="on-now-show-episode"><span id="on-now-show-name" class="on-now-show-name">' . check_plain($show_node->field_display_title[$lang][0]['value']) . '</span> <span id="on-now-episode" class="on-now-episode">'. $episode_name_clean . '</span></div>';
          }

          // link things up
          $tv_show = $on_now_icon . l($tv_show, $path, array('html' => true));
        } else {
          $tv_show = $on_now_icon . l($tv_show, $path, array('html' => true));
        }
      }

      $full_tv_schedule[] = array(
        'date' => $cal_date[0],
        'time' => $end_time[0],
        'ts' => strtotime($cal_date[0] .' '. $end_time[0]),
        'show_name' => check_plain($program[0]),
        'episode_name' => check_plain($episode[0]),
        'link' => $tv_show,
        'nid' => $nid,
      );
    }
  }
  // get the tv schedule from 6:00 AM till end of the day
  foreach ($tv_schedule as $item) {
    $cal_date = (array) $item->CalendarScheduleDate;

    $end_time = (array) $item->EndTime;
    $program = (array) $item->ProgramName;
    $episode = (array) $item->TitleName;

    $tv_show = trim(preg_replace('/\(.*\)/', '', $program[0]));
    $tv_show_name = $tv_show;
    $nid = _usanetwork_tv_schedule_get_nid_by_title($tv_show, 'tv_show');
    $episode_name_clean = check_plain($episode[0]);
    $episode_name_clean = ucwords(strtolower($episode_name_clean));

    $arrow = '';
    if (!empty($nid)) {
      $arrow = 'class="trigger"';
    }
    $on_now_icon = '<span id="on-now" ' . $arrow . '>onnow</span>';
    $tv_show = '<div id="on-now-show-episode"><span id="on-now-show-name" class="on-now-show-name">' . check_plain($tv_show) . '</span> <span id="on-now-episode" class="on-now-episode">'. $episode_name_clean . '</span></div>';

    if (empty($nid)) {
      if (strtoupper($tv_show_name) == 'USA MOVIE') {
        $tv_show = $on_now_icon . l($tv_show, 'movies', array('html' => true));
      } else {
        $tv_show = $on_now_icon . $tv_show;
      }
    } else {
      $path = drupal_get_path_alias('node/'.$nid);
      $show_node = node_load($nid);
      if (isset($show_node->field_display_title[$lang][0]['value']) && !empty($show_node->field_display_title[$lang][0]['value'])) {
        // check for identical program and episode name, if they match hide the episode
        if (trim($program[0]) === trim($episode[0])) {
          $tv_show = '<div id="on-now-show-episode"><span id="on-now-show-name" class="on-now-show-name">' . check_plain($show_node->field_display_title[$lang][0]['value']) . '</span> <span id="on-now-episode" class="on-now-episode">&nbsp;</span></div>';
        }
        else {
          $tv_show = '<div id="on-now-show-episode"><span id="on-now-show-name" class="on-now-show-name">' . check_plain($show_node->field_display_title[$lang][0]['value']) . '</span> <span id="on-now-episode" class="on-now-episode">'. $episode_name_clean . '</span></div>';
        }

        // link things up
        $tv_show = $on_now_icon . l($tv_show, $path, array('html' => true));
      } else {
        $tv_show = $on_now_icon . l($tv_show, $path, array('html' => true));
      }
    }

    $full_tv_schedule[] = array(
      'date' => $cal_date[0],
      'time' => $end_time[0],
      'ts' => strtotime($cal_date[0] .' '. $end_time[0]),
      'show_name' => check_plain($program[0]),
      'episode_name' => check_plain($episode[0]),
      'link' => $tv_show,
      'nid' => $nid,
    );

    if ($cal_date[0] != $today) {
      break;
    }
  }

  // expose the tv schedule as JS variable to determine the on on show based on the user timezone and for other modules to consume it
  $vars = 'var tv_schedule = ' . drupal_json_encode($full_tv_schedule) . ';';

  foreach ($full_tv_schedule as $i => $show) {
    if ($today == $show['date']) {
      $show_name = $show['link'];
      $show_nid = $show['nid'];
      $show_index = $i;
      if ($et_time < $show['ts']) {
        break;
      }
    }
  }

  // expose default et show for rest of the world
  $vars .= "var on_now_default_show = '" . $show_name . "';";
  // expose default show nid for on now panel
  $vars .= "var on_now_index = " . $show_index . ";";

  drupal_add_js($vars, array('type' => 'inline'));
  drupal_add_js(drupal_get_path('module', 'usanetwork_tv_schedule') . '/js/usanetwork_tv_schedule.js');

  // Handles the JS disabled browser scenario
  $markup = '<noscript>' . $show_name . '</noscript>';

  $render['on_now_block']['body'] = array(
    '#type' => 'markup',
    '#markup' => $markup,
  );

  // switch back to original server time zone
  date_default_timezone_set($orginal_tz);

  return $render;
}

/**
 * Block callback for the On Now Panel
 */
function usanetwork_tv_schedule_on_now_panel() {
  $output = '';
  $links = array();

  $links[0]['data'] = '<span class="tab-wrapper active"><span>' . t('On') . '</span> ' . t('Now') . '</span>';
  $links[0]['class'] = array('on-now', 'tab-1');
  //$links[0]['children'][] = '<div id="on-now-panel-tab"><iframe id="on-now-iframe" frameborder="0" width="100%" marginheight="0" marginwidth="0" scrolling="no" src=""></iframe></div>';
  $links[0]['children'][] = '<div id="on-now-panel-tab"></div>';

  $links[1]['data'] = '<span class="tab-wrapper"><span>' . t('Up') . '</span> ' . t('Next') . '</span>';
  $links[1]['class'] = array('up-next', 'tab-2');
  //$links[1]['children'][] = '<div id="up-next-panel-tab"><iframe id="up-next-iframe" frameborder="0" width="100%" marginheight="0" marginwidth="0" scrolling="no" src=""></iframe></div>';
  $links[1]['children'][] = '<div id="up-next-panel-tab"></div>';

  $output = theme('item_list', array('items' => $links));

  return '<div id="inner-on-now-panel">'. $output .'</div>';
}

/**
 * TV schedule page menu callback
 */
function usanetwork_tv_schedule_schedule_page() {
  $output = '';
  // styles moved to theme
  //@TODO clean this up
  //drupal_add_css(drupal_get_path('module', 'usanetwork_tv_schedule') . '/css/usanetwork_tv_schedule.css');

  // switch to ET timezone to perform calculations and then switch back to original timezone
  $orginal_tz = date_default_timezone_get();
  date_default_timezone_set('America/New_York');
  $et_time = floatval(date('U'));

  $sdate = date('Y_m_d');
  if (isset($_GET['sdate']) && !empty($_GET['sdate'])) {
    $sdate = check_plain($_GET['sdate']);
    $et_time = strtotime(str_replace('_', '-', $sdate) . date(' H:i:s'));
  }

  $tv_schedule = usanetwork_tv_schedule_fetch_schedule($sdate);

  if (empty($tv_schedule)) {
    // switch back to original server time zone
    date_default_timezone_set($orginal_tz);
    drupal_not_found();
    return;
  }

  $header = array(
    array('data' => t('TIME (ET)'), 'class' => array('show-time')),
    array('data' => t('PROGRAM'), 'class' => array('program')),
    array('data' => t('EPISODE'), 'class' => array('episode')),
    array('data' =>  t('RATING'), 'class' => array('rating')),
  );
  $rows = array();
  foreach ($tv_schedule as $item) {
    $classes = array();

    $start_time = (array) $item->StartTime;
    $end_time = (array) $item->EndTime;
    $program = (array) $item->ProgramName;
    $episode = (array) $item->TitleName;
    $rating = (array) $item->Rating;
    $cur_date = (array) $item->ScheduleDate;
    $cal_date = (array) $item->CalendarScheduleDate;
    $day_part = (array) $item->Daypart;

    // convert to timestamp to determine on-air / off-air
    $show_time = strtotime($cal_date[0] .' '. $end_time[0]);

    // add styles to show hide the row based on on air value
    $classes[] = ($et_time >= $show_time) ? 'off-air' : 'on-air';

    // add classes like primetime to style differently
    $classes[] = strtolower($day_part[0]);

    $show = trim(preg_replace('/\(.*\)/', '', $program[0]));
    $nid = _usanetwork_tv_schedule_get_nid_by_title($show, 'tv_show');
    $episode_suffix = trim(check_plain($episode[0])) != '' ? '<span class="episode-suffix"> - ' . check_plain($episode[0]) . '</span>' : '';
    if (empty($nid)) {
      if (strtoupper($show) == 'USA MOVIE') {
        $show = l(check_plain($program[0]) . $episode_suffix, 'movies', array('html' => true));
      } else {
        $show = check_plain($program[0]) . $episode_suffix;
      }
    } else {
      $path = drupal_get_path_alias('node/'.$nid);
      $show = l(check_plain($program[0]) . $episode_suffix, $path, array('html' => true));
    }

    $row = array(
      array('data' => preg_replace('/:[0-9][0-9] /', ' ', $start_time[0]), 'class' => array('show-time')),
      array('data' => $show, 'class' => array('program')),
      array('data' => check_plain($episode[0]), 'class' => array('episode')),
      array('data' => $rating[0], 'class' => array('rating')),
    );
    $rows[] = array('data' => $row, 'class' => $classes);
  }

  $output .= theme('usanetwork_tv_schedule_navigation', array('timestamp' => strtotime($cur_date[0])));

  $output .= '<div class="schedule-table">';
  $output .= empty($rows) ? '' : theme('table',array('header' =>  $header, 'rows' => $rows, 'attributes' => array('width' => '100%')));
  $output .= '</div>';

  // switch back to original server time zone
  date_default_timezone_set($orginal_tz);

  return $output;
}

/**
 * Fetch TV schedule from compass xml feed
 */
function usanetwork_tv_schedule_fetch_schedule($sdate='') {
  $xml_feed = variable_get('usanetwork_tv_schedule_xml_feed', '');

  if (empty($xml_feed) || empty($sdate)) {
    return NULL;
  }

  // replace the tokens in the Compass XML URL
  $xml_feed = str_replace('YYYY_MM_DD', $sdate, $xml_feed);

  $result = drupal_http_request($xml_feed);
  if (!isset($result->headers['content-type']) || $result->headers['content-type'] != 'application/xml') {
    return NULL;
  }

  $proxy = variable_get('pub_utilities_proxy', '');
  if (!empty($proxy)) {
    $default_context = stream_context_get_default(
      array('http' =>
        array(
         'proxy' => $proxy,
         'request_fulluri' => true,
        ),
      )
    );
    libxml_set_streams_context($default_context);
  }
  $tvs = simplexml_load_file($xml_feed);
  //$tvs = simplexml_load_file(drupal_get_path('module', 'usanetwork_tv_schedule') . '/test.xml');


  if (!isset($tvs->Schedules->Schedule->ScheduleItem) || empty($tvs->Schedules->Schedule->ScheduleItem)) {
    return NULL;
  } else {
    return $tvs->Schedules->Schedule->ScheduleItem;
  }
}

/**
 * Get node id given the title and type
 */
function _usanetwork_tv_schedule_get_nid_by_title($title, $type) {
  $nid = 0;
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $type)
    ->propertyCondition('status', 1)
    ->range(0, 1);

  /**
   * add fix for WWE
   * @todo: make configurable
   */
  if (strpos($title, 'WWE') === 0) {
    $query->propertyCondition('title', 'WWE%', 'LIKE');
  }
  else {
    $query->propertyCondition('title', $title);
  }

  $result = $query->execute();

  if (isset($result['node'])) {
    $nid = array_keys($result['node']);
    $nid = $nid[0];
  }

  return $nid;
}

/**
 * On now panel content ajax callback
 */
function usanetwork_on_now_panel_js() {
  $arg = arg();
  $output = '&nbsp;';
  $links = array();

  if (empty($arg[1]) && empty($arg[2])) {
    // return empty div to avoid 304: Not modified http header
    echo $output;
    exit;
  }

  if (!empty($arg[1]) && isset($_GET['on_now'])) {
    $on_now = node_load($arg[1]);
    $output = usanetwork_on_now_panel_node_content($on_now, check_plain($_GET['on_now']));
  }

  if (!empty($arg[2]) && isset($_GET['next_up'])) {
    $next_up = node_load($arg[2]);
    $output = usanetwork_on_now_panel_node_content($next_up, check_plain($_GET['next_up']));
  }

  echo $output;
  exit;
}


function usanetwork_on_now_social_block() {
  $arg = arg();
  $output = '&nbsp;';
  $links = array();
  if (empty($arg[1])) {
    // return empty div to avoid 304: Not modified http header
    echo $output;
    exit;
  }

  if (!empty($arg[1]) && !empty($arg[2])) {
    $on_now = node_load($arg[1]);
    $output = usanetwork_on_now_social_block_content($on_now,$arg[2]);
  }
  echo $output;
  exit;
}

function usanetwork_on_now_social_block_content($node, $tab) {
  $output = '';
  if($tab == 'twitter'){
    $output .= usanetwork_social_show_on_now_twitter_response($node, 2);
  }
  if($tab == 'chatter'){
    $output .= usanetwork_social_show_on_now_chatter_response($node, 2);
  }
  if($tab == 'facebook'){
    $output .= usanetwork_social_show_on_now_facebook_response($node, 2);
  }
  return $output;
}
/**
 * On now panel content given the tv show node
 */
function usanetwork_on_now_panel_node_content($node, $text) {
  $output = '';
  $lang = LANGUAGE_NONE;

  // Change only the first occurance of the quote to "'"; which will be safe from security attack
  $text = preg_replace('/&amp;#039;/', "'", $text, 1);

  $image = $node->field_usa_tv_on_now[$lang][0];
  $on_now_image = array(
    'style_name' => '300x250_on_now',
    'path' => $image['uri'],
    'alt' => $image['alt'],
    'title' => $image['title'],
  );

  $path = drupal_get_path_alias('node/'.$node->nid);

  if (isset($node->field_show_sync[$lang][0]['value']) && !empty($node->field_show_sync[$lang][0]['value'])) {
    // link image to show sync page
    $output .= '<div class="show-on-now-wrapper"><div class="show-on-sync"><figure>' . l(theme('image_style', $on_now_image) . '<span>sync now</span>', $path.'/social/sync', array('html' => true)) . '</figure></div>';
  } else {
    $output .= '<div class="show-on-now-wrapper"><figure>' . theme('image_style', $on_now_image) . '</figure>';
  }

  // show info
  $output .= '<div class="show-info-wrapper">';
  $output .= '<div class="show-info">';

  // show name
  if (isset($node->field_display_title[$lang][0]['value']) && !empty($node->field_display_title[$lang][0]['value'])) {
    $output .= '<div class="show-title">' . l($node->field_display_title[$lang][0]['value'], $path) . '</div>';
  } else {
    $output .= '<div class="show-title">' . l($node->title, $path) . '</div>';
  }

  // episode name
  $output .= '<div class="episode-title">' . l(ucwords(strtolower($text)), $path) . '</div>';

  $output .= '</div>';

  // social icons
  $output .= '<div class="icons-social icons-inline">';
  if (isset($node->field_usa_link_facebook[$lang][0]['url']) && !empty($node->field_usa_link_facebook[$lang][0]['url'])) {
    $output .= l('facebook', $node->field_usa_link_facebook[$lang][0]['url'],
      array('attributes' => array('class' => array('show-facebook', 'usasocial-facebook'))));
  }
  if (isset($node->field_usa_link_twitter[$lang][0]['url']) && !empty($node->field_usa_link_twitter[$lang][0]['url'])) {
    $output .= l('twitter', $node->field_usa_link_twitter[$lang][0]['url'],
      array('attributes' => array('class' => array('show-twitter', 'usasocial-twitter'))));
  }
  if (isset($node->field_usa_link_pinterest[$lang][0]['url']) && !empty($node->field_usa_link_pinterest[$lang][0]['url'])) {
    $output .= l('pinterest', $node->field_usa_link_pinterest[$lang][0]['url'],
      array('attributes' => array('class' => array('show-pinterest', 'usasocial-pinterest'))));
  }
  if (isset($node->field_usa_link_tumblr[$lang][0]['url']) && !empty($node->field_usa_link_tumblr[$lang][0]['url'])) {
    $output .= l('tumblr', $node->field_usa_link_tumblr[$lang][0]['url'],
      array('attributes' => array('class' => array('show-tumblr', 'usasocial-tumblr'))));
  }
  $output .= '</div>';

  $output .= '</div>';

  // schedule page
  $output .= '<div class="full-schedule-link">'. l(t('View full schedule'), 'schedule') . '</div>';

  $output .= '</div>';

  // Social Show block
  $output .= usanetwork_social_show_on_now_box($node, 2);

  return $output;
}
