<?php

/**
 * @file
 * Usanetwork Deep Linking module.
*/

define('USA_DEEP_LINKING_IOS_SCHEME', 'usatve://');
define('USA_DEEP_LINKING_WINDOWS_APP_ID', 'eee92128-e791-463d-abfc-2a7df28a2b5d');

/**
 * Process variables for file_entity.
 */
function usanetwork_deep_linking_preprocess_file_entity(&$vars) {
  $file = $vars['file'];
  if (in_array($file->type, _pub_mpx_get_mpx_account_video_file_types(TRUE))) {
    if (isset($vars['view_mode']) && $vars['view_mode'] == 'full') {
      $file_field = _usanetwork_get_field_item('file', $file, 'field_mpx_full_episode', 'value');
      if ($file_field == '1') {
        $apple_itunes_app_tag = array(
          '#tag' => 'meta',
          '#attributes' => array(
            'name' => 'apple-itunes-app',
            'content' => 'app-id=' . USANETWORK_USANOW_ITUNES_ID,
          )
        );
        $windows_app_tag_id = array(
          '#tag' => 'meta',
          '#attributes' => array(
            'name' => 'msApplication-ID',
            'content' => USA_DEEP_LINKING_WINDOWS_APP_ID,
          ),
        );
//        $windows_app_tag_family = array(
//          '#tag' => 'meta',
//          '#attributes' => array(
//            'name' => 'msApplication-PackageFamilyName',
//            'content' => SYFY_DEEP_LINKING_WINDOWS_FAMILY_ID,
//          ),
//        );

        $js_settings['usa']['msAppId'] = USA_DEEP_LINKING_WINDOWS_APP_ID;
//        $js_settings['syfy']['msFamilyId'] = SYFY_DEEP_LINKING_WINDOWS_FAMILY_ID;
        $js_settings['usa']['itunesAppId'] = SYFY_DEEP_LINKING_IOS_APP_ID;

        $advert_id = _usanetwork_get_field_item('file', $file, 'field_mpx_external_advertiser_id', 'value');
        if (!empty($advert_id)) {
          $ios_link = USA_DEEP_LINKING_IOS_SCHEME . '?target=videoAsset&ID=' . $advert_id;
          $apple_itunes_app_tag['#attributes']['content'] .= ', app-argument=' . $ios_link;
          $js_settings['usa']['deepLinking'] = $ios_link;
        }

        drupal_add_js($js_settings, 'setting');
        drupal_add_js(drupal_get_path('module', 'usanetwork_deep_linking') . '/js/usanetwork_deep_linking.js');
        drupal_add_html_head($apple_itunes_app_tag, 'usa_apple_itunes_app');
        drupal_add_html_head($windows_app_tag_id, 'usa_windows_app_id');
//        drupal_add_html_head($windows_app_tag_family, 'usa_windows_app_family');
      }
    }
  }
}
