<?php
function ds_usa_mpx_video() {
  return array(
    'label' => t('usa mpx video'),
    'regions' => array(
      'ad_dart' => t('ad_dart'),
      'ad_lead' => t('ad_lead'),
      'show' => t('show'),
      'video_title' => t('video title'),
      'season' => t('season'),
      'episode' => t('episode'),
      'airdate' => t('airdate'),
      'description' => t('description'),
      'ad_comp' => t('ad_comp'),
    ),
    'css' => true,
    'image' => false
  );
}