<?php
/**
 * @file
 * Code for the USA Network Umbel Tracking.
 */

/**
 * Implementation of hook_menu().
 */
function usanetwork_umbel_menu() {
  // admin area
  $items['admin/usanetwork/umbel'] = array(
    'title' => 'Umbel Tracking settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('usanetwork_umbel_tracking_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'usanetwork_umbel.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_page_alter().
 */
function usanetwork_umbel_page_alter(&$page) {
  if (!path_is_admin(current_path())) {
    $usanetwork_umbel_tracking_code = variable_get('usanetwork_umbel_tracking_code', 'iwgdlxrtqfiiortz');
    drupal_add_js(array('umbel_code' => $usanetwork_umbel_tracking_code),'setting');

    $page['page_bottom']['umbel']['#attached']['js'][drupal_get_path('module', 'usanetwork_umbel') . '/js/usanetwork_umbel_main.js'] =  array(
      'type' => 'file',
      'scope' => 'footer',
    );
  }
}
