<?php
/**
 * @file
 * Code for the usanetwork_gigya feature.
 */

include_once 'usanetwork_gigya.features.inc';

/**
 * Implements hook_init().
 */
function usanetwork_gigya_init() {
  /*drupal_add_js(drupal_get_path('module', 'usanetwork_gigya') . '/js/usanetwork_gigya_sharebar.js', array(
    'every_page' => true,
    'group' => JS_THEME,
  ));*/
}

/**
 * Implements hook_preprocess_file_entity().
 */
function usanetwork_gallery_content_preprocess_file_entity(&$variables) {
  if ($variables['view_mode'] == 'gallery_flexslider') {
    $content = &$variables['content'];
    $file = $content['file']['#file'];

    $filesize = $file->filesize;
    if ($content['file']['#theme'] == 'image_style') {
      $styled_file = image_style_path($content['file']['#style_name'], $file->uri);
      if (file_exists($styled_file)) {
        $filesize = filesize($styled_file);
      }
    }

    if ($filesize > 4194304) {
      // if file size is more that 4M
      // add compressed image url
      $content['file']['#attributes']['data-src-share'] = image_style_url('share', $file->uri);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * Overriding "Comment settings" dropdown options on Content Type add/edit
 * pages.
 */
function usanetwork_gigya_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  $form['comment']['comment']['#options'][1] = 'Hidden';
  unset($form['comment']['comment']['#options'][0]);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter()
 *
 * Overriding "Comment settings" options on node/edit & add pages.
 */
function usanetwork_gigya_form_node_form_alter(&$form, &$form_state, $form_id) {
  $form['comment_settings']['comment'][2]["#description"] = 'Gigya commenting is open to all users.';
  $form['comment_settings']['comment']['#options'][1] = 'Hidden';
  $form['comment_settings']['comment'][1]["#description"] = 'Gigya commenting is hidden for all users.';
}

/*
 * Implements hook_node_view()
 *
 * Removes Drupal comment section from all nodes where commenting is enabled
 * so it doesn't flash before Gigya comments are loaded via JavaScript since
 * if users leave a comment while they have JavaScript disabled it will not be
 * entered as a Gigya comment. Also replaces with empty div so Gigya can latch
 * on and insert it's commenting system where Drupal's would normally be.
 */
function usanetwork_gigya_node_view($node, $view_mode, $langcode) {
  if ($node->comment == COMMENT_NODE_OPEN) {
    $node->content['comments'] = array('#markup' => '<div id="comments"></div>');
  }
}
