<?php
/**
 * @file
 * Code for the usanetwork_gallery_content feature.
 */

include_once 'usanetwork_gallery_content.features.inc';

/**
 * Implements hook_node_view().
 */
function usanetwork_gallery_content_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'media_gallery') {
    $node->content['#attached']['js'][] = drupal_get_path('module', 'usanetwork_gallery_content') . '/js/usanetwork_gallery_content.js';
  }
}
