<?php
/**
 * @file
 * Code for the USANetwork Promo feature.
 */

include_once 'usanetwork_promo.features.inc';

/**
 * Implements template_preprocess_node().
 */
function usanetwork_promo_preprocess_node(&$vars) {
  $node = $vars['node'];
  
  if ($node->type == 'usanetwork_promo') {
    $action_type = field_get_items('node', $node, 'field_call_to_action_type');
    $action_term = taxonomy_term_load($action_type[0]['tid']);
    $vars['action_type'] = $action_term->name;
  }
}
