<?php

/**
 * @file
 * Code for the usanetwork_media_gallery feature.
 */
include_once 'usanetwork_media_gallery.features.inc';

define ('USA_GALLERY_RELATED_CONTENT_ITEMS', 6);

/**
 *  Implements hook_menu().
 */
function usanetwork_media_gallery_menu() {
  $items = array();

  $items['ajax/usanetwork-media-gallery/get-related/%node/%/%'] = array(
    'title' => 'Related content',
    'page callback' => 'usanetwork_media_gallery_get_related_content_ajax',
    'page arguments' => array(3, 4, 5),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 *  Implements hook_block_info().
 */
function usanetwork_media_gallery_block_info() {
  $blocks = array();

  $blocks['usa_gallery_central_gallery'] = array(
    'info' => 'Consumptionator: Media gallery slides',
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usa_gallery_episode_gallery'] = array(
    'info' => 'Consumptionator: Episode gallery',
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usa_gallery_consumptionator_main'] = array(
    'info' => 'Consumptionator: Media gallery block',
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usa_gallery_cons_related'] = array(
    'info' => 'Media gallery: Related content',
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 *  Implements hook_block_view().
 */
function usanetwork_media_gallery_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'usa_gallery_central_gallery':
      $block['subject'] = '';
      $block['content'] = _usanetwork_media_gallery_consumptionator_gallery_slides_block();
      break;

    case 'usa_gallery_episode_gallery':
      $block['subject'] = '';
      $block['content'] = _usanetwork_media_gallery_consumptionator_episodes_block();
      break;

    case 'usa_gallery_consumptionator_main':
      $block['subject'] = '';
      $block['content'] = _usanetwork_media_gallery_consumptionator_gallery_block();
      break;

    case 'usa_gallery_cons_related':
      $block['subject'] = '';
      $block['content'] = _usanetwork_media_gallery_related_content_block();
      break;
  }

  return $block;
}


/**
 * Implements hook_theme().
 */
function usanetwork_media_gallery_theme($existing, $type, $theme, $path) {
  return array(
    'usanetwork_media_gallery_consumptionator_slide' => array(
      'variables' => array(
        'gigya_id' => NULL,
        'image' => NULL,
        'info' => array(
          'description' => NULL,
        ),
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-slide',
    ),
    'usanetwork_media_gallery_consumptionator_slides' => array(
      'variables' => array(
        'slides' => array(),
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-slides',
    ),
    'usanetwork_media_gallery_consumptionator_episode_slide_horizontal' => array(
      'variables' => array(
        'gallery_url' => NULL,
        'image_url' => NULL,
        'title' => NULL,
        'season' => NULL,
        'episode' => NULL,
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-episode-slide-horizontal',
    ),
    'usanetwork_media_gallery_consumptionator_episode_slide_vertical' => array(
      'variables' => array(
        'gallery_url' => NULL,
        'image_url' => NULL,
        'title' => NULL,
        'season' => NULL,
        'episode' => NULL,
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-episode-slide-vertical',
    ),
    'usanetwork_media_gallery_consumptionator_episode_slides' => array(
      'variables' => array(
        'gallery_type' => NULL,
        'slides_vertical' => array(),
        'slides_horizontal' => array(),
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-episode-slides',
    ),
    'usanetwork_media_gallery_consumptionator' => array(
      'variables' => array(
        'slider' => NULL,
        'episodic_gallery' => NULL,
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator',
    ),



    'usanetwork_media_gallery_related_item' => array(
      'variables' => array(
        'classes' => NULL,
        'custom_classes' => NULL,
        'target_url' => NULL,
        'caption' => NULL,
        'title' => NULL,
        'additional' => NULL,
        'image_mobile' => NULL,
        'image_desktop' => NULL,
      ),
      'template' => 'templates/usanetwork-media-gallery-related-item',
    ),
    'usanetwork_media_gallery_related_ymal_item' => array(
      'variables' => array(
        'classes' => NULL,
        'custom_classes' => NULL,
        'target_url' => NULL,
        'topic' => NULL,
        'show_name' => NULL,
        'promo_title' => NULL,
        'description' => NULL,
        'image_mobile' => NULL,
        'image_desktop' => NULL,
        'cta' => NULL,
        'color_class' => NULL,
        'icon_type' => NULL,
      ),
      'template' => 'templates/usanetwork-media-gallery-related-ymal-item',
    ),
    'usanetwork_media_gallery_related_items_block' => array(
      'variables' => array(
        'ad' => NULL,
        'related_items' => array(),
      ),
      'template' => 'templates/usanetwork-media-gallery-related-items-block',
    ),
    'usanetwork_media_gallery_related_items_container' => array(
      'variables' => array(
        'related_items_block' => NULL,
        'load_more_link' => NULL,
        'items_pre_page_limit' => NULL,
        'show_nid' => NULL,
      ),
      'template' => 'templates/usanetwork-media-gallery-related-items-container',
    ),
  );
}


/**
 * Renders main gallery block for consumptionator page.
 */
function _usanetwork_media_gallery_consumptionator_gallery_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  return theme('usanetwork_media_gallery_consumptionator', array(
    'slider' => _usanetwork_media_gallery_consumptionator_gallery_slides_block(),
    'episodic_gallery' => _usanetwork_media_gallery_consumptionator_episodes_block(),
  ));
}

/**
 * Renders main gallery on MediaGallery page.
 */
function _usanetwork_media_gallery_consumptionator_gallery_slides_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $node = menu_get_object();

  if (isset($node->type) && $node->type == 'media_gallery') {
    $slides = array();

    $gallery_field = field_get_items('node', $node, 'field_media_items');

    $image_cover_field = field_get_items('node', $node, 'field_cover_item');
    if (!empty($image_cover_field)) {
      array_unshift($gallery_field, reset($image_cover_field));
    }
    if (!empty($gallery_field) && is_array($gallery_field)) {
      foreach ($gallery_field as $gallery_file) {
        if (is_array($gallery_file)) {
          $gallery_file = (object)$gallery_file;
        }

        if (!empty($node->field_gigya_share_bar)) {
          $sharebar = field_view_field('node', $node, 'field_gigya_share_bar');
          $sharebar['#title'] = t('Share this image');
        }
        $slide_variables = array(
          'gigya_id' => !empty($sharebar) ? render($sharebar) : NULL,
          'image' => theme_image(array(
            'path' => $gallery_file->uri,
            'attributes' => array(),
          )),
          'info' => array(
            'description' => '',
            'gallery_name' => $node->title,
            'photo_name' => $gallery_file->filename,
          ),
        );

        $caption_field = field_get_items('file', $gallery_file, 'field_caption');

        if (!empty($caption_field)) {
          $slide_variables['info']['description'] = $caption_field[0]['value'];
          $slide_variables['info']['description'] = strip_tags($caption_field[0]['value']);
        }

        $slides[] = theme('usanetwork_media_gallery_consumptionator_slide', $slide_variables);
      }
    }

    return theme('usanetwork_media_gallery_consumptionator_slides', array('slides' => $slides));
  }

  return '';
}

/**
 * Renders episodes gallery on MediaGallery page.
 */
function _usanetwork_media_gallery_consumptionator_episodes_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $node = menu_get_object();

  if (isset($node->type) && $node->type == 'media_gallery') {
    if (!empty($node->field_show) && !empty($node->field_gallery_type)) {
      $node_wrapper = entity_metadata_wrapper('node', $node);

      $show_nid = $node_wrapper->field_show->nid->value();
      $gallery_type = $node_wrapper->field_gallery_type->value();

      $galleries_list = _usanetwork_media_gallery_get_galleries($show_nid, $gallery_type);

      if (!empty($galleries_list)) {
        $rendered_items = array();

        foreach ($galleries_list as $gallery_item) {
          if ($gallery_item->nid == $node->nid) {
            continue;
          }

          $gallery_item_vertical = array(
            'gallery_url' => url('node/' . $gallery_item->nid),
            'image_url' => !empty($gallery_item->uri)
              ? image_style_url('111x74', $gallery_item->uri)
              : '',
            'title' => $gallery_item->title,
            'season' => $gallery_item->field_season_id_value,
            'episode' => $gallery_item->field_episode_number_value,
          );

          $gallery_item_horizontal = array(
            'gallery_url' => url('node/' . $gallery_item->nid),
            'image_url' => !empty($gallery_item->uri)
              ? image_style_url('full_episodes_633x356', $gallery_item->uri)
              : '',
            'title' => $gallery_item->title,
            'season' => $gallery_item->field_season_id_value,
            'episode' => $gallery_item->field_episode_number_value,
          );

          $rendered_items['slides_vertical'][] = theme('usanetwork_media_gallery_consumptionator_episode_slide_vertical', $gallery_item_vertical);
          $rendered_items['slides_horizontal'][] = theme('usanetwork_media_gallery_consumptionator_episode_slide_horizontal', $gallery_item_horizontal);
        }

        if (!empty($rendered_items)) {
          return theme('usanetwork_media_gallery_consumptionator_episode_slides', array(
            'gallery_type' => $gallery_type,
            'slides_vertical' => $rendered_items['slides_vertical'],
            'slides_horizontal' => $rendered_items['slides_horizontal'],
          ));
        }
      }
    }
  }

  return '';
}

/**
 * Returns data list of media galleries of current show using TV Season node id.
 *
 * @param $show_nid
 * @param $season_nid
 */
function _usanetwork_media_gallery_get_galleries($show_nid, $gallery_type) {
  $query = db_select('node', 'n');
  $query->fields('n', array('nid', 'title', 'created'));
  $query->join('field_data_field_show', 'sh', 'n.nid=sh.entity_id');
  $query->leftJoin('field_data_field_season', 'se', 'n.nid=se.entity_id');
  $query->join('field_data_field_gallery_type', 'gt', 'n.nid=gt.entity_id');
  $query->leftJoin('field_data_field_season_id', 'se_id', 'se.field_season_target_id=se_id.entity_id');
  $query->fields('se_id', array('field_season_id_value'));
  $query->leftJoin('field_data_field_episode', 'ep', 'n.nid=ep.entity_id');
  $query->leftJoin('node', 'ep_node', 'ep.field_episode_target_id=ep_node.nid');
  $query->leftJoin('field_data_field_episode_number', 'ep_number', 'ep_node.nid=ep_number.entity_id');
  $query->fields('ep_number', array('field_episode_number_value'));
  $query->leftJoin('field_data_field_cover_item', 'cover', 'n.nid=cover.entity_id');
  $query->fields('cover', array('field_cover_item_fid'));
  $query->leftJoin('file_managed', 'cover_file', 'cover_file.fid=cover.field_cover_item_fid');
  $query->fields('cover_file', array('uri'));

  $query->condition('sh.field_show_target_id', $show_nid);
  $query->condition('n.status', 1);
  $query->condition('n.type', 'media_gallery');
  $query->condition('gt.field_gallery_type_value', $gallery_type);

  return $query->execute()->fetchAll();
}

/**
 * Renders Block entity of related content items.
 */
function _usanetwork_media_gallery_related_content_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $content = menu_get_object('node');

  if (!empty($content)) {
    $show_field = field_get_items('node', $content, 'field_show');

    if (!empty($show_field)) {
      $tv_show_node = node_load($show_field[0]['target_id']);

      if (empty($tv_show_node->field_tvs_show_latest_lnd_feed)) {
        return '';
      }
      else {
        $latest_content_flag_field = field_get_items('node', $tv_show_node, 'field_tvs_show_latest_lnd_feed');

        if ($latest_content_flag_field[0]['value'] == 0) {
          return '';
        }
      }

      $you_may_also_like_item = usanetwork_media_gallery_get_ymal_item($tv_show_node);

      $related_content = _usanetwork_tv_shows_cache_get_limited_related_gallery_content(
        $tv_show_node, 0,
        !empty($you_may_also_like_item)
          ? USA_GALLERY_RELATED_CONTENT_ITEMS - 1
          : USA_GALLERY_RELATED_CONTENT_ITEMS
      );

      if (!empty($you_may_also_like_item)) {
        $related_content[] = $you_may_also_like_item;
      }

      if (!empty($related_content)) {
        drupal_add_js(drupal_get_path('module', 'usanetwork_tv_shows') . '/js/usanetwork_tv_shows_related_items_loader.js');
        drupal_add_js(array(
          'usanetwork_tv_show_nid' => $tv_show_node->nid,
          'usanetwork_tv_show_page_context' => 'gallery-consumptionator',
          'usanetwork_tv_show_offset' => !empty($you_may_also_like_item) ? -1 : 0,
        ), 'setting');

        $block_of_items = _usanetwork_media_gallery_render_related_content_items_block($related_content, FALSE);

        return theme('usanetwork_media_gallery_related_items_container', array(
          'related_items_block' => $block_of_items,
          'load_more_link' => TRUE,
          'show_nid' => $tv_show_node->nid,
          'items_pre_page_limit' => USA_MPX_VIDEO_RELATED_CONTENT_ITEMS,
        ));
      }
    }
  }
}

/**
 * Renders block of items (default number of items in the block is 6)
 */
function _usanetwork_media_gallery_render_related_content_items_block($data, $ad) {
  if (!empty($data)) {

    $advert_block = module_invoke('mps', 'block_view', 'midbanner');
    if (!empty($advert_block['content'])) {
      $advert = render($advert_block['content']);
    }

    $theme_variables = array(
      'related_items' => array(),
      'ad' => $ad ? (isset($advert) ? $advert : NULL) : NULL,
    );

    foreach ($data as $data_index => $data_item) {
      if (!empty($data_item->ymal)) {
        $theme_variables['related_items'][] = _usanetwork_media_gallery_render_related_content_item_ymal($data_item);
      }
      else {
        $theme_variables['related_items'][] = _usanetwork_media_gallery_render_related_content_item_default($data_item);
      }
    }

    return theme('usanetwork_media_gallery_related_items_block', $theme_variables);
  }

  return '';
}

/**
 * Renders YouMayAlsoLike item (featured function).
 */
function _usanetwork_media_gallery_render_related_content_item_ymal($data) {
  $classes = array();
  $desktop_image = $mobile_image = '';
  $target_url = '<front>';

  if (!empty($data->entity_type) && !empty($data->entity_id) && in_array($data->entity_type, array('file', 'node'))) {
    $target_url = url($data->entity_type . '/' . $data->entity_id);
  }

  if (!empty($data->raw_image_uri)) {
    $desktop_image = image_style_url('921x488', $data->raw_image_uri);
    $mobile_image = image_style_url('591x330', $data->raw_image_uri);
  }

  $theme_variables = array(
    'custom_classes' => implode(" ", $classes),
    'target_url' => $target_url,
    'topic' => !empty($data->promo_topic)
      ? check_plain($data->promo_topic)
      : '',
    'show_name' => NULL,
    'promo_title' => !empty($data->promo_title)
      ? check_plain($data->promo_title)
      : $data->title,
    'description' => !empty($data->promo_description)
      ? check_plain($data->promo_description)
      : '',
    'image_desktop' => $desktop_image,
    'image_mobile' => $mobile_image,
    'media_icon' => $data->media_icon,
    'cta' => NULL,
    'ymal_about' => $data->ymal_about,
  );
  return theme('usanetwork_media_gallery_related_ymal_item', $theme_variables);
}

/**
 * Renders default item.
 */
function _usanetwork_media_gallery_render_related_content_item_default($data) {
  $classes = array();
  $desktop_image = $mobile_image = '';
  $target_url = '<front>';

  if (!empty($data->entity_type) && !empty($data->entity_id) && in_array($data->entity_type, array(
      'file',
      'node'
    ))
  ) {
    $target_url = url($data->entity_type . '/' . $data->entity_id);
  }

  if (!empty($data->raw_image_uri)) {
    $desktop_image = image_style_url('921x488', $data->raw_image_uri);
    $mobile_image = image_style_url('591x330', $data->raw_image_uri);
  }

  $theme_variables = array(
    'custom_classes' => implode(" ", $classes),
    'target_url' => $target_url,
    'caption' => !empty($data->promo_topic)
      ? htmlspecialchars($data->promo_topic)
      : $data->show_title,
    'title' => !empty($data->promo_title)
      ? htmlspecialchars($data->promo_title)
      : $data->title,
    'additional' => !empty($data->promo_description)
      ? htmlspecialchars($data->promo_description)
      : '',
    'image_desktop' => $desktop_image,
    'image_mobile' => $mobile_image,
    'media_icon' => $data->media_icon,
  );

  return theme('usanetwork_media_gallery_related_item', $theme_variables);
}

/**
 * Returns "You may also like" rendered item.
 */
function usanetwork_media_gallery_get_ymal_item($show_node) {
  if (!empty($show_node->field_usa_tv_related_shows)) {
    $related_show_field = field_get_items('node', $show_node, 'field_usa_tv_related_shows');

    if (!empty($related_show_field[0]['target_id'])) {
      $related_show_node = node_load($related_show_field[0]['target_id']);
      $about_field_data = '';

      if (!empty($related_show_node->field_about_ymal)) {
        $about_field = field_get_items('node', $related_show_node, 'field_about_ymal');

        if (!empty($about_field)) {
          $about_field_data = check_plain(reset(reset($about_field)));
        }
      }

      return (object)array(
        'entity_type' => 'node',
        'bundle' => $related_show_node->type,
        'entity_id' => $related_show_node->nid,
        'created' => $related_show_node->created,
        'timestamp' => $related_show_node->changed,
        'title' => $related_show_node->title,
        'show_title' => $about_field_data,
        'raw_image_uri' => usanetwork_core_api_get_content_image('node', $related_show_node),
        'media_icon' => usanetwork_core_api_get_media_icon('node', $related_show_node->nid),
        'ymal_about' => $about_field_data,
        'ymal' => TRUE,
      );
    }
  }
}

function usanetwork_media_gallery_get_related_content_ajax($tv_show_node, $start_from = 0, $limit = 1) {
  $response = array(
    'found' => FALSE,
    'total' => 0,
    'overlimited' => FALSE,
    'rendered' => '',
  );

  $related_content = _usanetwork_tv_shows_cache_get_limited_related_gallery_content($tv_show_node, $start_from, $limit);

  if (!empty($related_content)) {
    $last_entry = end($related_content);
    $items_last = _usanetwork_tv_shows_cache_get_number_of_last_items($tv_show_node, $last_entry->entity_type, $last_entry->entity_id);

    $response['found'] = TRUE;
    $response['total'] = count($related_content);
    $response['rendered'] = _usanetwork_media_gallery_render_related_content_items_block($related_content, TRUE);

    if ($items_last == 0 || $items_last <= $limit) {
      $response['overlimited'] = TRUE;
    }
    else {
      $response['overlimited'] = FALSE;
    }

    return drupal_json_output($response);
  }
  elseif (empty($related_content) && $start_from > 0) {
    $response['overlimited'] = TRUE;
  }

  return drupal_json_output($response);
}
