<?php

/**
 * @file
 * Code for the usanetwork_media_gallery feature.
 */
include_once 'usanetwork_media_gallery.features.inc';

/**
 *  Implements hook_block_info().
 */
function usanetwork_media_gallery_block_info() {
  $blocks = array();

  $blocks['usa_gallery_central_gallery'] = array(
    'info' => 'Consumptionator: Media gallery slides',
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usa_gallery_episode_gallery'] = array(
    'info' => 'Consumptionator: Episode gallery',
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usa_gallery_consumptionator_main'] = array(
    'info' => 'Consumptionator: Media gallery block',
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 *  Implements hook_block_view().
 */
function usanetwork_media_gallery_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'usa_gallery_central_gallery':
      $block['subject'] = '';
      $block['content'] = _usanetwork_media_gallery_consumptionator_gallery_slides_block();
      break;

    case 'usa_gallery_episode_gallery':
      $block['subject'] = '';
      $block['content'] = _usanetwork_media_gallery_consumptionator_episodes_block();
      break;

    case 'usa_gallery_consumptionator_main':
      $block['subject'] = '';
      $block['content'] = _usanetwork_media_gallery_consumptionator_gallery_block();
      break;
  }

  return $block;
}


/**
 * Implements hook_theme().
 */
function usanetwork_media_gallery_theme($existing, $type, $theme, $path) {
  return array(
    'usanetwork_media_gallery_consumptionator_slide' => array(
      'variables' => array(
        'gigya_id' => NULL,
        'image' => NULL,
        'info' => array(
          'description' => NULL,
        ),
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-slide',
    ),
    'usanetwork_media_gallery_consumptionator_slides' => array(
      'variables' => array(
        'slides' => array(),
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-slides',
    ),
    'usanetwork_media_gallery_consumptionator_episode_slide_horizontal' => array(
      'variables' => array(
        'gallery_url' => NULL,
        'image_url' => NULL,
        'title' => NULL,
        'season' => NULL,
        'episode' => NULL,
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-episode-slide-horizontal',
    ),
    'usanetwork_media_gallery_consumptionator_episode_slide_vertical' => array(
      'variables' => array(
        'gallery_url' => NULL,
        'image_url' => NULL,
        'title' => NULL,
        'season' => NULL,
        'episode' => NULL,
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-episode-slide-vertical',
    ),
    'usanetwork_media_gallery_consumptionator_episode_slides' => array(
      'variables' => array(
        'gallery_type' => NULL,
        'slides_vertical' => array(),
        'slides_horizontal' => array(),
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator-episode-slides',
    ),
    'usanetwork_media_gallery_consumptionator' => array(
      'variables' => array(
        'slider' => NULL,
        'episodic_gallery' => NULL,
      ),
      'path' => $path . '/templates',
      'template' => 'usanetwork-media-gallery-consumptionator',
    ),
  );
}


/**
 * Renders main gallery block for consumptionator page.
 */
function _usanetwork_media_gallery_consumptionator_gallery_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  return theme('usanetwork_media_gallery_consumptionator', array(
    'slider' => _usanetwork_media_gallery_consumptionator_gallery_slides_block(),
    'episodic_gallery' => _usanetwork_media_gallery_consumptionator_episodes_block(),
  ));
}

/**
 * Renders main gallery on MediaGallery page.
 */
function _usanetwork_media_gallery_consumptionator_gallery_slides_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $node = menu_get_object();

  if (isset($node->type) && $node->type == 'media_gallery') {
    $slides = array();

    $gallery_field = field_get_items('node', $node, 'field_media_items');

    $image_cover_field = field_get_items('node', $node, 'field_cover_item');
    if (!empty($image_cover_field)) {
      array_unshift($gallery_field, reset($image_cover_field));
    }
    if (!empty($gallery_field) && is_array($gallery_field)) {
      foreach ($gallery_field as $gallery_file) {
        if (is_array($gallery_file)) {
          $gallery_file = (object)$gallery_file;
        }

        $slide_variables = array(
          'gigya_id' => NULL,
          'image' => theme_image(array(
            'path' => $gallery_file->uri,
            'attributes' => array(),
          )),
          'info' => array(
            'description' => '',
          ),
        );

        $caption_field = field_get_items('file', $gallery_file, 'field_caption');

        if (!empty($caption_field)) {
          $slide_variables['info']['description'] = $caption_field[0]['value'];
        }

        $slides[] = theme('usanetwork_media_gallery_consumptionator_slide', $slide_variables);
      }
    }

    return theme('usanetwork_media_gallery_consumptionator_slides', array('slides' => $slides));
  }

  return '';
}

/**
 * Renders episodes gallery on MediaGallery page.
 */
function _usanetwork_media_gallery_consumptionator_episodes_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $node = menu_get_object();

  if (isset($node->type) && $node->type == 'media_gallery') {
    if (!empty($node->field_show) && !empty($node->field_gallery_type)) {
      $node_wrapper = entity_metadata_wrapper('node', $node);

      $show_nid = $node_wrapper->field_show->nid->value();
      $gallery_type = $node_wrapper->field_gallery_type->value();

      $galleries_list = _usanetwork_media_gallery_get_galleries($show_nid, $gallery_type);

      if (!empty($galleries_list)) {
        $rendered_items = array();

        foreach ($galleries_list as $gallery_item) {
          if ($gallery_item->nid == $node->nid) {
            continue;
          }

          $gallery_item_vertical = array(
            'gallery_url' => url('node/' . $gallery_item->nid),
            'image_url' => !empty($gallery_item->uri)
              ? image_style_url('111x74', $gallery_item->uri)
              : '',
            'title' => $gallery_item->title,
            'season' => $gallery_item->field_season_id_value,
            'episode' => $gallery_item->field_episode_number_value,
          );

          $gallery_item_horizontal = array(
            'gallery_url' => url('node/' . $gallery_item->nid),
            'image_url' => !empty($gallery_item->uri)
              ? image_style_url('full_episodes_633x356', $gallery_item->uri)
              : '',
            'title' => $gallery_item->title,
            'season' => $gallery_item->field_season_id_value,
            'episode' => $gallery_item->field_episode_number_value,
          );

          $rendered_items['slides_vertical'][] = theme('usanetwork_media_gallery_consumptionator_episode_slide_vertical', $gallery_item_vertical);
          $rendered_items['slides_horizontal'][] = theme('usanetwork_media_gallery_consumptionator_episode_slide_horizontal', $gallery_item_horizontal);
        }

        if (!empty($rendered_items)) {
          return theme('usanetwork_media_gallery_consumptionator_episode_slides', array(
            'gallery_type' => $gallery_type,
            'slides_vertical' => $rendered_items['slides_vertical'],
            'slides_horizontal' => $rendered_items['slides_horizontal'],
          ));
        }
      }
    }
  }

  return '';
}

/**
 * Returns data list of media galleries of current show using TV Season node id.
 *
 * @param $show_nid
 * @param $season_nid
 */
function _usanetwork_media_gallery_get_galleries($show_nid, $gallery_type) {
  $query = db_select('node', 'n');
  $query->fields('n', array('nid', 'title', 'created'));
  $query->join('field_data_field_show', 'sh', 'n.nid=sh.entity_id');
  $query->leftJoin('field_data_field_season', 'se', 'n.nid=se.entity_id');
  $query->join('field_data_field_gallery_type', 'gt', 'n.nid=gt.entity_id');
  $query->leftJoin('field_data_field_season_id', 'se_id', 'se.field_season_target_id=se_id.entity_id');
  $query->fields('se_id', array('field_season_id_value'));
  $query->leftJoin('field_data_field_episode', 'ep', 'n.nid=ep.entity_id');
  $query->leftJoin('node', 'ep_node', 'ep.field_episode_target_id=ep_node.nid');
  $query->leftJoin('field_data_field_episode_number', 'ep_number', 'ep_node.nid=ep_number.entity_id');
  $query->fields('ep_number', array('field_episode_number_value'));
  $query->leftJoin('field_data_field_cover_item', 'cover', 'n.nid=cover.entity_id');
  $query->fields('cover', array('field_cover_item_fid'));
  $query->leftJoin('file_managed', 'cover_file', 'cover_file.fid=cover.field_cover_item_fid');
  $query->fields('cover_file', array('uri'));

  $query->condition('sh.field_show_target_id', $show_nid);
  $query->condition('n.status', 1);
  $query->condition('n.type', 'media_gallery');
  $query->condition('gt.field_gallery_type_value', $gallery_type);

  return $query->execute()->fetchAll();
}
