<?php
/**
 * @file
 * usanetwork_blocks.features.usanetwork_blocks.inc
 */

/**
 * Implements hook_usanetwork_blocks_defaults().
 */
function usanetwork_tv_shows_syndicated_state() {
$tv_show_node = array();
  $tv_show_node['Benched'] = array(
  'title' => 'Benched',
  'syndicated' => TRUE,
);
//  $tv_show_node['Burn Notice'] = array(
//  'title' => 'Burn Notice',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['CSI'] = array(
//  'title' => 'CSI',
//  'syndicated' => TRUE,
//);
//  $tv_show_node['Chrisley Knows Best'] = array(
//  'title' => 'Chrisley Knows Best',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Covert Affairs'] = array(
//  'title' => 'Covert Affairs',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Daytime'] = array(
//  'title' => 'Daytime',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Dig'] = array(
//  'title' => 'Dig',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Graceland'] = array(
//  'title' => 'Graceland',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['House'] = array(
//  'title' => 'House',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Law & Order: Criminal Intent'] = array(
//  'title' => 'Law & Order: Criminal Intent',
//  'syndicated' => TRUE,
//);
//  $tv_show_node['Law & Order: SVU'] = array(
//  'title' => 'Law & Order: SVU',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Modern Family'] = array(
//  'title' => 'Modern Family',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['NCIS'] = array(
//  'title' => 'NCIS',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['NCIS: Los Angeles'] = array(
//  'title' => 'NCIS: Los Angeles',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Necessary Roughness'] = array(
//  'title' => 'Necessary Roughness',
//  'syndicated' => TRUE,
//);
//  $tv_show_node['Partners in Crime'] = array(
//  'title' => 'Partners in Crime',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Playing House'] = array(
//  'title' => 'Playing House',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Psych'] = array(
//  'title' => 'Psych',
//  'syndicated' => TRUE,
//);
//  $tv_show_node['Royal Pains'] = array(
//  'title' => 'Royal Pains',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Rush'] = array(
//  'title' => 'Rush',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Satisfaction'] = array(
//  'title' => 'Satisfaction',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Sirens'] = array(
//  'title' => 'Sirens',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Suits'] = array(
//  'title' => 'Suits',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Summer Camp'] = array(
//  'title' => 'Summer Camp',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['The Moment'] = array(
//  'title' => 'The Moment',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['WWE Raw'] = array(
//  'title' => 'WWE Raw',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['Westminster Kennel Club Dog Show'] = array(
//  'title' => 'Westminster Kennel Club Dog Show',
//  'syndicated' => FALSE,
//);
//  $tv_show_node['White Collar'] = array(
//  'title' => 'White Collar',
//  'syndicated' => FALSE,
//);
return $tv_show_node;
}
