<?php
/**
 * @file
 * Code for the usanetwork_ads feature.
 */

include_once 'usanetwork_ads.features.inc';


/**
 * Helper that converts menu item router paths to a more easily understood form.
 */
function _usanetwork_ads_clean_menu_item_path($path) {

  // Change "%node" to "[content id]" to be more easily understood by
  // non-Drupalists.
  $path = str_replace('%node', '[content id]', $path);

  return $path;
}


/**
 * Helper that returns menu paths (from hook_menu() implementations) for all
 * usanetwork_* modules.
 */
function _usanetwork_ads_get_usanetwork_menu_paths() {

  $menu_paths = array();
  $hook_menu_modules = module_implements('menu');

  foreach ($hook_menu_modules as $module) {
    if (strpos($module, 'usanetwork_') === 0) {
      $function_name = $module . '_menu';
      $module_menu_items = $function_name();
      foreach ($module_menu_items as $item_path => $item_data) {
        if (strpos($item_path, 'admin') === FALSE && $item_path != 'home') {
          $menu_paths[ $item_path ] = _usanetwork_ads_clean_menu_item_path($item_path);
        }
      }
    }
  }

  asort($menu_paths);

  return $menu_paths;
}


/**
 * Implements hook_permission().
 */
function usanetwork_ads_permission() {

  $permissions = array();
  $permissions['administer usanetwork dart settings'] = array(
    'title' => t('Administer USA Network DART Ad Settings'),
    'description' => '',
  );

  return $permissions;
}


/**
 * Implements hook_menu().
 */
function usanetwork_ads_menu() {

  $items = array();
  $items['admin/usanetwork-ads/dart-settings'] = array(
    #'type' => MENU_CALLBACK,
    'title' => t('USA Network DART Ad Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_usanetwork_ads_site_metric_settings_form'),
    'access arguments' => array('administer usanetwork dart settings'),
  );

  return $items;
}

/**
 * Helper that returns TV Show nodes.
 */
function _usanetwork_ads_get_tv_show_nodes() {

  $tv_show_nodes_query = new EntityFieldQuery();
  $tv_show_nodes_query->entityCondition('entity_type', 'node');
  $tv_show_nodes_query->entityCondition('bundle', 'tv_show');
  $tv_show_nodes_query->propertyCondition('status', 1);
  $tv_show_nodes_query->propertyOrderBy('title', 'ASC');
  $tv_show_nodes_result = $tv_show_nodes_query->execute();

  $tv_show_nodes = array();

  if (isset($tv_show_nodes_result['node'])) {
    foreach ($tv_show_nodes_result['node'] as $result) {
      $tv_show_nodes[ $result->nid ] = node_load($result->nid, $result->vid);
    }
  }

  return $tv_show_nodes;
}

/**
 * Helper for adding omniture settings form elements.
 */
function _usanetwork_ads_omniture_site_metric_form_elements($id, $display_id, &$parent_element, &$existing_values, $clean_empty_values = FALSE) {

  $parent_element['omniture'] = array(
    '#type' => 'container',
    '#tree' => TRUE,
    '#prefix' => '<div id="' . $id . '-omniture-values"><div style="font-weight: bold;">' . t('Omniture Variables') . '</div>',
    '#suffix' => '</div>',
  );

  // Clean up empty values to avoid duplicate empty form elements.
  if ($clean_empty_values) {
    foreach ($existing_values as $delta => $values) {
      if (!$values['key'] && !$values['value']) {
        unset($existing_values[ $delta ]);
      }
    }
    $existing_values = array_values($existing_values);
  }

  // Add a new empty set of fields.
  $existing_values[] = array('key' => '', 'value' => '');

  // Now add all of the elements.
  foreach ($existing_values as $delta => $values) {
    $parent_element['omniture'][ $delta ] = array(
      '#type' => 'fieldset',
      '#tree' => TRUE,
    );
    $parent_element['omniture'][ $delta ]['key'] = array(
      '#type' => 'textfield',
      '#title' => t('Variable Name'),
      '#default_value' => $values['key'],
    );
    $parent_element['omniture'][ $delta ]['value'] = array(
      '#type' => 'textfield',
      '#title' => t('Value'),
      '#default_value' => $values['value'],
    );
  }

  // Add the "Add Another" button.
  $parent_element['add_omniture'] = array(
    '#type' => 'button',
    '#value' => t('Add A "!id" Variable', array('!id' => $display_id)),
    '#href' => '',
    '#ajax' => array(
      'callback' => '_usanetwork_ads_add_omniture_value',
      'wrapper' => $id . '-omniture-values',
    ),
  );
}


/**
 * Helper that returns the ad/tracking settings form elements for the homepage.
 */
function _usanetwork_ads_homepage_site_metric_form_elements(&$parent_element, &$form_state) {

  $default_settings = $form_state['storage']['default_settings'];

  $parent_element['home'] = array(
    '#type' => 'fieldset',
    '#title' => t('Homepage Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $parent_element['home']['sect'] = array(
    '#type' => 'textfield',
    '#title' => t('"sect" value'),
    '#default_value' => isset($default_settings['home']['sect']) ?
        $default_settings['home']['sub'] : '',
  );
  $parent_element['home']['sub'] = array(
    '#type' => 'textfield',
    '#title' => t('"sub" value'),
    '#default_value' => isset($default_settings['home']['sub']) ?
        $default_settings['home']['sub'] : '',
  );
  $parent_element['home']['sub2'] = array(
    '#type' => 'textfield',
    '#title' => t('"sub2" value'),
    '#default_value' => isset($default_settings['home']['sub2']) ?
        $default_settings['home']['sub2'] : '',
  );

  // Omniture unlimited value form.
  $form_state['storage']['default_settings']['home']['omniture'] = isset($form_state['storage']['default_settings']['home']['omniture']) ?
      $form_state['storage']['default_settings']['home']['omniture'] : array();
  _usanetwork_ads_omniture_site_metric_form_elements('homepage', t('Homepage'), $parent_element['home'],
      $form_state['storage']['default_settings']['home']['omniture'], $form_state['new_form']);
}


/**
 * Helper that returns the ad/tracking settings form elements for tv_show nodes.
 */
function _usanetwork_ads_tv_show_site_metric_form_elements(&$parent_element, &$form_state) {

  $default_settings = $form_state['storage']['default_settings'];

  $parent_element['node']['tv_show'] = array(
    '#type' => 'fieldset',
    '#title' => t('TV Show Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  // Default "sub" and "sub2" form elements.
  $parent_element['node']['tv_show']['default']['sub'] = array(
    '#type' => 'textfield',
    '#title' => t('Default landing page "sub" value'),
    '#default_value' => isset($default_settings['node']['tv_show']['default']['sub']) ?
        $default_settings['node']['tv_show']['default']['sub'] : '',
  );
  $parent_element['node']['tv_show']['default']['sub2'] = array(
    '#type' => 'textfield',
    '#title' => t('Default landing page "sub2" value'),
    '#default_value' => isset($default_settings['node']['tv_show']['default']['sub2']) ?
        $default_settings['node']['tv_show']['default']['sub2'] : '',
  );

  // Add a set of dart form elements per tv_show node.
  if ($tv_show_nodes = _usanetwork_ads_get_tv_show_nodes()) {
    foreach ($tv_show_nodes as $node) {
      $parent_element['node']['tv_show'][ $node->nid ] = array(
        '#type' => 'fieldset',
        '#title' => t('Show:  %tv_show_title', array('%tv_show_title' => $node->title)),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );
      $parent_element['node']['tv_show'][ $node->nid ]['sect'] = array(
        '#type' => 'textfield',
        '#title' => t('"sect" Value'),
        '#default_value' => isset($default_settings['node']['tv_show'][ $node->nid ]['sect']) ?
            $default_settings['node']['tv_show'][ $node->nid ]['sect'] : '',
      );
      /*
        TODO? Per show landing page "sub" and "sub2" over-rides?
      $form['usanetwork_ads_site_metric_settings']['node']['tv_show'][ $node->nid ]['sub'] = array(
        '#type' => 'textfield',
        '#title' => t('Landing page "sub" value'),
        '#default_value' => isset($default_settings['node']['tv_show'][ $node->nid ]['sub']) ?
            $default_settings['node']['tv_show'][ $node->nid ]['sub'] : '',
      );
      $form['usanetwork_ads_site_metric_settings']['node']['tv_show'][ $node->nid ]['sub2'] = array(
        '#type' => 'textfield',
        '#title' => t('Landing page "sub2" value'),
        '#default_value' => isset($default_settings['node']['tv_show'][ $node->nid ]['sub2']) ?
            $default_settings['node']['tv_show'][ $node->nid ]['sub2'] : '',
      );
      //*/
      // Omniture unlimited value form.
      $id = 'tv-show-' . $node->nid;
      $display_id = htmlspecialchars_decode(check_plain($node->title));
      $form_state['storage']['default_settings']['node']['tv_show'][ $node->nid ]['omniture'] = isset($form_state['storage']['default_settings']['node']['tv_show'][ $node->nid ]['omniture']) ?
          $form_state['storage']['default_settings']['node']['tv_show'][ $node->nid ]['omniture'] : array();
      _usanetwork_ads_omniture_site_metric_form_elements($id, $display_id, $parent_element['node']['tv_show'][ $node->nid ],
          $form_state['storage']['default_settings']['node']['tv_show'][ $node->nid ]['omniture'], $form_state['new_form']);
    }
  }
  // If no tv_show nodes are found, let the user know.
  else {
    $parent_element['node']['tv_show']['no_results']['#markup'] = t('There are no TV shows available.');
  }
}


/**
 * Helper that returns the ad/tracking settings form elements for content types.
 */
function _usanetwork_ads_content_type_site_metric_form_elements(&$parent_element, &$form_state) {

  $default_settings = $form_state['storage']['default_settings'];

  // Define node types used for displaying content.
  $content_node_types = array(
    'person' => t('Person'),
    'tv_episode' => t('TV Episode'),
    'media_gallery' => t('Media Gallery'),
    'usa_video' => t('MPX Video'),
    'usa_tve_video' => t('TVE Video'),
  );

  $parent_element['node_type'] = array(
    '#type' => 'fieldset',
    '#title' => t('Content Type Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  foreach ($content_node_types as $node_type => $title) {
    $parent_element['node_type'][ $node_type ] = array(
      '#type' => 'fieldset',
      '#title' => t('Type:  %type', array('%type' => $title)),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $parent_element['node_type'][ $node_type ]['sect'] = array(
      '#type' => 'textfield',
      '#title' => t('"sect" value'),
      '#default_value' => isset($default_settings['node_type'][ $node_type ]['sect']) ?
          $default_settings['node_type'][ $node_type ]['sect'] : '',
      '#description' => t('Setting a "sect" value here will over-ride the value set for the associated TV Show.'),
    );
    $parent_element['node_type'][ $node_type ]['sub'] = array(
      '#type' => 'textfield',
      '#title' => t('"sub" value'),
      '#default_value' => isset($default_settings['node_type'][ $node_type ]['sub']) ?
          $default_settings['node_type'][ $node_type ]['sub'] : '',
    );
    $parent_element['node_type'][ $node_type ]['sub2'] = array(
      '#type' => 'textfield',
      '#title' => t('"sub2" value'),
      '#default_value' => isset($default_settings['node_type'][ $node_type ]['sub2']) ?
          $default_settings['node_type'][ $node_type ]['sub2'] : '',
    );
    // Omniture unlimited value form.
    $id = 'node-type-' . $node_type;
    $display_id = t('@type', array('@type' => $title));
    $form_state['storage']['default_settings']['node_type'][ $node_type ]['omniture'] = isset($form_state['storage']['default_settings']['node_type'][ $node_type ]['omniture']) ?
        $form_state['storage']['default_settings']['node_type'][ $node_type ]['omniture'] : array();
    _usanetwork_ads_omniture_site_metric_form_elements($id, $display_id, $parent_element['node_type'][ $node_type ],
        $form_state['storage']['default_settings']['node_type'][ $node_type ]['omniture'], $form_state['new_form']);
  }
}


/**
 * Helper that returns the ad/tracking settings form elements for custom paths.
 */
function _usanetwork_ads_custom_path_site_metric_form_elements(&$parent_element, &$form_state) {

  $default_settings = $form_state['storage']['default_settings'];

  $parent_element['path'] = array(
    '#type' => 'fieldset',
    '#title' => t('Path Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  foreach (_usanetwork_ads_get_usanetwork_menu_paths() as $path => $clean_path) {
    $parent_element['path'][ $path ] = array(
      '#type' => 'fieldset',
      '#title' => t('Path:  %path', array('%path' => $clean_path)),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $parent_element['path'][ $path ]['sect'] = array(
      '#type' => 'textfield',
      '#title' => t('"sect" value'),
      '#default_value' => isset($default_settings['path'][ $path ]['sect']) ?
          $default_settings['path'][ $path ]['sect'] : '',
    );
    // Tell user that setting a "sect" value for "node/*" paths will over-ride
    // the sect value set per TV Show.
    if (strpos($path, 'node/') === 0) {
      $parent_element['path'][ $path ]['sect']['#description'] =
          t('Setting a "sect" value here will over-ride the value set for the associated TV Show.');
    }
    $parent_element['path'][ $path ]['sub'] = array(
      '#type' => 'textfield',
      '#title' => t('"sub" value'),
      '#default_value' => isset($default_settings['path'][ $path ]['sub']) ?
          $default_settings['path'][ $path ]['sub'] : '',
    );
    $parent_element['path'][ $path ]['sub2'] = array(
      '#type' => 'textfield',
      '#title' => t('"sub2" value'),
      '#default_value' => isset($default_settings['path'][ $path ]['sub2']) ?
          $default_settings['path'][ $path ]['sub2'] : '',
    );
    // Omniture unlimited value form.
    $id_clean_path = preg_replace('|[^a-zA-Z0-9]+|', '-', $path);
    $id = 'custom-path-' . strtolower($id_clean_path);
    $display_id = t('@path', array('@path' => $clean_path));
    $form_state['storage']['default_settings']['path'][ $path ]['omniture'] = isset($form_state['storage']['default_settings']['path'][ $path ]['omniture']) ?
        $form_state['storage']['default_settings']['path'][ $path ]['omniture'] : array();
    _usanetwork_ads_omniture_site_metric_form_elements($id, $display_id, $parent_element['path'][ $path ],
        $form_state['storage']['default_settings']['path'][ $path ]['omniture'], $form_state['new_form']);
  }
}


/**
 * Form definition / page callback for ad settings admin page.
 */
function _usanetwork_ads_site_metric_settings_form($form, $form_state) {

  $form = array();
  $default_settings = variable_get('usanetwork_ads_site_metric_settings', array());
  $form_state['storage']['default_settings'] = isset($form_state['storage']['default_settings']) ?
      $form_state['storage']['default_settings'] : $default_settings;
  $form_state['new_form'] = isset($form_state['new_form']) ? FALSE : TRUE;

  // Set the base of the form.
  $form['usanetwork_ads_site_metric_settings'] = array(
    '#tree' => TRUE,
  );

  // Homepage ad settings.
  _usanetwork_ads_homepage_site_metric_form_elements($form['usanetwork_ads_site_metric_settings'], $form_state);

  // TV Show based ad settings.
  _usanetwork_ads_tv_show_site_metric_form_elements($form['usanetwork_ads_site_metric_settings'], $form_state);

  // Content type based ad settings.
  _usanetwork_ads_content_type_site_metric_form_elements($form['usanetwork_ads_site_metric_settings'], $form_state);

  // Path based ad settings.
  _usanetwork_ads_custom_path_site_metric_form_elements($form['usanetwork_ads_site_metric_settings'], $form_state);


  return system_settings_form($form);
}


/**
 * AJAX callback for adding omniture key|value pairs.
 */
function _usanetwork_ads_add_omniture_value($form, $form_state) {

  // Ge the form element of the button that was clicked.
  $clicked_button_parents = $form_state['triggering_element']['#parents'];
  array_pop($clicked_button_parents);
  $container = $form[ array_shift($clicked_button_parents) ];
  foreach ($clicked_button_parents as $element) {
    $container = $container[ $element ];
  }
  $container = $container['omniture'];

  // Clean empty sets beyond the first.
  $skipped_first_empty_set = FALSE;
  foreach (element_children($container) as $delta) {
    if (!$container[ $delta ]['key']['#value'] && !$container[ $delta ]['value']['#value']) {
      if (!$skipped_first_empty_set) {
        $skipped_first_empty_set = TRUE;
        continue;
      }
      unset($container[ $delta ]);
    }
  }

  return $container;
}


/**
 * Implements hook_admin_paths().
 */
function usanetwork_ads_admin_paths() {

  $paths = array();
  $paths['admin/usanetwork-ads/dart-settings'] = TRUE;

  return $paths;
}


/**
 * Helper that returns DART ad settings for a given node.
 */
function _usanetwork_ads_get_node_dart_settings($node) {

  $node_dart_settings = array('sect' => NULL, 'sub' => NULL, 'sub2' => NULL);
  $site_metric_settings = variable_get('usanetwork_ads_site_metric_settings', array());

  // Set "sect" value by TV Show.
  if ($node->type == 'tv_show') {
    $node_dart_settings['sect'] = isset($site_metric_settings['node']['tv_show'][ $node->nid ]['sect']) ?
        $site_metric_settings['node']['tv_show'][ $node->nid ]['sect'] : '';
    // Default "sub" and "sub2" values for tv_show node pages.
    $node_dart_settings['sub'] = isset($site_metric_settings['node']['tv_show']['default']['sub']) ?
        $site_metric_settings['node']['tv_show']['default']['sub'] : '';
    $node_dart_settings['sub2'] = isset($site_metric_settings['node']['tv_show']['default']['sub2']) ?
        $site_metric_settings['node']['tv_show']['default']['sub2'] : '';
  }
  else if (isset($node->field_show)) {
    $field_show_items = field_get_items('node', $node, 'field_show');
    $tv_show_nid = $field_show_items[0]['target_id'];
    if ($tv_show_nid) {
      $node_dart_settings['sect'] = isset($site_metric_settings['node']['tv_show'][ $tv_show_nid ]['sect']) ?
          $site_metric_settings['node']['tv_show'][ $tv_show_nid ]['sect'] : '';
    }
  }

  // TODO: Set values for catchall nodes.

  // Over-ride values by content type.
  $node_dart_settings['sect'] = !empty($site_metric_settings['node_type'][ $node->type ]['sect']) ?
    $site_metric_settings['node_type'][ $node->type ]['sect'] : $node_dart_settings['sect'];
  $node_dart_settings['sub'] = !empty($site_metric_settings['node_type'][ $node->type ]['sub']) ?
    $site_metric_settings['node_type'][ $node->type ]['sub'] : $node_dart_settings['sub'];
  $node_dart_settings['sub2'] = !empty($site_metric_settings['node_type'][ $node->type ]['sub2']) ?
    $site_metric_settings['node_type'][ $node->type ]['sub2'] : $node_dart_settings['sub2'];


  return $node_dart_settings;
}


/**
 * Implements hook_preprocess_page().
 */
function usanetwork_ads_preprocess_page(&$variables) {

  // Define DART ad settings via Drupal JS settings.
  $usa_dart_js_settings = array();
  $usa_dart_js_settings['USA']['DART']['values'] = array('sect' => NULL, 'sub' => NULL, 'sub2' => NULL);
  $site_metric_settings = variable_get('usanetwork_ads_site_metric_settings', array());
  $current_menu_item = menu_get_item();
  $current_menu_item_path = $current_menu_item['path'];
  $current_menu_object = menu_get_object();

  // Homepage specific settings.
  $current_menu_item = menu_get_item();
  $current_menu_object = menu_get_object();
  if (drupal_is_front_page()) {
    $usa_dart_js_settings['USA']['DART']['values']['sect'] = !empty($site_metric_settings['home']['sect']) ?
      $site_metric_settings['home']['sect'] : 'home';
    $usa_dart_js_settings['USA']['DART']['values']['sub'] = !empty($site_metric_settings['home']['sub']) ?
      $site_metric_settings['home']['sub'] : '';
    $usa_dart_js_settings['USA']['DART']['values']['sub2'] = !empty($site_metric_settings['home']['sub2']) ?
      $site_metric_settings['home']['sub2'] : '';
  }
  // Node page based settings.
  else if ($current_menu_item_path == 'node/%' &&
      is_object($current_menu_object) && isset($current_menu_object->nid)) {
    $usa_dart_js_settings['USA']['DART']['values'] = _usanetwork_ads_get_node_dart_settings($current_menu_object);
  }
  // Path based settings.
  else {
    // If there is a node in $variables, get these values first.  Then over-ride
    // with the path specific values.
    if (isset($variables['node'])) {
      $usa_dart_js_settings['USA']['DART']['values'] = _usanetwork_ads_get_node_dart_settings($variables['node']);
    }
    $usa_dart_js_settings['USA']['DART']['values']['sect'] = !empty($site_metric_settings['path'][ $current_menu_item_path ]['sect']) ?
      $site_metric_settings['path'][ $current_menu_item_path ]['sect'] : $usa_dart_js_settings['USA']['DART']['values']['sect'];
    $usa_dart_js_settings['USA']['DART']['values']['sub'] = !empty($site_metric_settings['path'][ $current_menu_item_path ]['sub']) ?
      $site_metric_settings['path'][ $current_menu_item_path ]['sub'] : $usa_dart_js_settings['USA']['DART']['values']['sub'];
    $usa_dart_js_settings['USA']['DART']['values']['sub2'] = !empty($site_metric_settings['path'][ $current_menu_item_path ]['sub2']) ?
      $site_metric_settings['path'][ $current_menu_item_path ]['sub2'] : $usa_dart_js_settings['USA']['DART']['values']['sub2'];
  }

  // Ensure JS settings values.
  $usa_dart_js_settings['USA']['DART']['values']['sect'] = !empty($usa_dart_js_settings['USA']['DART']['values']['sect']) ?
      $usa_dart_js_settings['USA']['DART']['values']['sect'] : 'other';
  $usa_dart_js_settings['USA']['DART']['values']['sub'] = !empty($usa_dart_js_settings['USA']['DART']['values']['sub']) ?
      $usa_dart_js_settings['USA']['DART']['values']['sub'] : '';
  $usa_dart_js_settings['USA']['DART']['values']['sub2'] = !empty($usa_dart_js_settings['USA']['DART']['values']['sub2']) ?
      $usa_dart_js_settings['USA']['DART']['values']['sub2'] : '';


  // Set the JS settings for ads.
  drupal_add_js($usa_dart_js_settings, 'setting');
}

/**
 * Helper tha returns omniture variables given an array of omniture settings.
 */
function _usanetwork_ads_get_omniture_variables($omniture_settings) {

  if (!is_array($omniture_settings)) {
    return array();
  }

  $omniture_variables = array();

  foreach ($omniture_settings as $delta => $setting) {
    $key = trim(check_plain($setting['key']));
    $value = trim(check_plain($setting['value']));
    if ($key && $value) {
      $omniture_variables[ $key ] = $value;
    }
  }

  return $omniture_variables;
}


/**
 * Helper that returns omniture variables for a given node.
 */
function _usanetwork_ads_get_node_omniture_variables($node) {

  $node_omniture_settings = array();
  $site_metric_settings = variable_get('usanetwork_ads_site_metric_settings', array());

  // Set "sect" value by TV Show.
  if ($node->type == 'tv_show') {
    $node_omniture_settings =
        isset($site_metric_settings['node']['tv_show'][ $node->nid ]['omniture']) && is_array($site_metric_settings['node']['tv_show'][ $node->nid ]['omniture']) ?
        $site_metric_settings['node']['tv_show'][ $node->nid ]['omniture'] : array();
  }
  else if (isset($node->field_show)) {
    $field_show_items = field_get_items('node', $node, 'field_show');
    $tv_show_nid = $field_show_items[0]['target_id'];
    if ($tv_show_nid) {
      $node_omniture_settings =
          isset($site_metric_settings['node']['tv_show'][ $tv_show_nid ]['omniture']) && is_array($site_metric_settings['node']['tv_show'][ $tv_show_nid ]['omniture']) ?
          $site_metric_settings['node']['tv_show'][ $tv_show_nid ]['omniture'] : array();
    }
  }

  $node_omniture_variables = _usanetwork_ads_get_omniture_variables($node_omniture_settings);

  // Variable over-rides by content type.
  $node_type_omniture_settings =
      isset($site_metric_settings['node_type'][ $node->type ]['omniture']) && is_array($site_metric_settings['node_type'][ $node->type ]['omniture']) ?
      $site_metric_settings['node_type'][ $node->type ]['omniture'] : array();
  $node_type_omniture_variables = _usanetwork_ads_get_omniture_variables($node_type_omniture_settings);
  $node_omniture_variables = $node_type_omniture_variables + $node_omniture_variables;

  return $node_omniture_variables;
}


/**
 * Implements hook_sitecatalyst_variables().
 */
function usanetwork_ads_sitecatalyst_variables($page_variables) {

  $omniture_variables = array();
  $site_metric_settings = variable_get('usanetwork_ads_site_metric_settings', array());
  $current_menu_item = menu_get_item();
  $current_menu_item_path = $current_menu_item['path'];
  $current_menu_object = menu_get_object();

  // Homepage specific settings.
  if (drupal_is_front_page()) {
    $omniture_settings = isset($site_metric_settings['home']['omniture']) ?
        $site_metric_settings['home']['omniture'] : array();
    $omniture_variables = _usanetwork_ads_get_omniture_variables($omniture_settings);
  }
  // Node page based settings.
  else if ($current_menu_item_path == 'node/%' &&
      is_object($current_menu_object) && isset($current_menu_object->nid)) {
    $omniture_variables = _usanetwork_ads_get_node_omniture_variables($current_menu_object);
  }
  // Path based settings.
  else {
    // If there is a node in $variables, get these values first.  Then over-ride
    // with the path specific values.
    if (isset($page_variables['node'])) {
      $omniture_variables = _usanetwork_ads_get_node_omniture_variables($page_variables['node']);
    }
    $path_omniture_settings = isset($site_metric_settings['path'][ $current_menu_item_path ]['omniture']) ?
        $site_metric_settings['path'][ $current_menu_item_path ]['omniture'] : array();
    $path_omniture_variables = _usanetwork_ads_get_omniture_variables($path_omniture_settings);
    $omniture_variables = $path_omniture_variables + $omniture_variables;
  }

  return array('variables' => $omniture_variables);
}
