<?php

define('USANETWORK_BLOG_MIGRATE_LIFETIME_HOURS', 24);
/**
 *  Implements hook_form_FORM_ID_alter().
 */
function usanetwork_blog_migrate_form_usanetwork_settings_form_alter(&$form, &$form_state, $form_id) {
  $form['vox_blog_migrate_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('VOX blog migrate settings'),
    '#description' => t('Display settings of VOX feed migration process'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['vox_blog_migrate_settings']['vox_blog_migrate_mrrobot_nid'] = array(
    '#type' => 'textfield',
    '#title' => t('Mr. Robot blog.'),
    '#description' => t('Blog of Mr. Robot show that will use for migrate VOX blog posts.'),
    '#default_value' => variable_get('vox_blog_migrate_mrrobot_nid', NULL),
    '#autocomplete_path' => 'ajax/consumptionator_blog/autocomplete',
  );
}

/**
 * Implements hook_init().
 */
function usanetwork_blog_migrate_init() {
  module_load_include('inc', 'usanetwork_blog_migrate', 'vox_blog_migrate');
}

/**
 * Implements hook_cron().
 */
function usanetwork_blog_migrate_cron() {
  // If the minimum lifetime hasn't been passed, skip.
  $lifetime = REQUEST_TIME - variable_get('usanetwork_blog_migrate_last', 0);
  if ($lifetime < USANETWORK_BLOG_MIGRATE_LIFETIME_HOURS * 60 * 60) {
    return;
  }
  variable_set('usanetwork_blog_migrate_last', REQUEST_TIME);

  $machine_names = array('usanetwork_vox_blog');

  foreach ($machine_names as $machine_name) {
    // Log that we're starting this update.
    watchdog('usanetwork_migrate', 'Starting @migration migration update.',
        array('@migration' => $machine_name), WATCHDOG_NOTICE);
    drupal_set_message(t('USANETWORK MIGRATE:  Starting @migration migration update.',
        array('@migration' => $machine_name)));
    $migration = Migration::getInstance($machine_name);
    // Prepare to Update the contents/data
    $migration->prepareUpdate();
    // Trigger the migration
    $result = $migration->processImport();
    // Log that we've completed this update.
    watchdog('usanetwork_migrate', 'Completed @migration migration update.',
        array('@migration' => $machine_name), WATCHDOG_NOTICE);
    drupal_set_message(t('USANETWORK MIGRATE:  Completed @migration migration update.',
        array('@migration' => $machine_name)));
  }
}
