<?php

/**
 * @file
 * Code for the usanetwork_blocks feature.
 */
include_once 'usanetwork_blocks.features.inc';

/**
 * @file
 * USA blocks - custom blocks that are not generated with views or stored elsewhere
 */

/**
 * Implements hook_block_info().
 */
function usanetwork_blocks_block_info() {
  $blocks = array();
  $blocks['usa_footer_message'] = array(
    'info' => t('USA: Footer message'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['usa_footer_links'] = array(
    'info' => t('USA: Footer links'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['usa_footer_promos'] = array(
    'info' => t('Usanetwork Footer: Promo links'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  $blocks['usanetwork_social_carousel'] = array(
    'info' => t('Social carousel'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['usanetwork_catchall_related'] = array(
    'info' => t('Usanetwork catchall page: related content.'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_blocks_block_view($delta) {
  $block = array();
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'usa_footer_message':
      drupal_add_css(drupal_get_path("module", "usanetwork_blocks") . "/theme/css/usanetwork_block.css");
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_usa_footer_message();
      break;
    case 'usa_footer_links':
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_usa_footer_links();
      break;
    case 'usa_footer_promos':
      $block['subject'] = '';
      $block['content'] = _usanetwork_blocks_usa_footer_promos_block_content();
      break;
    case 'usanetwork_social_carousel':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _usanetwork_blocks_social_carousel_block_content(),
      );
      break;
    case 'usanetwork_catchall_related':
      $block['subject'] = '';
      $block['content'] = _usanetwork_catchall_related_content();
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function usanetwork_blocks_theme($existing, $type, $theme, $path) {
  // @TODO: add variables, make these real theme functions
  return array(
    'usa_footer_promos' => array(
      'variables' => array(
        'links' => array(
          0 => array(
            'image_url' => NULL,  // URL of image
            'url' => NULL,        // URL of link
            'title' => NULL,      // Title of link
            'class' => NULL,      // Additional classes of link
            'column' => NULL,     // Number of column of link wrapper
            'target' => NULL,     // Value of "target" attribute of link
          ),
        ),
        'columns' => NULL,
      ),
      'path' => $path . '/theme',
      'template' => 'usa-footer-promos',
    ),
    'usanetwork_social_carousel' => array(
      'variables' => array(
        'text1' => NULL,
        'text2' => NULL,
        'promos' => NULL,
      ),
      'path' => $path . '/theme',
      'template' => 'usa-social-carousel',
    ),
  );
}

/**
 *  Implements hook_image_default_styles().
 */
function usanetwork_blocks_image_default_styles() {
  $styles = array();

  $styles['usa_footer_promos_link_image'] = array(
    'label' => t('Usanetwork footer: promo link image'),
    'effects' => array(
      0 => array(
        'name' => 'focal_point_scale_and_crop',
        'data' => array(
          'width' => 75,
          'height' => 75,
        ),
        'weight' => 0,
      ),
      1 => array(
        'label' => 'Scale and crop',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 75,
          'height' => 75,
        ),
        'weight' => 0,
      ),
    ),
  );

  $styles['390x390'] = array(
    'effects' => array(
      array(
        'name' => 'focal_point_scale_and_crop',
        'data' => array(
          'width' => 390,
          'height' => 390,
        ),
        'weight' => 0,
      ),
      array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 390,
          'height' => 390,
        ),
        'weight' => 1,
      ),
    ),
  );
  return $styles;
}

/**
 *  Implements hook_form_FORM_ID_alter().
 */
function usanetwork_blocks_form_usanetwork_settings_form_alter(&$form, &$form_state, $form_id) {
  $footer_promo_links = variable_get('usa_footer_promos_links', array());

  // Determinate default number of fields
  if (empty($form_state['links_number'])) {
    $form_state['links_number'] = 1;
  }

  $form['footer']['promo_links'] = array(
    '#type' => 'fieldset',
    '#title' => t('Promo links'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#prefix' => '<div id="usanetwork-footer-promo-links-wrapper">',
    '#suffix' => '</div>',
  );

  // Increment the number with links that already saved
  if (!empty($footer_promo_links)) {
    $form_state['links_number'] += count($footer_promo_links);
  }

  // Add new form elements with saved links
  for ($i = 0; $i < $form_state['links_number']; $i++) {
    $array_element = _usanetwork_blocks_usa_footer_links_get_empty_fieldset_item($i, $footer_promo_links);

    array_push($form['footer']['promo_links'], $array_element);
  }

  // Add "Add more" button
  $form['footer']['promo_links']['add_more'] = array(
    '#type' => 'submit',
    '#value' => t('Add more'),
    '#submit' => array('ajax_usanetwork_blocks_usa_footer_links_add_more'),
    '#ajax' => array(
      'callback' => 'ajax_usanetwork_blocks_usa_footer_links_callback',
      'wrapper' => 'usanetwork-footer-promo-links-wrapper',
    ),
  );

  // Add "Remove last" button
  if ($form_state['links_number'] > 1) {
    $form['footer']['promo_links']['remove_item'] = array(
      '#type' => 'submit',
      '#value' => t('Remove last'),
      '#submit' => array('ajax_usanetwork_blocks_usa_footer_links_remove'),
      '#ajax' => array(
        'callback' => 'ajax_usanetwork_blocks_usa_footer_links_callback',
        'wrapper' => 'usanetwork-footer-promo-links-wrapper',
      ),
    );
  }

  $form['#submit'][] = 'usanetwork_blocks_form_usanetwork_settings_form_submit';
}

/**
 * Implements hook_form_submit() for usanetwork_blocks_form_usanetwork_settings_form_alter().
 */
function usanetwork_blocks_form_usanetwork_settings_form_submit(&$form, &$form_state) {
  global $user;

  if (!empty($form_state['values'])) {
    $footer_promo_links = array();

    foreach ($form_state['values'] as $value_name => $value) {
      $matches = array();

      if (preg_match("/^usa_promo_links_link_(\d+)_(.+)$/", $value_name, $matches)) {
        if ($matches[2] == 'image' && !empty($value)) {
          $file = file_load($value);
          $file->status = FILE_STATUS_PERMANENT;
          file_save($file);
          file_usage_add($file, 'user', 'user', $user->uid);
        }

        $footer_promo_links[$matches[1]][$matches[2]] = $value;
      }
    }
  }

  // Remove empty items
  foreach ($footer_promo_links as $index => $footer_promo_link) {
    if (empty($footer_promo_link['title']) || $footer_promo_link['image'] == 0) {
      unset($footer_promo_links[$index]);
    }
  }

  variable_set('usa_footer_promos_links', $footer_promo_links);
}

/**
 * Block for Displaying Footer Message
 */
function usanetwork_blocks_usa_footer_message() {
  $render = array();
  $render['usa_footer']['body'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id ="footer-message">' . str_replace("YYYY", date("Y"), variable_get("usanetwork_footer_message", '')),
    '#suffix' => '</div>',
  );
  return $render;
}

/**
 * Block for Displaying Footer Links
 */
function usanetwork_blocks_usa_footer_links() {
  $render = menu_tree('usa-footer-bottom');

  $render['ad_chocies'] = array(
    '#type' => 'markup',
    '#prefix' => '<li id ="footer-links">' . variable_get("usanetwork_footer_ad_choices_text", ''),
    '#suffix' => '</li>',
  );
  return $render;
}

/**
 * Returns content for social_carousel_block.
 */

function _usanetwork_blocks_social_carousel_block_content() {
  $theme_variables = array();
  $homepage = usanetwork_home_get_homepage(array('usa_homepage'));
  if (!empty($homepage['node'])) {
    $homepage_nids = array_keys($homepage['node']);
    if (empty($homepage_nids[0])) {
      return '';
    }
    $homepage_node = node_load($homepage_nids[0]);
    if ($homepage_node) {
      $homepage_wrapper = entity_metadata_wrapper('node', $homepage_node);
      if (isset($homepage_wrapper->field_social_promo_title)) {
        $theme_variables['title'] = $homepage_wrapper->field_social_promo_title->value();
      }
      if (isset($homepage_wrapper->field_social_promo_additional)) {
        $theme_variables['additional'] = $homepage_wrapper->field_social_promo_additional->value();
      }
      $field_promo_items = field_get_items('node', $homepage_node, 'field_hp_ft_social');
      if (!empty($field_promo_items) && is_array($field_promo_items)) {
        foreach ($field_promo_items as $field_promo_item) {
          $promo = entity_load($field_promo_item['target_type'], array($field_promo_item['target_id']));
          if (empty($promo)) {
            continue;
          }
          $promo = reset($promo);
          switch ($field_promo_item['target_type']) {
            case 'node':
              $promo_data = _usanetwork_promo_pull_node_promo_details($promo);
              break;
            case 'file':
              $promo_data = _usanetwork_promo_pull_file_promo_details($promo);
              break;
          }
          if (empty($promo_data)) {
            continue;
          }
          if (!empty($promo->field_promo_image_override)) {
            $promo_image_url = _usanetwork_get_field_item($field_promo_item['target_type'], $promo, 'field_promo_image_override', 'uri');
          }
          else {
            $promo_image_url = usanetwork_core_api_get_content_image($field_promo_item['target_type'], $promo);
          }
          if (!empty($promo->field_promo_link)) {
            $promo_link = _usanetwork_get_field_item($field_promo_item['target_type'], $promo, 'field_promo_link', 'url');
          }
          else {
            $promo_link = url($field_promo_item['target_type'] . '/' . $field_promo_item['target_id']);
          }
          $episode_theme_variables = array(
            'url' => $promo_link,
            'promo_title' => $promo_data['promo_title'],
            'topic' => $promo_data['topic'],
            'image' => theme('image_style', array('style_name' => '390x390', 'path' => $promo_image_url)),
            'color_class' => $promo_data['show_class'],
            'icon_type' => $promo_data['icon_type'],
            'icon_text' => $promo_data['cta'],
            'show_name' => ($promo_data['show_name'] != $promo_data['topic']) ? $promo_data['show_name'] : '',
            'description' => $promo_data['description'],
            'cta' => !empty($promo_data['cta']) ? $promo_data['cta'] : '',
          );
          $theme_variables['promos'][] = $episode_theme_variables;
        }
        $theme_variables['promos'][count($theme_variables['promos']) -1 ]['class'] = 'last';
        $theme_variables['promos'][0]['class'] = 'first';
        return theme('usanetwork_social_carousel', $theme_variables);
      }
    }
  }
  return '';
}

/**
 * Returns content for usa_footer_promos block.
 */
function _usanetwork_blocks_usa_footer_promos_block_content() {
  if (arg(0) == 'admin') {
    return '';
  }

  $footer_promo_links = variable_get('usa_footer_promos_links', array());

  // Sort according weight.
  if (!empty($footer_promo_links)) {

    $column_index = 0;
    usort($footer_promo_links, function($a, $b) {
      if (!isset($a['weight'])) {
        $a['weight'] = 0;
      }
      if (!isset($b['weight'])) {
        $b['weight'] = 0;
      }

      if ($a['weight'] > $b['weight']) {
        return 1;
      }
      elseif ($a['weight'] < $b['weight']) {
        return -1;
      }

      return 0;
    });
    $theme_variables = array();
    foreach ($footer_promo_links as $footer_promo_link) {
      $image_file = NULL;

      if (!empty($footer_promo_link['image'])) {
        $image_file = file_load($footer_promo_link['image']);
      }

      $theme_variables['links'][] = array(
        'image_url' => !empty($image_file)
          ? image_style_url('usa_footer_promos_link_image', $image_file->uri)
          : NULL,
        'target_url' => !empty($footer_promo_link['url'])
          ? $footer_promo_link['url']
          : NULL,
        'title' => !empty($footer_promo_link['title'])
          ? $footer_promo_link['title']
          : NULL,
        'class' => !empty($footer_promo_link['class'])
          ? $footer_promo_link['class']
          : NULL,
        'target' => !empty($footer_promo_link['target'])
          ? $footer_promo_link['target']
          : '_tab',
        'column' => $column_index++,
      );
    }
    $theme_variables['columns'] = count($footer_promo_links);
    return theme('usa_footer_promos', $theme_variables);
  }
  return '';
}


/**
 * Returns an empty form element for adding a new footer promo link in usanetwork_blocks_form_usanetwork_settings_form_alter().
 */
function _usanetwork_blocks_usa_footer_links_get_empty_fieldset_item($i, $footer_promo_links) {
  $data = array(
    'link_' . $i => array(
      '#type' => 'fieldset',
      'usa_promo_links_link_' . $i . '_title' => array(
        '#type' => 'textfield',
        '#title' => t('Title'),
        '#required' => FALSE,
        '#default_value' => !empty($footer_promo_links[$i]['title'])
          ? $footer_promo_links[$i]['title']
          : '',
      ),
      'usa_promo_links_link_' . $i . '_url' => array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#required' => FALSE,
        '#default_value' => !empty($footer_promo_links[$i]['url'])
          ? $footer_promo_links[$i]['url']
          : '',
      ),
      'usa_promo_links_link_' . $i . '_target' => array(
        '#type' => 'select',
        '#title' => t('Target'),
        '#description' => t('Value of "target" attribute of link'),
        '#options' => array(
          '_tab' => t('New tab'),
          '_self' => t('Current window'),
        ),
        '#required' => FALSE,
        '#default_value' =>!empty($footer_promo_links[$i]['target'])
          ? $footer_promo_links[$i]['target']
          : '_tab',
      ),
      'usa_promo_links_link_' . $i . '_image' => array(
        '#type' => 'managed_file',
        '#title' => t('Image'),
        '#progress_message' => t('Please wait...'),
        '#progress_indicator' => 'bar',
        '#required' => FALSE,
        '#upload_validators' => array(
          'file_validate_extensions' => array(
            'jpeg jpg png gif'
          ),
        ),
        '#upload_location' => 'public://footer_promo_links/',
        '#default_value' => !empty($footer_promo_links[$i]['image'])
          ? $footer_promo_links[$i]['image']
          : NULL,
      ),
      'usa_promo_links_link_' . $i . '_class' => array(
        '#type' => 'textfield',
        '#title' => t('Classes'),
        '#description' => t('Enumerate classes that should be added to link'),
        '#required' => FALSE,
        '#default_value' => !empty($footer_promo_links[$i]['class'])
          ? $footer_promo_links[$i]['class']
          : '',
      ),
      'usa_promo_links_link_' . $i . '_weight' => array(
        '#type' => 'select',
        '#title' => t('Weight'),
        '#description' => t('Link with lesser number displays first'),
        '#options' => array(),
        '#required' => FALSE,
        '#default_value' => !empty($footer_promo_links[$i]['weight'])
          ? $footer_promo_links[$i]['weight']
          : 0,
      ),
    ),
  );

  for ($weight = -10; $weight <= 10; $weight++) {
    $data['link_' . $i]['usa_promo_links_link_' . $i . '_weight']['#options'][$weight] = $weight;
  }

  return $data;
}

/**
 * Increments the number of footer promo links in usanetwork_blocks_form_usanetwork_settings_form_alter().
 */
function ajax_usanetwork_blocks_usa_footer_links_add_more($form, &$form_state) {
  $form_state['links_number']++;
  $form_state['rebuild'] = TRUE;
}

/**
 * Decrements the number of footer promo links in usanetwork_blocks_form_usanetwork_settings_form_alter().
 */
function ajax_usanetwork_blocks_usa_footer_links_remove($form, &$form_state) {
  if ($form_state['links_number'] > 1) {
    $form_state['links_number']--;
  }
  $form_state['rebuild'] = TRUE;
}

/**
 * Footer promo links ajax-callback of usanetwork_blocks_form_usanetwork_settings_form_alter().
 */
function ajax_usanetwork_blocks_usa_footer_links_callback($form, $form_state) {
  return $form['footer']['promo_links'];
}
