<?php

/**
 * @file
 * Code for the usanetwork_blocks feature.
 */

include_once 'usanetwork_blocks.features.inc';

/**
 * @file
 * USA blocks - custom blocks that are not generated with views or stored elsewhere
 */


/**
 * Implements hook_block_info().
 */
function usanetwork_blocks_block_info() {
  $blocks = array();
  $blocks['fpo_ad_rectangle'] = array(
    'info' => t('FPO: rectangle ad block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['fpo_ad_skyscraper'] = array(
    'info' => t('FPO: skyscraper ad block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['fpo_ad_leaderboard'] = array(
    'info' => t('FPO: leaderboard ad block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['fpo_ad_pusher'] = array(
    'info' => t('FPO: pushdown 970x90 ad block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['fpo_block'] = array(
    'info' => t('FPO: generic block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['usa_meganav'] = array(
    'info' => t('USA: mega nav'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['usa_meganav_syndicate'] = array(
    'info' => t('USA: mega nav syndicate'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['usa_social_footer'] = array(
    'info' => t('USA: social footer (unused)'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['usa_tv_show_menu'] = array(
    'info' => t('USA: TV Show Menu'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['usa_footer_message'] = array(
    'info' => t('USA: Footer message'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['usa_footer_links'] = array(
    'info' => t('USA: Footer links'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['usa_detect_ieversion'] = array(
    'info' => t('USA: Detect ie version'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['usa_follow_block'] = array(
    'info' => t('USA: Follow us block'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_blocks_block_view($delta) {
  $block = array();
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'fpo_ad_rectangle':
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_fpo_ad_rectangle();
      break;
    case 'fpo_ad_skyscraper':
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_fpo_ad_skyscraper();
      break;
    case 'fpo_ad_leaderboard':
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_fpo_ad_leaderboard();
      break;
    case 'fpo_ad_pusher':
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_fpo_ad_pusher();
      break;
    case 'fpo_block':
      $block['subject'] = t('Generic block');
      $block['content'] = usanetwork_blocks_fpo_block();
      break;
    case 'usa_meganav':
      drupal_add_library('system', 'drupal.ajax');
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_usa_meganav();
      break;
    case 'usa_meganav_syndicate':
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_usa_meganav_syndicate();
      break;  
    case 'usa_social_footer':
      $block['subject'] = t('Follow Us:');
      $block['content'] = usanetwork_blocks_usa_social_footer();
      break;
    case 'usa_tv_show_menu':
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_tv_show_menu();
      break;
    case 'usa_footer_message':
      drupal_add_css(drupal_get_path("module", "usanetwork_blocks")."/theme/css/usanetwork_block.css");
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_usa_footer_message();
      break;
    case 'usa_footer_links':
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_usa_footer_links();
      break;
    case 'usa_detect_ieversion':
      drupal_add_css(drupal_get_path("module", "usanetwork_blocks")."/theme/css/usanetwork_block.css");
      drupal_add_js(drupal_get_path("module", "usanetwork_blocks")."/theme/js/usanetwork_block.js");
      $block['subject'] = '';
      $block['content'] = usanetwork_blocks_usa_detect_ieversion();
      break;
    case 'usa_follow_block':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => usanetwork_blocks_usa_follow_block(),
        '#attached' => array(
          'js' => array(
            drupal_get_path('module', 'usanetwork_blocks') . '/js/usanetwork_blocks_social.js'
          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function usanetwork_blocks_theme($existing, $type, $theme, $path) {
  // @TODO: add variables, make these real theme functions
  return array(
   'usa_meganav' => array(
      'variables' => array(
        ),
      'path' => $path . '/theme',
      'template' => 'usa-meganav',
    ),
   'usa_meganav_syndicate' => array(
      'variables' => array(
        ),
      'path' => $path . '/theme',
      'template' => 'usa-meganav-syndicate',
    ),
   'usa_social_footer' => array(
      'variables' => array(
        ),
      'path' => $path . '/theme',
      'template' => 'usa-social-footer',
    ),
   'usa_detect_ieversion' => array(
      'variables' => array(
        ),
      'path' => $path . '/theme',
      'template' => 'usa-detect-ieversion',
    ),
  );
}

/**
 * Block callback for the FPO rectangle ad block
 */
function usanetwork_blocks_fpo_ad_rectangle() {
  $render = array();

  $render['fpo_ad']['body'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="ad" style="width: 300px; height: 250px; text-align: center; background: #ddd;">',
    '#markup' => t('300x250 ad unit'),
    '#suffix' => '</div>',
  );

  return $render;
}

/**
 * Block callback for the FPO rectangle ad block
 */
function usanetwork_blocks_fpo_ad_skyscraper() {
  $render = array();

  $render['fpo_ad']['body'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="ad" style="width: 160px; height: 600px; text-align: center; background: #ddd;">',
    '#markup' => t('160x600 ad unit'),
    '#suffix' => '</div>',
  );

  return $render;
}


/**
 * Block callback for the FPO rectangle ad block
 */
function usanetwork_blocks_fpo_ad_leaderboard() {
  $render = array();

  $render['fpo_ad']['body'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="ad" style="width: 728px; height: 90px; text-align: center; background: #ddd;">',
    '#markup' => t('728x90 ad unit'),
    '#suffix' => '</div>',
  );

  return $render;
}

/**
 * Block callback for the FPO slider or super 970 x 90 ad block
 */
function usanetwork_blocks_fpo_ad_pusher() {
  $render = array();

  $render['fpo_ad']['body'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="ad" style="width: 970px; height: 90px; text-align: center; background: #ddd;">',
    '#markup' => t('728x90 ad unit'),
    '#suffix' => '</div>',
  );

  return $render;
}

/**
 * Block callback for the FPO generic block
 */
function usanetwork_blocks_fpo_block() {
  $render = array();

  $render['fpo_block']['body'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="body">',
    '#markup' => t('I am a generic placement only block. See me be that. :)'),
    '#suffix' => '</div>',
  );

  return $render;
}

/**
 * Block callback for the usa_meganav block
 */
function usanetwork_blocks_usa_meganav() {
  $render = array();

  $render['meganav'] = array(
    '#type' => 'markup',
    '#markup' => theme('usa_meganav', array()),
  );

  return $render;
}


/**
 * Block callback for the usa_meganav syndicate block
 */
function usanetwork_blocks_usa_meganav_syndicate() {
  $render = array();

  $render['meganav_syndicate'] = array(
    '#type' => 'markup',
    '#markup' => theme('usa_meganav_syndicate', array()),
  );

  return $render;
}

/**
 * Block callback for the usa_social_footer block
 */
function usanetwork_blocks_usa_social_footer() {
  $render = array();

  $render['socialfeet'] = array(
    '#type' => 'markup',
    '#markup' => theme('usa_social_footer', array()),
  );

  return $render;
}


/**
 * Block for displaying TV show menu
 */
function usanetwork_blocks_tv_show_menu() {
  $lang = LANGUAGE_NONE;
  $showlinks = array();
  $output = '';
  $show = '';
  $show_nid = '';
  $field_name = "field_show";
  $displaytitle = '';

  $show = _usanetwork_tv_show_menu_get_show();

  if ($show) {
    // if display title is populated load that as the menu title
    if (!empty($show->field_display_title)) {
      $displaytitle = field_get_items('node', $show, 'field_display_title');
      $displaytitle = $displaytitle[0]['safe_value'];
    }
    else {
      $displaytitle = $show->title;
    }

    // Get the field collection items.
    $fc_fields = field_get_items('node', $show, 'field_show_links');
    if (empty($fc_fields)) {
      return;
    }

    // Extract the field collection item ids
//    $ids = array();
    $items = array();
    foreach ($fc_fields as $fc_field) {
      $items[] = entity_revision_load('field_collection_item', $fc_field['revision_id']); //load current revision of collection
//      $ids[] = $fc_field['value'];
    }

    // Load up the field collection items
//    $items = field_collection_item_load_multiple($ids);
    if (empty($items)) {
      return;
    }

    // Loop through the items and extract field values
    foreach ($items as $item) {
      $mlinks = array();
      $link_fields = field_get_items('field_collection_item', $item, 'field_main_link');
      if (!empty($link_fields)) {
        foreach ($link_fields as $link) {
          $mlinks['data'] = empty($link['url']) ? l($link['title'], '', array('attributes' => array('class' => array('link-empty', 'parent-trigger')))) : l($link['title'], $link['url'], array('attributes' => array('class' => array('parent-trigger'))));
        }
      }

      $link_fields = field_get_items('field_collection_item', $item, 'field_child_link');
      if (!empty($link_fields)) {
        foreach ($link_fields as $link) {
          $mlinks['children'][] = empty($link['url']) ? l($link['title'], '', array('attributes' => array('class' => array('link-empty')))) : l($link['title'], $link['url']);
        }
      }
      $showlinks[] = $mlinks;
    }
    if (!empty($showlinks)) {
      $output .= '<div class="tv-show-menu-trigger">' . l($displaytitle, 'node/' . $show->nid, array('html' => true)) . '</div>';
      $output .= '<div id="tv-show-menu">' . theme('item_list', array('items' => $showlinks)) . '</div>';
    }
  }

  return $output;
}

/**
 * Block for Displaying Footer Message
 */
function usanetwork_blocks_usa_footer_message() {
  $render = array();
  $render['usa_footer']['body'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id ="footer-message">'. str_replace("YYYY", date("Y"), variable_get("usanetwork_footer_message", '')),
    '#suffix' => '</div>',
  );
  return $render;
}

/**
 * Block for Displaying Footer Links
 */
function usanetwork_blocks_usa_footer_links() {
  $render = menu_tree('usa-footer-bottom');

  $render['ad_chocies'] = array(
    '#type' => 'markup',
    '#prefix' => '<li id ="footer-links">'. variable_get("usanetwork_footer_ad_choices_text", ''),
    '#suffix' => '</li>',
  );
  return $render;
}


/**
 * Block callback for the usa_detect_ieversion
 */
function usanetwork_blocks_usa_detect_ieversion() {
  // add the cookie library so things to not explode
  drupal_add_library('system', 'jquery.cookie');
  $render = array();

  $render['ieversion_detection'] = array(
    '#type' => 'markup',
    '#markup' => theme('usa_detect_ieversion', array()),
  );

  return $render;
}

function usanetwork_blocks_usa_follow_block() {
  
  $fb_account = 'https://www.facebook.com/USANetwork';
  $tw_account = 'usa_network';
  
  $menu = menu_get_item();
  $entity_type = $menu['map'][0];
  $entity = menu_get_object($entity_type);

  if ($entity) {
    if ($entity->type == 'tv_show') {
      $fb_link = field_get_items($entity_type, $entity, 'field_usa_link_facebook');
      $fb_account = ($fb_link) ? $fb_link[0]['url'] : $fb_account;
      $tw_link = field_get_items($entity_type, $entity, 'field_usa_link_twitter');
      $tw_account = ($tw_link) ? $tw_link[0]['url'] : $tw_account;
    } else if (in_array($entity->type, array('catchall_page', 'media_gallery', 'person', 'tv_episode', 'usa_video', 'usa_tve_video', ))
            || (in_array($entity->type, _usanetwork_mpx_video_get_all_file_types()))) {
      $show = field_get_items($entity_type, $entity, 'field_show');
      if ($show) {
        $show_node = node_load($show[0]['target_id']);
        $fb_link = field_get_items('node', $show_node, 'field_usa_link_facebook');
        $fb_account = ($fb_link) ? $fb_link[0]['url'] : $fb_account;
        $tw_link = field_get_items('node', $show_node, 'field_usa_link_twitter');
        $tw_account = ($tw_link) ? $tw_link[0]['url'] : $tw_account;
      }
    }
  }
  
  drupal_add_js('!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");',
          'inline');
  
  $facebook_like = '<div class="social-dropdown">';
  $facebook_like .= '<iframe src="//www.facebook.com/plugins/likebox.php?href=' . $fb_account . '&width&height=62&colorscheme=light&show_faces=false&locale=en_US&header=true&stream=false&show_border=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:62px;" allowTransparency="true"></iframe>';
  $facebook_like .= '</div>';
  
  $output = '<div class="top-bar-social">';
  $output .= l($facebook_like, $fb_account,
    array('attributes' => array('class' => array('usa-facebook-share'), 'target' => '_blank'), 'html' => TRUE));
  
  $output .= '<a class="usa-twitter-share" url="https://twitter.com/intent/user?screen_name=@' . basename($tw_account).'"></a>';
  
  $output .= '</div>';
 
  return $output;
}
