<?php
/**
 * @file
 * Code for the usanetwork_aspot feature.
 */

include_once 'usanetwork_aspot.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function usanetwork_aspot_form_usanetwork_aspot_node_form_alter(&$form, &$form_state, $form_id) {
  $lang = $form['language']['#value'];
  $form['field_mp4_video_url']['#states'] = array(
    'visible' => array(
      ":input[name=\"field_animated_a_spot[$lang]\"]" => array('checked' => TRUE),
    ),
  );
  $form['field_webm_video_url']['#states'] = array(
    'visible' => array(
      ":input[name=\"field_animated_a_spot[$lang]\"]" => array('checked' => TRUE),
    ),
  );
  $form['#validate'][]= 'usanetwork_aspot_validate';
}

/**
 * Implements hook_validate().
 */
function usanetwork_aspot_validate(&$form, &$form_state) {
  $lang = $form['language']['#value'];
  if (isset($form_state['values']['field_animated_a_spot'][$lang][0]['value']) && $form_state['values']['field_animated_a_spot'][$lang][0]['value'] == 1) {
    if (isset($form_state['values']['field_mp4_video_url'][$lang][0]['value']) && $form_state['values']['field_mp4_video_url'][$lang][0]['value'] == '') {
      form_error($form['field_mp4_video_url'], t('MP4 Video URL is required field when "This is an Animated A-Spot" checked.'));
    }
    if (isset($form_state['values']['field_webm_video_url'][$lang][0]['value']) && $form_state['values']['field_webm_video_url'][$lang][0]['value'] == '') {
      form_error($form['field_webm_video_url'], t('Webm Video URL is required field when "This is an Animated A-Spot" checked.'));
    }
    if (isset($form_state['values']['field_mp4_video_url'][$lang][0]['value']) && !filter_var($form_state['values']['field_mp4_video_url'][$lang][0]['value'], FILTER_VALIDATE_URL)){
      form_error($form['field_mp4_video_url'], t('This is not a correct URL in MP4 Video URL field'));
    }
    if (isset($form_state['values']['field_webm_video_url'][$lang][0]['value']) && !filter_var($form_state['values']['field_webm_video_url'][$lang][0]['value'], FILTER_VALIDATE_URL)){
      form_error($form['field_webm_video_url'], t('This is not a correct URL in Webm Video URL field'));
    }
  }
}
/**
 * Implements hook_preprocess_node().
 */
function usanetwork_aspot_preprocess_node(&$vars) {
  if ($vars['type'] == 'usa_homepage'){
    $lang = $vars['language'];
    if (isset($vars['field_usa_hp_arefs'])){
      usanetwork_aspot_aspot_settings($vars['field_usa_hp_arefs'], $lang);
    }
  }
  if ($vars['type'] == 'tv_show'){
    $lang = $vars['language'];
    if (isset($vars['field_usa_tv_a_spot'][$lang])){
      usanetwork_aspot_aspot_settings($vars['field_usa_tv_a_spot'][$lang], $lang);
    }
  }
  if ($vars['type'] == 'usanetwork_aspot') {
    $current_path = current_path();
    if ($current_path == 'node/'.$vars['nid']) {
      $lang = $vars['language'];
      if ($vars['field_animated_a_spot'][$lang][0]['value']) {
        $vars['aspot_page'] = TRUE;
        $show = 'aspot';
        $mp4_url = $vars['field_mp4_video_url'][$lang][0]['value'];
        $webm_url = $vars['field_webm_video_url'][$lang][0]['value'];
        $aspot_settings = array(
          'show' => $show,
          'mp4_url' => $mp4_url,
          'webm_url' => $webm_url
        );
        drupal_add_js(array('aspotSettings' => $aspot_settings), 'setting');
      }
    }
  }
}

/**
 * Implements hook_block_info().
 */
function usanetwork_aspot_block_info() {
  $blocks = array();

  $blocks['usanetwork_aspot_carousel'] = array(
    'info' => t('ASpot: carousel'),
    'cache' => DRUPAL_NO_CACHE, // @TODO: change to cacheable
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_aspot_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'usanetwork_aspot_carousel':
      $block['subject'] = '';
      $block['content'] = _usanetwork_aspot_carousel_block();
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function usanetwork_aspot_theme() {
  return array(
    'usanetwork_aspot_carousel_slide' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_class' => NULL,
        'show_poster_url' => NULL,
        'show_title_prefix' => NULL,
        'show_title' => NULL,
        'show_timer' => array(
          'title_prefix' => NULL,
          'value' => '',
        ),
        'cta_buttons' => array(
          0 => array(
            'url' => NULL,
            'text' => NULL,
          ),
        ),
        'social_meter' => array(
          'value' => NULL,
          'multiplier' => NULL,
          'tag' => NULL,
          'hot' => NULL,
          'link' => array(
            'url' => NULL,
            'link' => NULL,
            'class' => NULL,
          ),
        ),
      ),
      'template' => 'templates/usanetwork-aspot-carousel-slide',
    ),
    'usanetwork_aspot_carousel' => array(
      'variables' => array(
        'slides' => array(),
      ),
      'template' => 'templates/usanetwork-aspot-carousel',
    ),
  );
}

function usanetwork_aspot_aspot_settings($aspot_array, $lang){
  foreach($aspot_array as $aspot){
    $node = node_load($aspot['target_id']);
    if ($node->field_animated_a_spot[$lang][0]['value']) {
      if(drupal_is_front_page()){
        $show = 'home';
      } else {
        $show = drupal_get_path_alias();
      }
      $mp4_url = $node->field_mp4_video_url[$lang][0]['value'];
      $webm_url = $node->field_webm_video_url[$lang][0]['value'];
      $aspot_settings = array(
        'show' => $show,
        'mp4_url' => $mp4_url,
        'webm_url' => $webm_url
      );
      drupal_add_js(array('aspotSettings' => $aspot_settings), 'setting');
      break(1);
    }
  }
}

function _usanetwork_aspot_carousel_block() {
  $carousel_nodes = _usanetwork_aspot_get_homepage_aspot_nodes();
  $output_array = array();

  if (!empty($carousel_nodes)) {
    foreach ($carousel_nodes as $carousel_node) {
      $theme_array = array(
        'show_url' => url('node/' . $carousel_node->nid),
        'show_class' => 'show-undefined',
        'show_poster_url' => 'http://placehold.it/666x444',
        'show_title_prefix' => t('HC title prefix'),
        'show_title' => $carousel_node->title,
      );

      // @TODO: Add logic for timer
      if (TRUE) {
        $theme_array['show_timer'] = array(
          'title_prefix' => t('Starts in'),
          'value' => 10000,
        );
      }

      // @TODO: Add logic for call to action buttons
      if (TRUE) {
        $theme_array['cta_buttons'] = array(
          0 => array(
            'url' => 'http://google.ru?q=How+does+cost+IS-6',
            'text' => t('Try with google!'),
          ),
        );
      }

      // @TODO: Add logic for social meter
      if (FALSE) {
        $theme_array['social_meter'] = array(
          'value' => NULL,
          'multiplier' => NULL,
          'tag' => NULL,
          'hot' => NULL,
          'link' => array(
            'url' => NULL,
            'link' => NULL,
            'class' => NULL,
          ),
        );
      }

      $output_array[] = theme('usanetwork_aspot_carousel_slide', $theme_array);
    }
  }

  if (!empty($output_array)) {
    return theme('usanetwork_aspot_carousel', array('slides' => $output_array));
  }

  return '';
}

function _usanetwork_aspot_get_homepage_aspot_nodes() {
  $homepage = usanetwork_home_get_homepage(array('usa_homepage'));

  if (!empty($homepage['node'])) {
    $homepage_nids = array_keys($homepage['node']);
    $homepage_node = node_load($homepage_nids[0]);
  }
}
