<?php
/**
 * @file
 * Code for the Usanetwork Pop-up Element feature.
 */

include_once 'usanetwork_popup.features.inc';

/**
 *  Implements hook_theme().
 */
function usanetwork_popup_theme($existing, $type, $theme, $path) {
  return array(
    'usanetwork_popup_window' => array(
      'variables' => array(
        'popup_image' => array(
          'desktop' => NULL,
          'mobile' => NULL,
          'mobile_retina' => NULL,
        ),
        'link' => array(
          'url' => NULL,
          'target' => NULL,
        ),
      ),
      'template' => 'templates/usanetwork-popup-window',
    ),
  );
}

function _usanetwork_popup_window() {
  if (arg(0) == 'admin') {
    return '';
  }

  $homepage = usanetwork_home_get_homepage();

  if (!empty($homepage['node'])) {
    $homepage_node = node_load(reset($homepage['node'])->nid);
  }

  $popup_element = _usanetwork_get_field_item('node', $homepage_node, 'field_popup_element', 'target_id');

  if (!empty($popup_element)) {
    $popup_node = node_load($popup_element);

    if ($popup_node->status == NODE_PUBLISHED) {
      drupal_add_js(drupal_get_path('module', 'usanetwork_popup') . '/js/usanetwork_popup.js');
      $popup_wrapper = entity_metadata_wrapper('node', $popup_node);
      if (!empty($popup_node->field_popup_desktop_image)) {
        $desktop = $popup_wrapper->field_popup_desktop_image->file->url->value();
      }
      if (!empty($popup_node->field_popup_mobile_image)) {
        $mobile_retina = $popup_wrapper->field_popup_mobile_image->file->url->value();
        $mobile_image = $popup_wrapper->field_popup_mobile_image->file->value();
        $mobile = image_style_url('313x451', $mobile_image->uri);
      }
      if (!empty($popup_node->field_promo_link)) {
        $link = $popup_wrapper->field_promo_link->url->value();
        $target_value = $popup_wrapper->field_promo_link->attributes->value();
        if (!empty($target_value)) {
          $target = $target_value['target'];
        }
      }

      if (!empty($popup_node->field_usa_css)) {
        $css = $popup_wrapper->field_usa_css->value();
        drupal_add_css($css, 'inline');
      }
      if (!empty($popup_node->field_usa_catchall_js)) {
        $js = $popup_wrapper->field_usa_catchall_js->value();
        drupal_add_js($js, array('type' => 'inline', 'scope' => 'footer'));
      }

      $theme_variables = array(
        'popup_image' => array(
          'desktop' => (!empty($desktop)) ? $desktop : NULL,
          'mobile' => (!empty($mobile)) ? $mobile : NULL,
          'mobile_retina' => (!empty($mobile_retina)) ? $mobile_retina : NULL,
        ),
        'link' => array(
          'url' => (!empty($link)) ? $link : NULL,
          'target' => (!empty($target)) ? $target : NULL,
        ),
        'popup_title' => $popup_node->title,
        'popup_id' => $popup_node->nid,
      );

      return theme('usanetwork_popup_window', $theme_variables);
    }
  }

  return '';
}

/**
 * Implements hook_page_alter().
 */
function usanetwork_popup_page_alter(&$page) {
  if (path_is_admin(current_path())) {
    // Prevent from adding extra js and css files for admin area.
    return;
  }
  if ("home" == current_path()) {
    // Attach hidden modal windows to the bottom of the page.
    $popup_window = _usanetwork_popup_window();
    $page['page_bottom']['usanetwork_popup_windows'] = array(
      '#markup' => $popup_window,
    );
  }
}

/**
 * Implements hook_image_default_styles().
 */
function usanetwork_popup_image_default_styles() {
  $styles = array();

  // Exported image style: 313x451.
  $styles['313x451'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 313,
          'height' => 451,
        ),
      ),
    ),
  );

  return $styles;
}
