<?php

/**
 * Implements hook_form_alter()
 */
function usanetwork_field_episodic_form_usanetwork_aspot_node_form_alter(&$form, &$form_state, $form_id) {
  $default_fields = array(
    'field_usa_text_color',
    'field_usa_aspot_txt1',
    'field_text_line_1_font_size',
    'field_text_line_1_image',
    'field_usa_aspot_txt2',
    'field_mobile_text_line_2',
    'field_text_line_2_font_size',
    'field_usa_aspot_txt3',
    'field_call_to_action_type',
    'field_usa_aspot_txt4',
  );
  
  $episodic_fields = array(
    'field_episodic_1_color',
    'field_episodic_1_title',
    'field_episodic_1_fontsize',
    'field_episodic_1_tablan_fontsize',
    'field_episodic_1_tabpor_fontsize',
    'field_episodic_1_mobile_fontsize',
    'field_episodic_1_image',
    'field_episodic_2_color',
    'field_episodic_2_title',
    'field_episodic_2_fontsize',
    'field_episodic_2_tablan_fontsize',
    'field_episodic_2_tabpor_fontsize',
    'field_episodic_2_mobile_fontsize',
    'field_episodic_3_color',
    'field_episodic_3_title',
    'field_episodic_3_fontsize',
    'field_episodic_3_tablan_fontsize',
    'field_episodic_3_tabpor_fontsize',
    'field_episodic_3_mobile_fontsize',
  );

  foreach ($default_fields as $default_field) {
    $form[$default_field]['#states'] =  array('invisible' => array(':input[name="field_is_episodic[und]"]' => array('checked' => TRUE)));
  }
  
  foreach ($episodic_fields as $episodic_field) {
    $form[$episodic_field]['#states'] =  array('visible' => array(':input[name="field_is_episodic[und]"]' => array('checked' => TRUE)));
  }
  
  $form['#attached']['css'][] = drupal_get_path('module', 'usanetwork_field_episodic') . '/css/usanetwork_field_episodic.css';
}
