<?php

/**
 * Implements hook_init().
 */
function usanetwork_tv_shows_color_init() {
  $show = _usanetwork_tv_show_menu_get_show();
  if ($show) {
    usanetwork_tv_shows_color_add_css($show);
  }
}

/*
 * Implements hook_usanetwork_widget_style().
 */
function usanetwork_tv_shows_color_usanetwork_widget_style($show) {
  usanetwork_tv_shows_color_add_css($show);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function usanetwork_tv_shows_color_field_widget_colorfield_unified_textfield_form_alter(&$element, &$form_state, $context) {
  // Attaches the library to the field based on the selected colorpicker.
  $settings = $context['instance']['widget']['settings'];
  if (isset($settings['colorfield_options']['colorfield_enable_colorpicker']) && $settings['colorfield_options']['colorfield_colorpicker_type'] == 'minicolors') {
    // Load jQuery minicolors if we can't, farbtastic will fallback.
    if (($library = libraries_load('jquery-miniColors')) && !empty($library['loaded'])) {
      $element['rgb']['#post_render'][] = 'usanetwork_tv_shows_color_field_attach_library';
      $element['#attached']['css'][] = drupal_get_path('module', 'usanetwork_tv_shows_color') . '/usanetwork_tv_show_color_admin.css';
    }
  }
}

/**
 * Callback to load library. Fixes library not loading on validation error.
 */
function usanetwork_tv_shows_color_field_attach_library($children, $elements) {
  libraries_load('jquery-miniColors');
  return $children;
}

/**
 * Adds show-specific css
 */
function usanetwork_tv_shows_color_add_css($show) {
  if (isset($show)) {
    if (file_exists('public://tv_show_color/tv_show_color_schema.css')) {
      drupal_add_css('public://tv_show_color/tv_show_color_schema.css', array('type' => 'file', 'group' => CSS_THEME));
    }
  }
}

/**
 * Implements hook_theme().
 */
function usanetwork_tv_shows_color_theme() {
  $module_path = drupal_get_path('module', 'usanetwork_tv_shows_color');
  return array(
    'usanetwork_tv_show_color_css' => array(
      'variables' => array(
        'node_code' => NULL,
        'primary_color_code' => NULL,
        'secondary_color_code' => NULL,
        'tertiary_color_code' => NULL,
      ),
      'path' => $module_path . '/theme',
      'template' => 'tv-show-color-css',
    ),
  );
}

/**
 * Implements hook_node_presave().
 */
function usanetwork_tv_shows_color_node_presave($node) {
  if (!isset($node->op) && $node->type == 'tv_show') {
    
    $node_code = field_get_items('node', $node, 'field_pathauto_alias');
    $primary_color_code = field_get_items('node', $node, 'field_usa_tv_show_color');
    $secondary_color_code = field_get_items('node', $node, 'field_usa_tv_show_color_second');
    $tertiary_color_code = field_get_items('node', $node, 'field_usa_tv_show_color_tertiary');

    if (!$node_code ||
        !$primary_color_code ||
        !$secondary_color_code ||
        !$tertiary_color_code) {
      return;
    }
    else {
      $node_code = reset($node_code);
      $primary_color_code = reset($primary_color_code);
      $secondary_color_code = reset($secondary_color_code);
      $tertiary_color_code = reset($tertiary_color_code);
    }

    $node_css = theme('usanetwork_tv_show_color_css', array(
      'node_code' => $node_code['value'],
      'primary_color_code' => $primary_color_code['rgb'],
      'secondary_color_code' => $secondary_color_code['rgb'],
      'tertiary_color_code' => $tertiary_color_code['rgb'],
    ));
    $tv_show_css_dir = 'public://tv_show_color/nodes';
    $tv_show_css = 'public://tv_show_color/tv_show_color_schema.css';
    if (file_prepare_directory($tv_show_css_dir, FILE_CREATE_DIRECTORY)) {
      $saved = file_unmanaged_save_data($node_css, $tv_show_css_dir . '/' . $node_code['value'] . '_' . $node->nid . '.css', FILE_EXISTS_REPLACE);
      if ($saved) {
        $files = file_scan_directory($tv_show_css_dir, '/\.css/');
        $css = '';
        foreach ($files as $file) {
          $css .= file_get_contents($file->uri);
        }
        file_unmanaged_save_data($css, $tv_show_css, FILE_EXISTS_REPLACE);
      }
    }
  }
}

/**
 * Return css class for show
 */
function usanetwork_tv_shows_color_show_css_class($show_node) {
  if (!is_object($show_node)) {
    $show_node = node_load($show_node);
  }
  
  $node_alias = reset(field_get_items('node', $show_node, 'field_pathauto_alias'));
  if ($node_alias) {
    $show_css_class = 'show-' . $node_alias['value'];
  } else {
    $show_css_class = drupal_clean_css_identifier($show_node->title);
  }
  
  return $show_css_class;
}
