<?php
/**
 * @file
 * The domains and their corresponding ACS ids need to be communicated to the
 * IDM/SSO team.
 */

//$domains = array(
//  'local.usanetwork.com' => 'usa-local',
//  'dev-beta.usanetwork.com' => 'usa-devbeta',
//  'dev.usanetwork.com' => 'usa-dev',
//  'stage-beta.usanetwork.com' => 'usa-stagebeta',
//  'stage.usanetwork.com' => 'usa-stage',
//  'qa-beta.usanetwork.com' => 'usa-qabeta',
//  'qa.usanetwork.com' => 'usa-qa',
//  'origin-beta.usanetwork.com' => 'usa-originbeta',
//  'origin-www.usanetwork.com' => 'usa-origin',
//  'usanetwork.com' => 'usa-prod',
//  'www.usanetwork.com' => 'usa-www',
//);
$main_domain = array (
  'usanetwork.com' => 'usanetwork',
);