<?php
/**
 * @file
 * usanetwork_consumptionator_post.features.metatag.inc
 */

/**
 * Implements hook_metatag_export_default().
 */
function usanetwork_consumptionator_post_metatag_export_default() {
  $config = array();

  // Exported Metatag config instance: node:consumpt_post.
  $config['node:consumpt_post'] = array(
    'instance' => 'node:consumpt_post',
    'config' => array(
      'robots' => array(
        'value' => array(
          'index' => 0,
          'follow' => 0,
          'noindex' => 0,
          'nofollow' => 0,
          'noarchive' => 0,
          'nosnippet' => 0,
          'noodp' => 0,
          'noydir' => 0,
          'noimageindex' => 0,
          'notranslate' => 0,
        ),
      ),
      'og:description' => array(
        'value' => '[node:field_usa_og_description]',
      ),
      'og:image' => array(
        'value' => '[node:field_usa_og_image]',
      ),
    ),
  );

  return $config;
}
