<?php
/**
 * @file
 * Code for the usanetwork_person feature.
 */

include_once 'usanetwork_person.features.inc';


/**
 * Implements hook_preprocess_HOOK().
 */
function usanetwork_person_preprocess_page(&$vars) {
  // Load node, hide title on the frontend
  $node = menu_get_object();
  if ($node && $node->type == 'person') {
    $vars['title'] = '';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function usanetwork_person_form_person_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_person').'/js/usanetwork_person.js';
}
