<?php
/**
 * @file
 * Code for the Usanetwork News feature.
 */

/**
 * Implementation of hook_menu().
 */
function usanetwork_news_menu() {

  $items['news'] = array(
    'title' => t('Latest on USA'),
    'page callback' => 'usanetwork_news_landing_post',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Global News Page
 */
function usanetwork_news_landing_post() {
  $page = pager_find_page();
  $num_per_page = 20;

  $cache_name = 'blog_global_page_' . $page;
  $cache_name_count = 'blog_global_page_count';
  $cache = cache_get($cache_name);
  $cache_count = cache_get($cache_name_count);

  if (empty($cache)) {
    $offset = $num_per_page * $page;
    $query = db_select('node', 'cp');
    $query->fields('cp', array('nid', 'title'));
    $query->leftJoin('field_data_body', 'body_field', 'body_field.entity_id=cp.nid');
    $query->addField('body_field', 'body_value', 'body');
    $query->leftJoin('field_data_field_summary', 'field_summary', 'field_summary.entity_id=cp.nid');
    $query->addField('field_summary', 'field_summary_value', 'summary');
    $query->leftJoin('field_data_field_post_cover', 'post_cover', 'post_cover.entity_id=cp.nid');
    $query->addField('post_cover', 'field_post_cover_fid', 'post_cover_fid');
    $query->leftJoin('field_data_field_promo_created_ovts', 'post_covts', 'post_covts.entity_id=cp.nid');
    $query->addField('post_covts', 'field_promo_created_ovts_value', 'created');
    $query->condition('cp.type', 'consumpt_post');
    $query->condition('cp.status', NODE_PUBLISHED);
    $query->orderBy('post_covts.field_promo_created_ovts_value', 'DESC');

    $clone_db_query = clone $query;
    $count_query = $clone_db_query->countQuery();
    $result_count = $count_query->execute()->fetchField();

    $query->range($offset, $num_per_page);
    $result = $query->execute()->fetchAll();

    if ($result) {
      foreach ($result as &$result_item) {
        $result_item->description = _usanetwork_consumptionator_post_get_season_episodes_description($result_item);
      }
    }
    cache_set($cache_name, $result, 'cache', time() + 900);
    cache_set($cache_name_count, $result_count, 'cache', time() + 900);
  }
  else {
    $result = $cache->data;
    $result_count = $cache_count->data;
  }

  $posts_data = $result;

  $theme_variables = array(
    'news_page' => TRUE,
  );

  if (!empty($posts_data)) {
    pager_default_initialize($result_count, $num_per_page);
    foreach ($posts_data as $post_data_index => $post_data) {
      $cover_file = entity_load('file', array($post_data->post_cover_fid));
      if (!empty($cover_file)) {
        $cover_file = reset($cover_file);
        $cover_uri = $cover_file->uri;
      }
      $theme_item_variables = array(
        'blog_url' => isset($post_data->nid)
          ? url('node/' . $post_data->nid)
          : NULL,
        'desktop_image_url' => image_style_url('677x381', $cover_uri),
        'title' => $post_data->title,
        'description' => check_markup($post_data->description, 'wysiwyg_mini'),
        'post_date' => !empty($post_data->created)
          ? gmdate('m/d/Y', $post_data->created)
          : NULL,
      );
      $theme_variables['items'][] = theme('usanetwork_blog_landing_posts_list_item', $theme_item_variables);
    }
  }

  return !empty($theme_variables['items'])
    ? theme('usanetwork_blog_landing_posts', $theme_variables) . theme('pager')
    : '';
}
