<?php
/**
 * @file
 * Code for the USA Network Chartbeat Tracking.
 */

/**
 * Implements hook_page_alter().
 */
function usanetwork_chartbeat_page_alter(&$page) {
  if (!path_is_admin(current_path())) {

    drupal_add_js('var _sf_startpt=(new Date()).getTime()', 'inline');
    drupal_add_js(array('chartbeat_domain' => $_SERVER['SERVER_NAME']),'setting');

    $page['page_bottom']['chartbeat']['#attached']['js'][drupal_get_path('module', 'usanetwork_chartbeat') . '/js/usanetwork_chartbeat.js'] =  array(
      'type' => 'file',
      'scope' => 'footer',
    );
  }
}
