<?php
if (!defined('USA_PREFIX')) define('USA_PREFIX', '<h2>');
if (!defined('USA_SUFFIX')) define('USA_SUFFIX', '</h2>');
function usa_print($msg) {
  return USA_PREFIX . $msg . USA_SUFFIX;
}

include 'usanetwork_microsite.admin.inc';

/**
 * Implements hook_menu().
 */
function usanetwork_microsite_menu() {
//echo usa_print('usanetwork_microsite_menu');
  $items = array();
/*
  $items['node/%/#section=%/%'] = array(
    'title' => 'Microsite Page',
    'page callback' => 'usanetwork_dig_show_page_process',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
*/
// @TODO: SET THE FOLLOWING SO IT DOESN'T LOOK AT EVERY NODE!!!
//  $items['node/%'] = array(
  $items['node/54204'] = array(
    'title' => 'Dig',
    'page callback' => 'usanetwork_dig_show_page',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_preprocess_node()
 */
/*
function _usanetwork_aspot_preprocess_node($nid) {
  $vars = (array)node_load($nid);
//dpm($vars);
  if ($vars['type'] == 'usa_homepage'){
    $lang = $vars['language'];
    if (isset($vars['field_usa_hp_arefs'])){
      usanetwork_aspot_aspot_settings($vars['field_usa_hp_arefs'], $lang);
    }
  }
  if ($vars['type'] == 'tv_show'){
    $lang = $vars['language'];
    if (isset($vars['field_usa_tv_a_spot'][$lang])){
      usanetwork_aspot_aspot_settings($vars['field_usa_tv_a_spot'][$lang], $lang);
    }
  }
  if ($vars['type'] == 'usanetwork_aspot') {
    $current_path = current_path();
//    if ($current_path == 'node/'.$vars['nid']) {
      $lang = $vars['language'];
      if ($vars['field_animated_a_spot'][$lang][0]['value']) {
        $vars['aspot_page'] = TRUE;
        $show = 'aspot';
        $mp4_url = $vars['field_mp4_video_url'][$lang][0]['value'];
        $webm_url = $vars['field_webm_video_url'][$lang][0]['value'];
        $aspot_settings = array(
          'show' => $show,
          'mp4_url' => $mp4_url,
          'webm_url' => $webm_url
        );
        drupal_add_js(array('aspotSettings' => $aspot_settings), 'setting');
      }
//    }
  }
}
*/

function _usanetwork_microsite_get_info($nid) {
//echo USA_PREFIX . '_usanetwork_microsite_get_info()' . USA_SUFFIX;
  $params = array();
  $node = node_load($nid);
  if ($node->type == 'usanetwork_microsite') {
//dpm($vars);
//dpm($node);

    // set variables
    $lang = (!empty($node->language)) ? $node->language : 'und';
    $params['lang'] = $lang;
    $params['show'] = (!empty($node->field_show[$lang][0]['target_id'])) ? $node->field_show[$lang][0]['target_id'] : '';
    $params['theme'] = (!empty($node->field_ms_theme[$lang][0]['value'])) ? $node->field_ms_theme[$lang][0]['value'] : '';
    $params['profile_image'] = (!empty($node->field_ms_small_logo[$lang][0]['filename'])) ? $node->field_ms_small_logo[$lang][0]['filename'] : '';
    $params['tune_in'] = (!empty($node->field_ms_tune_in[$lang][0]['value'])) ? $node->field_ms_tune_in[$lang][0]['value'] : '';
    $params['section_separator'] = (!empty($node->field_ms_section_separator[$lang][0]['value'])) ? $node->field_ms_section_separator[$lang][0]['value'] : '';
    $section = array();
    foreach($node->field_ms_section[$lang] as $key => $array) {
      $s_node_id = $node->field_ms_section[$lang][$key]['value'];
      $s_node = entity_load('field_collection_item', array($s_node_id));
//dpm($s_node_id);
//dpm($s_node);
      $section = array();
      $section['section_enabled'] = $s_node[$s_node_id]->field_ms_section_enabled[$lang][0]['value'];
      if ($section['section_enabled']) {
        $section['title'] = (!empty($s_node[$s_node_id]->field_ms_section_title[$lang][0]['value'])) ? $s_node[$s_node_id]->field_ms_section_title[$lang][0]['value'] : '';
        $section['bg_image'] = (!empty($s_node[$s_node_id]->field_ms_section_bg_image[$lang][0]['filename'])) ? $s_node[$s_node_id]->field_ms_section_bg_image[$lang][0]['filename'] : '';
        $section['type'] = (!empty($s_node[$s_node_id]->field_ms_section_type[$lang][0]['value'])) ? $s_node[$s_node_id]->field_ms_section_type[$lang][0]['value'] : '';

        // aspots
        $aspots = array();
        foreach($s_node[$s_node_id]->field_usa_hp_arefs[$lang] as $key2 => $array2) {
//          if ($array2['state_flow']->current == 'published') {
            $aspot_node_id = $s_node[$s_node_id]->field_usa_hp_arefs[$lang][$key2]['target_id'];
            $aspots[] = (array)node_load($aspot_node_id);
            // add aspot info to javascript
            //_usanetwork_aspot_preprocess_node($aspot_node_id);
//          }
        }
        $section['aspot'] = $aspots;

        // bspot -- there should be only 1
        $section['bspot'] = (!empty($s_node[$s_node_id]->field_usa_hp_brefs[$lang][0]['target_id'])) ? (array)node_load($s_node[$s_node_id]->field_usa_hp_brefs[$lang][0]['target_id']) : '';

        // cspot -- there should be only 1
        $section['cspot'] = (!empty($s_node[$s_node_id]->field_usa_hp_crefs[$lang][0]['target_id'])) ? (array)node_load($s_node[$s_node_id]->field_usa_hp_crefs[$lang][0]['target_id']) : '';

        // media gallery
        $section['media_gallery'] = (!empty($s_node[$s_node_id]->field_media_gallery[$lang][0]['target_id'])) ? (array)node_load($s_node[$s_node_id]->field_media_gallery[$lang][0]['target_id']) : '';

        // about description
        $section['description'] = (!empty($s_node[$s_node_id]->field_ms_section_text[$lang][0]['value'])) ? $s_node[$s_node_id]->field_ms_section_text[$lang][0]['value'] : '';

        // people
        $section['person'] = (!empty($s_node[$s_node_id]->field_person[$lang][0]['target_id'])) ? (array)node_load($s_node[$s_node_id]->field_person[$lang][0]['target_id']) : '';
        $section['character'] = (!empty($s_node[$s_node_id]->field_episode_credit_character[$lang][0]['target_id'])) ? (array)node_load($s_node[$s_node_id]->field_episode_credit_character[$lang][0]['target_id']) : '';

        // carousels
        $section['promo_carousel'] = (!empty($s_node[$s_node_id]->field_hp_promo_carousel[$lang][0]['target_id'])) ? $s_node[$s_node_id]->field_hp_promo_carousel[$lang][0]['target_id'] : '';

        // promo
        $section['featured_promo'] = (!empty($s_node[$s_node_id]->field_hp_promos[$lang][0]['target_id'])) ? $s_node[$s_node_id]->field_hp_promos[$lang][0]['target_id'] : '';


        // catch all
        $catchalls = array();
        foreach($s_node[$s_node_id]->field_ms_catchall_page[$lang] as $key3 => $array3) {
//          if ($array3['state_flow']->current == 'published') {
            $catchall_node_id = $s_node[$s_node_id]->field_ms_catchall_page[$lang][$key3]['target_id'];
            $catchalls[] = (array)node_load($catchall_node_id);
//          }
        }
        $section['catchalls'] = $catchalls;
        $section['featured_promo'] = (!empty($s_node[$s_node_id]->field_hp_promos[$lang][0]['target_id'])) ? $s_node[$s_node_id]->field_hp_promos[$lang][0]['target_id'] : '';
      }
      $params['section'][$key] = $section;
    }
    // set paths
    $params['theme_path'] = drupal_get_path('theme', 'aurora_usa') . '/usanetwork_microsite_themes/' . $params['theme'];
//dpm($params);
    usanetwork_dig_show_page($params);
  }

  return $params;
}

/**
 * usanetwork_dig_show_page
 * Sets $params array containing all content
 */
//function usanetwork_dig_show_page($nid) {
function usanetwork_dig_show_page($nid) {
  //if (!path_is_admin(current_path())) {
    $params = _usanetwork_microsite_get_info($nid);

    if (count($params) > 0) {
      // add css
      drupal_add_css(drupal_get_path('theme', 'aurora_usa') . '/usanetwork_microsite_themes/dig/css/ms_style.css');
      drupal_add_css(drupal_get_path('theme', 'aurora_usa') . '/usanetwork_microsite_themes/dig/css/trivia.css');

      // add js
      drupal_add_js(drupal_get_path('module', 'usanetwork_microsite') . '/js/jquery.easing.1.3.js');
      drupal_add_js(drupal_get_path('module', 'usanetwork_microsite') . '/js/jquery.easing.compatibility.js');
      drupal_add_js(drupal_get_path('module', 'usanetwork_microsite') . '/js/microsite_global.js');
      //drupal_add_js(drupal_get_path('theme', 'aurora_usa') . '/javascripts/show-flexslider.js');

      return theme('usanetwork_dig_show_page', $params);
    }
    else {
      // do nothing here
      // for some reason this function is being called more than once!!
      //echo('params not set yet');
    }
  //}
}


/**
 * Implements hook_theme().
 */
function usanetwork_microsite_theme() {
usa_print('usanetwork_microsite_theme');
  $theme_path = drupal_get_path('theme', 'aurora_usa');
// @TODO: FIND A WAY TO PASS $params['theme'] TO THE FILE TEMPLATE PATH
  $themes = array(
    'usanetwork_dig_show_page' => array(
      'template' => 'usanetwork_microsite',
      'path' => $theme_path . '/usanetwork_microsite_themes/dig/templates',
    ),
  );
  return $themes;
}

/**
 * Implements hook_permission
 */
function usanetwork_microsite_permission() {
  $perm = array(
    'view microsites' => array(
      'title' => t('View microsites'),
    ),
    'create microsites' => array(
      'title' => t('Create microsites'),
    ),
    'manage microsites' => array(
      'title' => t('Manage microsites'),
    )
  );
  return $perm;
}
