<?php

/**
 * Implementation of hook_menu().
 */
function usanetwork_social_menu() {
  // admin pages
  $items['admin/usanetwork/social-settings'] = array(
    'title' => t('Social Settings'),
    'description' => t('Administer USA Network social settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('usanetwork_social_settings_form'),
    'access arguments' => array('administer usanetwork'),
    'file' =>  'usanetwork_social.admin.inc',
    'weight' => -10,
  );
 
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function usanetwork_social_form_node_form_alter(&$form, &$form_state) {
  $lang = LANGUAGE_NONE;

  if ($form['type']['#value'] == 'tv_show') {

    // set the sitewide values as default values for each show
    if (!isset($form['field_twitter_eql_template'][$lang][0]['value']['#default_value']) ||
      empty($form['field_twitter_eql_template'][$lang][0]['value']['#default_value'])) {
      $form['field_twitter_eql_template'][$lang][0]['value']['#default_value'] = variable_get('usanetwork_social_twitter_echo_query_template', '');
    }
    if (!isset($form['field_twitter_childrenof'][$lang][0]['value']['#default_value']) ||
      empty($form['field_twitter_childrenof'][$lang][0]['value']['#default_value'])) {
      $form['field_twitter_childrenof'][$lang][0]['value']['#default_value'] = variable_get('usanetwork_social_twitter_childrenof', '');
    }
  }
}
