<?php
/**
 * @file
 * Code for the usanetwork_aspot feature.
 */

include_once 'usanetwork_aspot.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function usanetwork_aspot_form_usanetwork_aspot_node_form_alter(&$form, &$form_state, $form_id) {
  $lang = $form['language']['#value'];
  $form['field_mp4_video_url']['#states'] = array(
    'visible' => array(
      ":input[name=\"field_animated_a_spot[$lang]\"]" => array('checked' => TRUE),
    ),
  );
  $form['field_webm_video_url']['#states'] = array(
    'visible' => array(
      ":input[name=\"field_animated_a_spot[$lang]\"]" => array('checked' => TRUE),
    ),
  );
  $form['#validate'][]= 'usanetwork_aspot_validate';
}

/**
 * Implements hook_validate().
 */
function usanetwork_aspot_validate(&$form, &$form_state) {
  $lang = $form['language']['#value'];
  if (isset($form_state['values']['field_animated_a_spot'][$lang][0]['value']) && $form_state['values']['field_animated_a_spot'][$lang][0]['value'] == 1) {
    if (isset($form_state['values']['field_mp4_video_url'][$lang][0]['value']) && $form_state['values']['field_mp4_video_url'][$lang][0]['value'] == '') {
      form_error($form['field_mp4_video_url'], t('MP4 Video URL is required field when "This is an Animated A-Spot" checked.'));
    }
    if (isset($form_state['values']['field_webm_video_url'][$lang][0]['value']) && $form_state['values']['field_webm_video_url'][$lang][0]['value'] == '') {
      form_error($form['field_webm_video_url'], t('Webm Video URL is required field when "This is an Animated A-Spot" checked.'));
    }
    if (isset($form_state['values']['field_mp4_video_url'][$lang][0]['value']) && !filter_var($form_state['values']['field_mp4_video_url'][$lang][0]['value'], FILTER_VALIDATE_URL)){
      form_error($form['field_mp4_video_url'], t('This is not a correct URL in MP4 Video URL field'));
    }
    if (isset($form_state['values']['field_webm_video_url'][$lang][0]['value']) && !filter_var($form_state['values']['field_webm_video_url'][$lang][0]['value'], FILTER_VALIDATE_URL)){
      form_error($form['field_webm_video_url'], t('This is not a correct URL in Webm Video URL field'));
    }
  }
}
/**
 * Implements hook_preprocess_node().
 */
function usanetwork_aspot_preprocess_node(&$vars) {
  if ($vars['type'] == 'usa_homepage'){
    $lang = $vars['language'];
    if (isset($vars['field_usa_hp_arefs'])){
      usanetwork_aspot_aspot_settings($vars['field_usa_hp_arefs'], $lang);
    }
  }
  if ($vars['type'] == 'tv_show'){
    $lang = $vars['language'];
    if (isset($vars['field_usa_tv_a_spot'][$lang])){
      usanetwork_aspot_aspot_settings($vars['field_usa_tv_a_spot'][$lang], $lang);
    }
  }
  if ($vars['type'] == 'usanetwork_aspot') {
    $current_path = current_path();
    if ($current_path == 'node/'.$vars['nid']) {
      $lang = $vars['language'];
      if ($vars['field_animated_a_spot'][$lang][0]['value']) {
        $vars['aspot_page'] = TRUE;
        $show = 'aspot';
        $mp4_url = $vars['field_mp4_video_url'][$lang][0]['value'];
        $webm_url = $vars['field_webm_video_url'][$lang][0]['value'];
        $aspot_settings = array(
          'show' => $show,
          'mp4_url' => $mp4_url,
          'webm_url' => $webm_url
        );
        drupal_add_js(array('aspotSettings' => $aspot_settings), 'setting');
      }
    }
  }
}

function usanetwork_aspot_aspot_settings($aspot_array, $lang){
  foreach($aspot_array as $aspot){
    $node = node_load($aspot['target_id']);
    if ($node->field_animated_a_spot[$lang][0]['value']) {
      if(drupal_is_front_page()){
        $show = 'home';
      } else {
        $show = drupal_get_path_alias();
      }
      $mp4_url = $node->field_mp4_video_url[$lang][0]['value'];
      $webm_url = $node->field_webm_video_url[$lang][0]['value'];
      $aspot_settings = array(
        'show' => $show,
        'mp4_url' => $mp4_url,
        'webm_url' => $webm_url
      );
      drupal_add_js(array('aspotSettings' => $aspot_settings), 'setting');
      break(1);
    }
  }
}
