<?php

/**
 * Implements hook_menu().
 */
function usanetwork_node_copy_menu() {
  $items['admin/usanetwork/copy_settings'] = array(
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('copy_settings_form'),
    'title' => 'Node copy settings',
    'file' => 'usanetwork_node_copy.admin.inc',
  );
  $items['node/%node/copy'] = array(
    'page callback' => 'usanetwork_node_copy',
    'page arguments' => array(1),
    'access arguments' => array('access administration pages'),
    'title' => 'Copy content',
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Is node type can be copied
 */
function usanetwork_node_copy_is_copy($type){
  $copied = variable_get('usanetwork_node_type_copy', array('usanetwork_aspot' => 'usanetwork_aspot', 'usanetwork_promo' => 'usanetwork_promo'));
  return isset($copied[$type]) ? $copied[$type] : false;
}

/**
 * Menu callback: Copy node
 */
function usanetwork_node_copy($original_node) {
  if (isset($original_node->nid)) {
    global $user;

    if (usanetwork_node_copy_is_copy($original_node->type)) {
      $node = clone $original_node;

      $node->nid = NULL;
      $node->vid = NULL;
      $node->tnid = NULL;
      $node->name = isset($user->name) ? $user->name : NULL;
      $node->uid = $user->uid;
      $node->created = NULL;
      $node->menu = NULL;
      $node->path = NULL;
      $node->files = array();
      
      $db_select = db_select('node', 'n')
          ->condition('n.title', '%' . db_like($node->title) . '%', 'like')
          ->countQuery()
          ->execute()->fetchField(); 
      $node->title = t('!title !number', array('!title' => $node->title, '!number' => ($db_select + 1)));
      drupal_set_title($node->title);

      $node->current_state = 'draft';
      $node->state_flow->current = 'draft';
      
      $form_state = array();
      $form_state['build_info']['args'] = array($node);
      form_load_include($form_state, 'inc', 'node', 'node.pages');
      return drupal_build_form($node->type .'_node_form', $form_state);
    }
  }
}

/**
 * Implementation of hook_admin_paths().
 */
function usanetwork_node_copy_admin_paths() {
  if (variable_get('node_admin_theme')) {
    $paths = array(
      'node/*/copy' => TRUE,
    );
    return $paths;
  }
}

/**
 * Implements hook_views_api.
 */
function usanetwork_node_copy_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'usanetwork_node_copy') .'/views',
  );
}
