<?php
if (!defined('USA_PREFIX')) define('USA_PREFIX', '<h2>');
if (!defined('USA_SUFFIX')) define('USA_SUFFIX', '</h2>');
function usa_print($msg) {
  return USA_PREFIX . $msg . USA_SUFFIX;
}

/**
 * Implements hook_menu().
 */
function usanetwork_show_microsite_menu() {
//echo usa_print('usanetwork_show_microsite_menu');
  $items = array();
  $items['node/%'] = array(
    'title' => 'Microsite Page',
    'page callback' => 'usanetwork_dig_show_page',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_preprocess_node().
 */
/*
function _usanetwork_aspot_preprocess_node($nid) {
  $vars = (array)node_load($nid);
  if ($vars['type'] == 'usa_homepage'){
    $lang = $vars['language'];
    if (isset($vars['field_usa_hp_arefs'])){
      usanetwork_aspot_aspot_settings($vars['field_usa_hp_arefs'], $lang);
    }
  }
  if ($vars['type'] == 'tv_show'){
    $lang = $vars['language'];
    if (isset($vars['field_usa_tv_a_spot'][$lang])){
      usanetwork_aspot_aspot_settings($vars['field_usa_tv_a_spot'][$lang], $lang);
    }
  }
  if ($vars['type'] == 'usanetwork_aspot') {
    $current_path = current_path();
    if ($current_path == 'node/'.$vars['nid']) {
      $lang = $vars['language'];
      if ($vars['field_animated_a_spot'][$lang][0]['value']) {
        $vars['aspot_page'] = TRUE;
        $show = 'aspot';
        $mp4_url = $vars['field_mp4_video_url'][$lang][0]['value'];
        $webm_url = $vars['field_webm_video_url'][$lang][0]['value'];
        $aspot_settings = array(
          'show' => $show,
          'mp4_url' => $mp4_url,
          'webm_url' => $webm_url
        );
        drupal_add_js(array('aspotSettings' => $aspot_settings), 'setting');
      }
    }
  }
}
*/

/**
 * usanetwork_dig_show_page
 * Sets $params array containing all content
 */
function usanetwork_dig_show_page($nid) {
//echo usa_print('usanetwork_dig_show_page(' . $nid . ')');
  $params = array();
  $node = node_load($nid);
//dpm($node);
  if ($node->type == 'show_microsite') {
//echo PRE_ECHO_TAG . 'usanetwork_show_microsite_node_view' . POST_ECHO_TAG;

    // set variables
    $lang = (!empty($node->language)) ? $node->language : 'und';
    $params['section_enabled'] = $node->field_ms_section_enable[$lang][0]['value'];
    $params['theme'] = (!empty($node->field_theme[$lang][0]['value'])) ? $node->field_theme[$lang][0]['value'] : '';
    $params['show'] = (!empty($node->field_show[$lang][0]['target_id'])) ? $node->field_show[$lang][0]['target_id'] : '';
    $params['section_separator'] = (!empty($node->field_ms_section_separator[$lang][0]['value'])) ? $node->field_ms_section_separator[$lang][0]['value'] : '';
    $params['profile_image'] = (!empty($node->field_profile_image[$lang][0]['filename'])) ? $node->field_profile_image[$lang][0]['filename'] : '';
    $params['tune_in'] = (!empty($node->field_ms_tunein[$lang][0]['value'])) ? $node->field_ms_tunein[$lang][0]['value'] : '';
    if ($params['section_enabled']) {
      $params['aspots'] = (!empty($node->field_usa_hp_arefs[$lang][0]['target_id'])) ? $node->field_usa_hp_arefs[$lang][0]['target_id'] : '';
      // add aspot info to javascript
      //_usanetwork_aspot_preprocess_node($params['aspots']);
      $params['bspot'] = (!empty($node->field_usa_hp_brefs[$lang][0]['target_id'])) ? $node->field_usa_hp_brefs[$lang][0]['target_id'] : '';
      $params['cspot'] = (!empty($node->field_usa_hp_crefs[$lang][0]['target_id'])) ? $node->field_usa_hp_crefs[$lang][0]['target_id'] : '';
      $params['media_gallery'] = (!empty($node->field_media_gallery[$lang][0]['target_id'])) ? $node->field_media_gallery[$lang][0]['target_id'] : '';
      $params['person'] = (!empty($node->field_episode_credit_person[$lang][0]['target_id'])) ? $node->field_episode_credit_person[$lang][0]['target_id'] : '';
    }
//dpm($params);

    // set paths
    $theme_path = drupal_get_path('module', 'usanetwork_show_microsite') . '/themes/' . $params['theme'];

    // add css
    drupal_add_css($theme_path . '/css/ms_style.css');
    drupal_add_css($theme_path . '/css/trivia.css');

    // add js
    drupal_add_js($theme_path . '/js/microsite_global.js');
  }
  return theme('usanetwork_dig_show_page', $params);
}

/**
 * Get all a-spot info for show microsites
 */
/*
function _usanetwork_get_all_aspots($lang='und') {
  if (isset($vars['field_usa_hp_arefs'][$lang])){
    usanetwork_aspot_aspot_settings($vars['field_usa_hp_arefs'][$lang], $lang);
  }
  $aspots = array();
//dpm($node->field_usa_hp_arefs[$lang]);
//  $empty = (!empty($node->field_usa_hp_arefs[$lang][0])) ? 1 : 0;
//  $count = (count($node->field_usa_hp_arefs[$lang]) > 0) ? 1 : 0;
// echo 'empty: ' . $empty . '<br>count: ' . $count . '<br>';
  $i=0;
  while (!empty($node->field_usa_hp_arefs[$lang][$i]['entity'])) {
//    foreach($node->field_usa_hp_arefs[$lang] as $key => $value) {
//dpm($key);
//dpm($value['entity']);
      $aspots[$i] = (array)$node->field_usa_hp_arefs[$lang][$i]['entity'];
      $i++;
//    }
  }
  return $aspots;
}
*/

/**
 * Implements hook_theme().
 */
function usanetwork_show_microsite_theme() {
usa_print('usanetwork_show_microsite_theme');
  $module_path = drupal_get_path('module', 'usanetwork_show_microsite');
  $themes = array(
    'usanetwork_dig_show_page' => array(
      'template' => 'usanetwork_show_microsite',
      'path' => $module_path . '/themes/dig/templates',
    ),
  );
  return $themes;
}

/**
 * Implements hook_permission
 */
function usanetwork_show_microsite_permission() {
  $perm = array(
    'view microsites' => array(
      'title' => t('View microsites'),
    ),
    'create microsites' => array(
      'title' => t('Create microsites'),
    ),
    'manage microsites' => array(
      'title' => t('Manage microsites'),
    )
  );
  return $perm;
}
