<?php
/**
 * @file
 * Code for the USA Network TOP3.
 */

include_once 'usanetwork_top3.features.inc';

/**
 * Implements hook_menu().
 */
function usanetwork_top3_menu() {
  $items['ajax/top3_create_url'] = array(
    'page callback' => '_usanetwork_top3_create_url',
    'page arguments' => array(),
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function usanetwork_top3_block_info() {
  $blocks = array();
  $blocks['usanetwork_top3_main_block'] = array(
    'info' => t('TOP3: Main Block'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_top3_block_view($delta) {
  $block = array();
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'usanetwork_top3_main_block':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _usanetwork_top3_main_block(),
        '#attached' => array(
          'js' => array(
            $pdk_controller_url = "http://player.theplatform.com/pdk/HNK2IC/tpPdkController.js",
            drupal_add_js($pdk_controller_url, 'external'),
            drupal_get_path('module', 'gigya') . '/js/gigya_sharebar.js',
            drupal_get_path('module', 'usanetwork_top3') . '/js/draggabilly.pkgd.min.js',
            drupal_get_path('module', 'usanetwork_top3') . '/js/dragdrop.js',
            drupal_get_path('module', 'usanetwork_top3') . '/js/html2canvas.min.js',
            drupal_get_path('theme', 'aurora_usa') . '/javascripts/slick.min.js',
            drupal_get_path('module', 'usanetwork_top3') . '/js/usanetwork_top3.js',
          ),
          'css' => array(
            drupal_get_path('module', 'gigya') . '/css/gigya.css',
          ),
        ),
      );
  }
  return $block;
}

/*
 * Implements hook_theme
 */
function usanetwork_top3_theme($existing, $type, $theme, $path) {
  $themes = array(
    'usanetwork_top3_main_block' => array(
      'variables' => array(
      ),
      'template' => 'templates/usanetwork-top3-main-block',
    ),
    'usanetwork_top3_shared'=> array(
      'variables' => array(
      ),
      'template' => 'templates/usanetwork-top3-shared',
    ),
  );
  return $themes;
}

/*
 * Main block for TOP3 Page
 */
function _usanetwork_top3_main_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $node = menu_get_object('node');
  if (empty($node)) {
    return '';
  }

  $node_wrapper = entity_metadata_wrapper('node', $node);
  $logo_image = $node_wrapper->field_logo->value();
  if (!empty($logo_image)) {
    $logo = file_create_url($logo_image['uri']);
  }

  $query_params = drupal_get_query_parameters();
  if (!empty($query_params) && (isset($query_params['shared']) && isset($query_params['node']))) {
    if (isset($query_params['shared']) && isset($query_params['node'])) {
      $shared_fids = explode('|', $query_params['shared']);
      $shared_files = file_load_multiple($shared_fids);
      $slides = array();
      foreach ($shared_files as $shared_file) {
        list($title, $video_image) = _usanetwork_top3_get_title_and_image($node, $shared_file);
        $slides[] = array(
          'title' => !empty($title) ? $title : NULL,
          'image' => !empty($video_image) ? image_style_url('2880x1620', $video_image) : NULL,
//          'video' => isset($video) ? $video : NULL,
        );
      }
    }
    $theme_variables = array(
      'slides' => $slides,
      'logo' => isset($logo) ? $logo : NULL,
      'node_path' => url('node/' . $node->nid),
    );

    return theme('usanetwork_top3_shared', $theme_variables);
  }
  else {
    $slides = array();
    if (!empty($node->field_slides_content)) {
      foreach ($node_wrapper->field_slides_content->getIterator() as $delta => $slide_item) {
        $slide_image = $slide_item->field_top3_image->value();
        $slide_video = $slide_item->field_top3_video->value();
        if (empty($slide_image)) {
          $slide_image_url = _usanetwork_mpx_video_get_image_path($slide_video);
        }
        else {
          $slide_image_url = $slide_image['uri'];
        }
        if (!empty($slide_video)) {
          $fid = $slide_video->fid;
          $video = _usanetwork_mpx_video_get_player_src(array(
            'file' => $slide_video,
            'pub_mpx_player_parameters' => array('autoPlay' => 'true'),
          ));
        }
        else {
          $fid = $slide_image['fid'];
        }
        $title = $slide_item->field_episodic_1_title->value();
        $slides[] = array(
          'title' => !empty($title) ? $title : NULL,
          'image' => !empty($slide_image_url) ? image_style_url('2880x1620', $slide_image_url) : NULL,
          'fid' => $fid,
          'video' => isset($video) ? $video : NULL,
        );
      }
    }

    $theme_variables = array(
      'slides' => $slides,
      'logo' => isset($logo) ? $logo : NULL,
      'nid' => $node->nid,
    );
    return theme('usanetwork_top3_main_block', $theme_variables);
  }
}

function _usanetwork_top3_get_title_and_image($node, $shared_file) {
  $db_select = db_select('field_data_field_slides_content', 'slides_content');
  $db_select->condition('slides_content.entity_id', $node->nid);

  if ($shared_file->filemime == 'image/png') {
    $db_select->leftJoin('field_data_field_top3_image', 'top3_image', 'top3_image.entity_id=slides_content.field_slides_content_value');
    $db_select->condition('top3_image.field_top3_image_fid', $shared_file->fid);
  } else {
    $db_select->join('field_data_field_top3_video', 'top3_video', 'top3_video.entity_id=slides_content.field_slides_content_value');
    $db_select->condition('top3_video.field_top3_video_target_id', $shared_file->fid);
    $db_select->leftJoin('field_data_field_top3_image', 'top3_image', 'top3_image.entity_id=slides_content.field_slides_content_value');
    $db_select->addField('top3_image', 'field_top3_image_fid', 'slide_image');
  }
  $db_select->leftJoin('field_data_field_episodic_1_title', 'top3_title', 'top3_title.entity_id=slides_content.field_slides_content_value');
  $db_select->addField('top3_title', 'field_episodic_1_title_value', 'slide_title');
  $result = $db_select->execute()->fetchObject();

  if ($result) {
    return array(isset($result->slide_title) ? $result->slide_title : NULL, isset($result->slide_image) ? $result->slide_image : NULL);
  } else {
    return NULL;
  }
}


/*
 * Implements hook_preprocess_block
 */
function usanetwork_top3_preprocess_block(&$vars) {
  if ($vars['block']->delta == 'usanetwork_top3_main_block') {
    $node = menu_get_object('node');
    if (!empty($node)) {
      $node_wrapper = entity_metadata_wrapper('node', $node);
      $background_image = $node_wrapper->field_background->value();
      if (!empty($background_image)) {
        $background = file_create_url($background_image['uri']);
        $vars['attributes_array']['style'][] = 'background: url(' . $background . ') repeat';
      }

      $query_params = drupal_get_query_parameters();
      if (!empty($query_params) && (isset($query_params['shared']) && isset($query_params['node']))) {
        $vars['classes_array'][] = 'shared-screen';
      }
    }
  }
}

/*
 * Callbacl for ajax call
 */
function _usanetwork_top3_create_url() {
  if (!empty($_POST['galleryNid']) && !empty($_POST['firstFid']) && !empty($_POST['secondFid']) && !empty($_POST['thirdFid']) && !empty($_POST['imageSrc'])) {
    $data = $_POST['imageSrc'];

    $new_folder = 'public://top3_shared/';
    $is_writable = file_prepare_directory($new_folder, FILE_CREATE_DIRECTORY);

    if ($is_writable) {
      $data = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $data));
      $filename = 'image' . $_POST['firstFid'] . $_POST['secondFid'] . $_POST['thirdFid'];
      $image_uri = 'public://top3_shared/' . $filename . '.png';
      $isCreated = file_put_contents($image_uri, $data);

      if ($isCreated) {
        $image_url = file_create_url($image_uri);
      }
    }

    $url = url('node/' . $_POST['galleryNid'], array('query' => array('shared' => $_POST['firstFid'] . '|' . $_POST['secondFid'] . '|' . $_POST['thirdFid'])));
    return drupal_json_output(array('url' => $url, 'image_url' => $image_url));
  }
}
