<?php
/**
 * @file
 * Code for the USA Network TOP3.
 */

include_once 'usanetwork_top3.features.inc';

/**
 * Implements hook_menu().
 */
function usanetwork_top3_menu() {
  $items['top3_create_url/%/%/%/%'] = array(
    'page callback' => '_usanetwork_top3_create_url',
    'page arguments' => array(1, 2, 3, 4),
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function usanetwork_top3_block_info() {
  $blocks = array();
  $blocks['usanetwork_top3_main_block'] = array(
    'info' => t('TOP3: Main Block'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_top3_block_view($delta) {
  $block = array();
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'usanetwork_top3_main_block':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _usanetwork_top3_main_block(),
        '#attached' => array(
          'js' => array(
            $pdk_controller_url = "http://player.theplatform.com/pdk/HNK2IC/tpPdkController.js",
            drupal_add_js($pdk_controller_url, 'external'),
            drupal_get_path('module', 'usanetwork_top3') . '/js/draggabilly.pkgd.min.js',
            drupal_get_path('module', 'usanetwork_top3') . '/js/dragdrop.js',
            drupal_get_path('module', 'usanetwork_top3') . '/js/html2canvas.min.js',
            drupal_get_path('theme', 'aurora_usa') . '/javascripts/slick.min.js',
            drupal_get_path('module', 'usanetwork_top3') . '/js/usanetwork_top3.js',
          ),
        ),
      );
  }
  return $block;
}

/*
 * Implements hook_theme
 */
function usanetwork_top3_theme($existing, $type, $theme, $path) {
  $themes = array(
    'usanetwork_top3_main_block' => array(
      'variables' => array(
      ),
      'template' => 'templates/usanetwork-top3-main-block',
    ),
    'usanetwork_top3_shared'=> array(
      'variables' => array(
      ),
      'template' => 'templates/usanetwork-top3-shared',
    ),
  );
  return $themes;
}

function _usanetwork_top3_main_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $node = menu_get_object('node');
  if (empty($node)) {
    return '';
  }

  $query_params = drupal_get_query_parameters();
  if (!empty($query_params) && (isset($query_params['shared']) && isset($query_params['node']))) {
    if (isset($query_params['shared']) && isset($query_params['node'])) {
      $shared_fids = explode('|', $query_params['shared']);
      $shared_files = file_load_multiple($shared_fids);
    }
    return theme('usanetwork_top3_shared', array());
  } else {
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $logo_image = $node_wrapper->field_logo->value();
    if (!empty($logo_image)) {
      $logo = file_create_url($logo_image['uri']);
    }

    $slides = array();
    if (!empty($node->field_slides_content)) {
      foreach ($node_wrapper->field_slides_content->getIterator() as $delta => $slide_item) {
        $slide_image = $slide_item->field_top3_image->value();
        $slide_video = $slide_item->field_top3_video->value();
        if (empty($slide_image)) {
          $slide_image_url = _usanetwork_mpx_video_get_image_path($slide_video);
        } else {
          $slide_image_url = $slide_image['uri'];
        }

        if (!empty($slide_video)) {
          $fid = $slide_video->fid;
          $video = '';
        } else {
          $fid = $slide_image['fid'];
        }
        $title = $slide_item->field_episodic_1_title->value();
        $slides[] = array(
          'title' => !empty($title) ? $title : NULL,
          'image' => !empty($slide_image_url) ? image_style_url('2880x1620', $slide_image_url) : NULL,
          'is_video' => (!empty($slide_video)) ? TRUE : FALSE,
          'fid' => $fid,
          'video' => isset($video) ? $video : NULL,
        );
      }
    }

    $theme_variables = array(
      'slides' => $slides,
      'logo' => isset($logo) ? $logo : NULL,
      'nid' => $node->nid,
    );
    return theme('usanetwork_top3_main_block', $theme_variables);
  }
}

function usanetwork_top3_preprocess_block(&$vars) {
  if ($vars['block']->delta == 'usanetwork_top3_main_block') {
    $node = menu_get_object('node');
    if (!empty($node)) {
      $node_wrapper = entity_metadata_wrapper('node', $node);
      $background_image = $node_wrapper->field_background->value();
      if (!empty($background_image)) {
        $background = file_create_url($background_image['uri']);
        $vars['attributes_array']['style'][] = 'background: url(' . $background . ') repeat';
      }
    }
  }
}

function _usanetwork_top3_create_url($nid, $first, $second, $third) {

  return url('node/' . $nid, array('query' => array('shared' => $first . '|' .  $second . '|' . $third)));
}
