<?php
/**
 * @file
 * Code for the usanetwork_nitro feature.
 */

include_once 'usanetwork_nitro.features.inc';


/**
 * Implements hook_block_info().
 */
function usanetwork_nitro_block_info() {
  $blocks = array();
  $blocks['usa_nitro'] = array(
    'info' => t('USANETWORK: Nitro Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_nitro_block_view($delta) {
  $block = array();
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'usa_nitro':
      $block['subject'] = '';
      $block['content'] = usanetwork_nitro_block_callback();
      break;
  }
  return $block;
}

/**
 * If set-up for this page, log Nitro actions.
 */
function usanetwork_nitro_block_callback() {
  $lang = LANGUAGE_NONE;
	$arg = arg();

	// redirect to show page if its an invalid url
  if (!isset($arg[1]) || empty($arg[1])) {
    return '';
  }

	$node = node_load($arg[1]);
	$pathAlias = drupal_get_path_alias('node/' . arg(1));

	$js = '';
	if (isset($node->field_enable_nitro[$lang][0]['value']) && $node->field_enable_nitro[$lang][0]['value'] == 1) {
		$nitroName = $node->field_nitro_action_name[$lang][0]['value'];
		$js .= 'var usanetwork_nitro_path = "' . $pathAlias . '";';
		$js .= 'var usanetwork_nitro_action_name = "' . $nitroName . '";';
		drupal_add_js($js, array('type' => 'inline'));
  	drupal_add_js(drupal_get_path('module', 'usanetwork_nitro') . '/js/usanetwork_nitro_club.js');
	}

	return '';
}
