<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function usanetwork_menu_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
  if ($module == 'panels_mini' && $api == 'panels_default') {
    return array('version' => 1);
  }
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_menu().
 */
function usanetwork_menu_menu() {
  $items = array();

  // Used for rendering ajax block
  $items['ajax/render-running-show/%/%'] = array(
    'title' => 'Running show',
    'page callback' => 'usanetwork_menu_render_running_show_ajax',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['ajax/render-watch-live/%'] = array(
    'title' => 'Running show',
    'page callback' => 'usanetwork_menu_render_watch_live_show_ajax',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function usanetwork_menu_block_info() {
  $blocks = array();

  $blocks['usanetwork_menu_sm_main'] = array(
    'info' => t('Homepage Menu: Main menu'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  
  $blocks['usanetwork_menu_sm_featured'] = array(
    'info' => t('Homepage Menu: Featured items'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  $blocks['usanetwork_menu_sm_primetime'] = array(
    'info' => t('Homepage Menu: Primetime tonight'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  $blocks['usanetwork_menu_sm_upcoming'] = array(
    'info' => t('Homepage Menu: Upcoming show episodes'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_now_and_next'] = array(
    'info' => t('Homepage Menu: On now and Up next'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_watch_live'] = array(
    'info' => t('Homepage Menu: Watch live'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_menu'] = array(
    'info' => t('Usanetwork Menu: Menu block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_fm_shows'] = array(
    'info' => t('Usanetwork Footer: Shows'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_fm_apps_services'] = array(
    'info' => t('Usanetwork Footer: Apps & Services'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  $blocks['usanetwork_menu_fm_social_links'] = array(
    'info' => t('Usanetwork Footer: Social links'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_fm_menu'] = array(
    'info' => t('Usanetwork Footer: Footer block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_aspot_ot'] = array(
    'info' => t('Usanetwork A-Spot: On now, tonight'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_consumptionator'] = array(
    'info' => t('Usanetwork Consumptionator: Upper menu'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_menu_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'usanetwork_menu_sm_main':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_main_menu_block();
      break;
    
    case 'usanetwork_menu_sm_featured':
      $block['subject'] = t('Featured');
      $block['content'] = _usanetwork_menu_show_menu_featured_block();
      break;

    case 'usanetwork_menu_sm_primetime':
      $block['subject'] = t('Primetime tonight');
      $block['content'] = _usanetwork_menu_show_menu_primetime_block();
      break;

    case 'usanetwork_menu_sm_upcoming':
      $block['subject'] = t('Upcoming show episodes');
      $block['content'] = _usanetwork_menu_show_menu_upcoming_episodes_block();
      break;

    case 'usanetwork_menu_sm_now_and_next':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_show_menu_now_and_next_block();
      break;

    case 'usanetwork_menu_sm_watch_live':
      $block['subject'] = t('Watch live!');
      $block['content'] = _usanetwork_menu_show_menu_watch_live_block();
      break;

    case 'usanetwork_menu_sm_menu':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _usanetwork_menu_render_show_menu_block(),
        '#attached' => array(
          'js' => array(
              path_to_theme('aurora_usa') . '/javascripts/menu-dropdown.js',
          ),
        ),
      );
      break;

    case 'usanetwork_menu_fm_shows':
      $block['subject'] = t('Shows');
      $block['content'] = usanetwork_tv_shows_footer_links();
      break;

    case 'usanetwork_menu_fm_apps_services':
      $block['subject'] = t('Apps & Services');
      $block['content'] = _usanetwork_menu_footer_apps_services();
      break;
    
    case 'usanetwork_menu_fm_social_links':
      $block['subject'] = '';
      $block['content'] = usanetwork_bottom_footer();
      break;

    case 'usanetwork_menu_fm_menu':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_render_footer_menu_block();
      break;

    case 'usanetwork_menu_aspot_ot':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_aspot_onnow_tonight_block();
      break;

    case 'usanetwork_menu_consumptionator':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_consumptionator_block();
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function usanetwork_menu_theme() {
  return array(
    'usanetwork_menu_smnav_img_show_item' => array(
      'variables' => array(
        'title' => NULL,
        'image' => NULL,
        'cta_text' => NULL,
        'node_url' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-smnav-img-show-item',
    ),
    'usanetwork_menu_smnav_img_show_container' => array(
      'variables' => array(
        'elements' => NULL
      ),
      'template' => 'templates/usanetwork-menu-smnav-img-show-container',
    ),
    'usanetwork_menu_smnav_primetime_item' => array(
      'variables' => array(
        'time' => NULL,
        'show_title' => NULL,
        'show_episode' => NULL,
        'data' => NULL,
        'node_url' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-smnav-primetime-item',
    ),
    'usanetwork_menu_smnav_primetime_container' => array(
      'variables' => array(
        'elements' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-smnav-primetime-container',
    ),
    'usanetwork_menu_smnav_upcoming_element_item' => array(
      'variables' => array(
        'image_url' => NULL,
        'image' => NULL,
        'show_name' => NULL,
        'episode_title' => NULL,
        'episode_day' => NULL,
        'episode_time' => NULL,
        'episode_interval' => NULL,
        'episode_description' => NULL,
        'node_url' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-smnav-upcoming-element-item',
    ),
    'usanetwork_menu_smnav_upcoming_element_container' => array(
      'variables' => array(
        'elements' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-smnav-upcoming-element-container',
    ),
    'usanetwork_menu_smnav_now_next' => array(
      'variables' => array(
        'on_now' => array(),
        'up_next' => array(),
      ),
      'template' => 'templates/usanetwork-smnav-now-next',
    ),
    'usanetwork_menu_smnav_watch_live' => array(
      'variables' => array(
        'image' => NULL,
        'title' => NULL,
        'season' => NULL,
        'episode' => NULL,
        'season_and_episode' => NULL,
        'node_url' => NULL,
      ),
      'template' => 'templates/usanetwork-smnav-watch-live',
    ),
    'usanetwork_menu_aspot_onnow_tonight' => array(
      'variables' => array(
        'on_now_block_item' => array(
          'on_now' => array(
            'show_title' => NULL,
            'episode_title' => NULL,
          ),
          'up_next' => array(
            'show_title' => NULL,
            'episode_title' => NULL,
            'time' => NULL,
            'day_part' => NULL,
          ),
        ),
        'tonight_block_items' => array(
          0 => array(
            'show_title' => NULL,
            'time' => NULL,
            'day_part' => NULL,
          ),
          1 => array(
            'show_title' => NULL,
            'time' => NULL,
            'day_part' => NULL,
          ),
          2 => array(
            'show_title' => NULL,
            'time' => NULL,
            'day_part' => NULL,
          ),
        ),
      ),
      'template' => 'templates/usanetwork-aspot-onnow-tonight',
    ),
    'usanetwork_menu_consumptionator' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'episode' => array(
          'caption' => NULL,
          'image_url' => NULL,
          'title' => NULL,
          'season_number' => NULL,
          'episode_number' => NULL,
          'running_time' => NULL,
          'description' => NULL,
        ),
      ),
      'template' => 'templates/usanetwork-menu-consumptionator',
    ),
  );
}

/**
 * Implements hook_image_default_styles().
 */
function usanetwork_menu_image_default_styles() {
  $styles = array();

  $styles['episode_preview_temp'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 143,
          'height' => 81,
        ),
        'weight' => 0,
      ),
    ),
  );

  return $styles;
}

/**
 * Render header main menu block
 */
function _usanetwork_menu_main_menu_block() {
  $menu = menu_load('main-menu');
  if (!$menu) {
    return;
  }
  $menu_links = menu_load_links($menu['menu_name']);
  foreach ($menu_links as $item) {
    $items[] = array(
      'data' => l($item['link_title'], $item['link_path'], array('html' => TRUE, 'attributes' => array('class' => array('no-refresh'), 'data-state' => array('')))),
      'class' => array(
        'tab',
      ),
    );
  }

  return  theme('usanetwork_item_list', array(
    'title' => NULL,
    'items' => $items,
    'type' => 'ul',
    'attributes' => array(
      'class' => array(
        'menu',
      )
    ),
  ));
}

/**
 * Renders featured content block.
 * The callback is only FOR TESTING and POC!
 */
function _usanetwork_menu_show_menu_featured_block() {
  $output = array();
  $homepage = usanetwork_home_get_homepage(array('usa_homepage'));

  if (!empty($homepage['node'])) {
    $node_data = reset($homepage['node']);
    $node = node_load($node_data->nid);

    $field_hp_nav_img_shows = field_get_items('node', $node, 'field_hp_nav_img_shows');

    if (!empty($field_hp_nav_img_shows)) {
      foreach ($field_hp_nav_img_shows as $field_reference) {
        $reference_node = node_load($field_reference['target_id']);

        if ($reference_node) {
          $image_url = NULL;
          $image_field = field_get_items('node', $reference_node, 'field_gobal_nav_image');

          $cta_text = NULL;
          $cta_field = field_get_items('node', $reference_node, 'field_global_nav_cta_text');

          if (!empty($image_field)) {
            $image_field = reset($image_field);
            $image_url = file_create_url($image_field['uri']);
          }

          if (!empty($cta_field)) {
            $cta_field = reset($cta_field);
            $cta_text = $cta_field['value'];
          }

          $output[] = theme('usanetwork_menu_smnav_img_show_item', array(
            'title' => $reference_node->title,
            'image' => $image_url,
            'cta_text' => $cta_text,
            'type' => NULL,
            'time' => NULL,
            'node_url' => NULL,
          ));
        }
      }
    }
  }

  if (!empty($output)) {
    return theme('usanetwork_menu_smnav_img_show_container', array('elements' => $output));
  }

  return '';
}

/**
 * Renders primetime block.
 */
function _usanetwork_menu_show_menu_primetime_block() {
  $elements = array();
  $programs = _usanetwork_tv_schedule_get_primetime_items();

  if (!empty($programs)) {
    foreach ($programs as $program) {
      $elements[] = theme('usanetwork_menu_smnav_primetime_item', array(
        'time' => array(
          'value' => date('g:i', $program->start_time),
          'interval' => date('A', $program->start_time),
        ),
        'show_title' => $program->show_title,
        'show_episode' => $program->title,
        'node_url' => NULL,
      ));
    }
  }

  if (!empty($elements)) {
    return theme('usanetwork_menu_smnav_primetime_container', array(
      'elements' => $elements,
    ));
  }

  return '';
}

/**
 * Renders block of upcoming episodes.
 */
function _usanetwork_menu_show_menu_upcoming_episodes_block() {
  $elements = array();
  $node = _usanetwork_menu_show_menu_get_current_show_node();

  if (!empty($node)) {
    $episodes = _usanetwork_tv_schedule_get_upcoming_episodes($node);

    if (!empty($episodes)) {
      foreach ($episodes as $episode) {
        $preview_image = NULL;
        $image_uri = _usanetwork_menu_show_menu_get_image_preview_url($episode->episode_nid, 'tv_episode');

        if (!empty($image_uri)) {
          $preview_image = theme('image', array(
            'path' => $image_uri,
            'attributes' => array(
              'class' => array(
                'upcoming-episodes-preview-image'
              ),
            ),
          ));
        }

        $elements[] = theme('usanetwork_menu_smnav_upcoming_element_item', array(
          'image_url' => $image_uri,
          'image' => $preview_image,
          'show_name' => $episode->show_title,
          'episode_title' => $episode->title,
          'episode_day' => date('l', $episode->start_time),
          'episode_time' => date('g:i', $episode->start_time),
          'episode_interval' => date('A', $episode->start_time),
          'episode_description' => $episode->program_description,
          'node_url' => !empty($episode->episode_nid)
            ? url('node/' . $episode->episode_nid)
            : '',
          'show_nid' => $episode->show_nid,
        ));
      }
    }
  }

  if (!empty($elements)) {
    return theme('usanetwork_menu_smnav_upcoming_element_container', array(
      'elements' => $elements,
    ));
  }

  return '';
}

/**
 * Renders Show Menu.
 */
function _usanetwork_menu_render_show_menu_block() {
  $output = '';

  $panel = panels_mini_load('usanetwork_show_menu');

  if ($panel) {
    $output = panels_render_display($panel->display);
  }

  return $output;
}

/**
 * Renders Footer Menu.
 */
function _usanetwork_menu_render_footer_menu_block() {
  $output = '';

  $panel = panels_mini_load('usanetwork_footer');

  if ($panel) {
    $output = panels_render_display($panel->display);
  }

  return $output;
}

/**
 * Returns current Show node.
 */
function _usanetwork_menu_show_menu_get_current_show_node() {
  $menu_item = menu_get_item();

  if (!empty($menu_item['page_arguments'])) {
    $node = reset($menu_item['page_arguments']);

    if (isset($node->type) && $node->type == 'tv_show') {
      return $node;
    }
  }

  return NULL;
}

/**
 * Returns current Episode node.
 */
function _usanetwork_menu_show_menu_get_current_episode_node() {
  $menu_item = menu_get_item();

  if (!empty($menu_item['page_arguments'])) {
    $node = reset($menu_item['page_arguments']);

    if (isset($node->type) && $node->type == 'tv_episode') {
      return $node;
    }
  }

  return NULL;
}

/**
 * Renders "On now & Up next" block.
 */
function _usanetwork_menu_show_menu_now_and_next_block() {
  $block_form = array();

  $spinner_options = array(
    'path' => drupal_get_path('theme', 'aurora_usa') . '/images/ajax-loader.gif',
    'alt' => t('Please wait...'),
    'title' => t('Please wait'),
    'attributes' => array('class' => 'spinner'),
  );

  $block_form['#attached']['js'][] = libraries_get_path('jstz') . '/jstz-1.0.4.min.js';
  $block_form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.common.js';
  $block_form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.now_and_next.js';
  $block_form['test'] = array(
    '#type' => 'item',
    '#markup' => theme('image', $spinner_options),
  );

  return render($block_form);
}

/**
 * Renders AJAX block using users timezone
 */
function usanetwork_menu_render_running_show_ajax($user_timezone, $periods = 'now,next') {
  $data = usanetwork_tv_schedule_get_running_show_ajax($user_timezone, $periods, FALSE);

  if ($data) {
    $theme_variables = array(
      'on_now' => array(
        'image' => !empty($data['now']->nid)
          ? theme('image', array(
            'path' => _usanetwork_menu_show_menu_get_image_preview_url($data['now']->nid),
            'attributes' => array(
              'class' => array(
                'running-now-show-preview-image'
              ),
            ),
          ))
          : '',
        'title' => !empty($data['now']->show_title) ? $data['now']->show_title : '',
        'caption' => !empty($data['now']->title) ? $data['now']->title : '',
        'description' => !empty($data['now']->program_description)
          ? $data['now']->program_description
          : '',
        'node_url' => !empty($data['now']->nid)
          ? (url('node/' . $data['now']->nid))
          : '',
      ),
      'up_next' => array(
        'image' => !empty($data['next']->nid)
          ? theme('image', array(
            'path' => _usanetwork_menu_show_menu_get_image_preview_url($data['next']->nid),
            'attributes' => array(
              'class' => array(
                'running-next-show-preview-image'
              ),
            ),
          ))
          : '',
        'title' => !empty($data['next']->show_title) ? $data['next']->show_title : '',
        'caption' => !empty($data['next']->title) ? $data['next']->title : '',
        'description' => !empty($data['next']->program_description)
          ? $data['next']->program_description
          : '',
        'time' => !empty($data['next']->start_time)
          ? date('h:i', $data['next']->start_time)
          : '',
        'time_daypart' => !empty($data['next']->start_time)
          ? date('A', $data['next']->start_time)
          : '',
        'node_url' => !empty($data['next']->nid)
          ? (url('node/' . $data['next']->nid))
          : '',
      ),
    );

    return drupal_json_output(array(
      'html' => theme('usanetwork_menu_smnav_now_next', $theme_variables),
    ));
  }

  return drupal_json_output(NULL);
}

/**
 * Renders AJAX block using users timezone
 */
function usanetwork_menu_render_watch_live_show_ajax($user_timezone) {
  $data = usanetwork_tv_schedule_get_running_show_ajax($user_timezone, 'now', FALSE);

  if ($data) {
    $theme_variables = array(
      'image' => !empty($data['now']->nid)
        ? theme('image', array(
          'path' => _usanetwork_menu_show_menu_get_image_preview_url($data['now']->nid),
          'attributes' => array(
            'class' => array(
              'watch-live-show-preview-image'
            ),
          ),
        ))
        : '',
      'title' => !empty($data['now']->title) ? $data['now']->title : '',
      'season' => !empty($data['now']->season_number)
        ? $data['now']->season_number
        : '',
      'episode' => !empty($data['now']->season_episode_number)
        ? $data['now']->season_episode_number
        : '',
      'season_and_episode' => (!empty($data['now']->season_number) && !empty($data['now']->season_episode_number))
        ? ('S' . $data['now']->season_number . ' ' . t('Episode') . ' ' . $data['now']->season_episode_number)
        : '',
      'node_url' => !empty($data['now']->nid)
        ? url('node/' . $data['now']->nid, array(
          'alias' => TRUE,
        ))
        : '',
    );

    return drupal_json_output(array(
      'html' => theme('usanetwork_menu_smnav_watch_live', $theme_variables),
    ));
  }

  return drupal_json_output(NULL);
}

/**
 * Renders "Watch Live" block.
 */
function _usanetwork_menu_show_menu_watch_live_block() {
  $block_form = array();

  $spinner_options = array(
    'path' => drupal_get_path('theme', 'aurora_usa') . '/images/ajax-loader.gif',
    'alt' => t('Please wait...'),
    'title' => t('Please wait'),
    'attributes' => array('class' => 'spinner'),
  );

  $block_form['#attached']['js'][] = libraries_get_path('jstz') . '/jstz-1.0.4.min.js';
  $block_form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.common.js';
  $block_form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.watch_live.js';
  $block_form['test'] = array(
    '#type' => 'item',
    '#markup' => theme('image', $spinner_options),
  );

  return render($block_form);
}

/**
 * Returns preview image URL.
 */
function _usanetwork_menu_show_menu_get_image_preview_url($nid, $type = 'tv_show') {
  switch ($type) {
    case 'tv_show':
      return _usanetwork_menu_show_menu_show_get_image_preview_url($nid);
    case 'tv_episode':
      return _usanetwork_menu_show_menu_episode_get_image_preview_url($nid);
  }
}

/**
 * Loads previewing image for show.
 */
function _usanetwork_menu_show_menu_show_get_image_preview_url($nid) {
  $query = db_select('field_data_field_logo', 'fl');
  $query->fields('fl', array('field_logo_fid'));
  $query->condition('fl.entity_id', $nid);
  $query->range(0, 1);

  $result = $query->execute()->fetch();

  if ($result) {
    $file = file_load($result->field_logo_fid);
    return $file->uri;
  }

  return;
}

/**
 * Loads previewing image for episode.
 */
function _usanetwork_menu_show_menu_episode_get_image_preview_url($nid) {
  $query = db_select('field_data_field_tv_cover_media', 'fm');
  $query->fields('fm', array('field_cover_media_fid'));
  $query->condition('fm.entity_id', $nid);
  $query->range(0, 1);

  $result = $query->execute()->fetch();

  if ($result) {
    $file = file_load($result->field_cover_media_fid);
    return $file->uri;
  }

  return;
}
/**
 * Render button footer block for Apps & Services
 */
function _usanetwork_menu_footer_apps_services() {

  $menu = menu_load('menu-apps-services');
  if (!$menu) {
    return;
  }
  $menu_links = menu_load_links($menu['menu_name']);
  foreach ($menu_links as $item) {
    $items[] = array(
      'data' => l($item['link_title'], $item['link_path'], array('html' => TRUE)),
      'class' => array(
        'menu-item'
      ),
    );
  }

  return  theme('usanetwork_item_list', array(
    'warpper_attributes' => array(
      'class' => array(
        'app-and-services-menu',
      ),
    ),
    'title' => NULL,
    'items' => $items,
    'type' => 'ul',
    'attributes' => array(
      'class' => array(
        'menu',
      )
    ),
  ));
}

/**
 * Renders Consumtionator Menu block.
 */
function _usanetwork_menu_consumptionator_block() {
  $episode_node = _usanetwork_menu_show_menu_get_current_episode_node();

  if ($episode_node) {
    $episode_node_wrapper = entity_metadata_wrapper('node', $episode_node);

    if (!empty($episode_node_wrapper)) {
      $body_meta_data = $episode_node_wrapper->body->value();
      $episode_caption = $episode_node_wrapper->field_tv_episode_type->name->label();

      if (empty($episode_caption)) {
        $episode_caption = t('Full episode');
      }

      return theme('usanetwork_menu_consumptionator', array(
        'show_url' => url('node/' . $episode_node_wrapper->field_show->value()->nid),
        'show_name' => $episode_node_wrapper->field_show->value()->title,
        'episode' => array(
          'caption' => $episode_caption,
          'image_url' => $episode_node_wrapper->field_tv_cover_media->file->value()->uri,
          'title' => $episode_node_wrapper->title->value(),
          'season_number' => $episode_node_wrapper->field_season->field_season_id->value(),
          'episode_number' => $episode_node_wrapper->field_episode_number->value(),
          'running_time' => gmdate('H:i:s', $episode_node_wrapper->field_original_air_date->duration->value()),
          'description' => !empty($body_meta_data) ? $body_meta_data['value'] : '',
        ),
      ));
    }
  }

  return '';
}

/**
 * Renders OnNow, Tonight at the bottom of the A-Spot carousel.
 */
function _usanetwork_menu_aspot_onnow_tonight_block() {
  $on_now = usanetwork_schedule_pull_on_now_item();
  $up_next = usanetwork_schedule_pull_up_next_item();
  $tonight = _usanetwork_tv_schedule_get_primetime_items(3);

  $on_now_block = array();
  $up_next_block = array();
  $tonight_block = array();

  if (!empty($on_now)) {
    if (is_array($on_now)) {
      $on_now = reset($on_now);
    }

    $on_now_block = array(
      'show_title' => $on_now->show_title,
      'episode_title' => $on_now->title,
    );
  }

  if (!empty($up_next)) {
    if (is_array($up_next)) {
      $up_next = reset($up_next);
    }

    $up_next_block = array(
      'show_title' => $up_next->show_title,
      'episode_title' => $up_next->title,
      'time' => date('H:i', $up_next->start_time),
      'day_part' => date('A', $up_next->start_time),
    );
  }

  if (!empty($tonight)) {
    foreach ($tonight as $tonight_item) {
      $tonight_block[] = array(
        'show_title' => $tonight_item->show_title,
        'time' => date('H:i', $tonight_item->start_time),
        'day_part' => date('A', $tonight_item->start_time),
      );
    }
  }
  
  $theme_data = array(
    'on_now_block_item' => array(
      'on_now' => $on_now_block,
      'up_next' => $up_next_block,
    ),
    'tonight_block_items' => $tonight_block,
  );

  return theme('usanetwork_menu_aspot_onnow_tonight', $theme_data);
}
