<?php

define('USANETWORK_MENU_FULL_EPISODES_NUMBER', 6);
define('USANETWORK_MENU_MOVIES_NUMBER', 6);
define('USANETWORK_MENU_SHOWS_LANDING_SHOWS_NUMBER', 4);
include_once 'usanetwork_menu.features.inc';


/**
 * Implements hook_menu().
 */
function usanetwork_menu_menu() {
  $items = array();

  // Used for rendering ajax block
  $items['ajax/render-running-show/%/%'] = array(
    'title' => 'Running show',
    'page callback' => 'usanetwork_menu_render_running_show_ajax',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['ajax/render-onnow-tonight/%'] = array(
    'title' => 'On now / Tonight',
    'page callback' => '_usanetwork_menu_aspot_onnow_tonight_ajax',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['ajax/render-live-video-header/%'] = array(
    'title' => 'Live video header',
    'page callback' => '_usanetwork_menu_render_live_video_header_ajax',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  // Show autocompliter.
  $items['usanetwork_menu/full_shows/autocomplete'] = array(
    'title' => 'Select content',
    'page callback' => 'usanetwork_menu_full_shows_autocomplete',
    'access arguments' => array('administer nodes'),
    'delivery callback' => 'drupal_deliver_html_page',
    'type' => MENU_CALLBACK,
  );

  // Movies autocompliter.
  $items['usanetwork_menu/movies/autocomplete'] = array(
    'title' => 'Select content',
    'page callback' => 'usanetwork_menu_movies_autocomplete',
    'access arguments' => array('administer nodes'),
    'delivery callback' => 'drupal_json_output',
    'type' => MENU_CALLBACK,
  );

  // admin area
  $items['admin/usanetwork/shows-landing-page'] = array(
    'title' => 'Shows Landing Page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('usanetwork_menu_shows_landing_main_form'),
    'access arguments' => array('administer site configuration'),
  );

  // Show autocompliter.
  $items['usanetwork_menu/shows/autocomplete'] = array(
    'title' => 'Select content',
    'page callback' => 'usanetwork_menu_shows_autocomplete',
    'access arguments' => array('administer nodes'),
    'delivery callback' => 'drupal_deliver_html_page',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function usanetwork_menu_block_info() {
  $blocks = array();

  $blocks['usanetwork_menu_sm_main'] = array(
    'info' => t('Homepage Menu: Main menu'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_all_shows'] = array(
    'info' => t('Homepage Menu: Shows: All Shows'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_primetime'] = array(
    'info' => t('Homepage Menu: Primetime tonight'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_now_and_next'] = array(
    'info' => t('Homepage Menu: On now and Up next'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_full_episodes'] = array(
    'info' => t('Homepage Menu: Full Episodes'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_movies'] = array(
    'info' => t('Homepage Menu: Movies'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_news'] = array(
    'info' => t('Homepage Menu: News'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_sm_menu'] = array(
    'info' => t('Usanetwork Menu: Menu block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_fm_shows'] = array(
    'info' => t('Usanetwork Footer: Shows'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_fm_apps_services'] = array(
    'info' => t('Usanetwork Footer: Apps & Services'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_fm_social_links'] = array(
    'info' => t('Usanetwork Footer: Social links'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_fm_menu'] = array(
    'info' => t('Usanetwork Footer: Footer block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_aspot_ot'] = array(
    'info' => t('Usanetwork A-Spot: On now, tonight'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['usanetwork_menu_consumptionator'] = array(
    'info' => t('Usanetwork Consumptionator: Upper menu'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['usanetwork_menu_page_header'] = array(
    'info' => t('Usanetwork static page: Upper menu'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usanetwork_menu_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'usanetwork_menu_sm_main':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_main_menu_block();
      break;

    case 'usanetwork_menu_sm_all_shows':
      $block['subject'] = t('Current Shows');
      $block['content'] = _usanetwork_menu_all_shows_block(TRUE);
      break;

    case 'usanetwork_menu_sm_primetime':
      $block['subject'] = t('Tonight');
      $block['content'] = _usanetwork_menu_show_menu_primetime_block();
      break;

    case 'usanetwork_menu_sm_now_and_next':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_show_menu_now_and_next_block();
      break;

    case 'usanetwork_menu_sm_full_episodes':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_full_episodes_block();
      break;

    case 'usanetwork_menu_sm_movies':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_movies_block();
      break;

    case 'usanetwork_menu_sm_news':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_news_block();
      break;

    case 'usanetwork_menu_sm_menu':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _usanetwork_menu_render_show_menu_block(),
        '#attached' => array(
          'js' => array(
            path_to_theme('aurora_usa') . '/javascripts/menu-dropdown.js',
          ),
        ),
      );
      break;

    case 'usanetwork_menu_fm_shows':
      $block['subject'] = t('Shows');
      $block['content'] = _usanetwork_menu_all_shows_block(FALSE);
      break;

    case 'usanetwork_menu_fm_apps_services':
      $block['subject'] = t('Apps & Services');
      $block['content'] = _usanetwork_menu_footer_apps_services();
      break;

    case 'usanetwork_menu_fm_social_links':
      $block['subject'] = '';
      $block['content'] = usanetwork_bottom_footer();
      break;

    case 'usanetwork_menu_fm_menu':
      $block['subject'] = '';
      $block['content'] = _usanetwork_menu_render_footer_menu_block();
      break;

    case 'usanetwork_menu_aspot_ot':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _usanetwork_menu_aspot_onnow_tonight_block(),
        '#attached' => array(
          'js' => array(
            path_to_theme('aurora_usa') . '/javascripts/jquery.carouFredSel.min.js',
          ),
        ),
      );
      break;

    case 'usanetwork_menu_consumptionator':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _usanetwork_menu_consumptionator_block(),
        '#attached' => array(
          'js' => array(
            path_to_theme('aurora_usa') . '/javascripts/menu-dropdown.js',
          ),
        ),
      );
      break;
    case 'usanetwork_menu_page_header':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _usanetwork_menu_static_page_header_block(),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function usanetwork_menu_theme() {
  return array(
    'usanetwork_menu_smnav_primetime_item' => array(
      'variables' => array(
        'time' => NULL,
        'show_title' => NULL,
        'show_episode' => NULL,
        'data' => NULL,
        'node_url' => NULL,
        'syndicated_url' => NULL,
        'episode_full_url' => NULL,
        'show_class' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-smnav-primetime-item',
    ),
    'usanetwork_menu_smnav_primetime_container' => array(
      'variables' => array(
        'elements' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-smnav-primetime-container',
    ),
    'usanetwork_menu_smnav_now_next' => array(
      'variables' => array(
        'on_now' => array(),
        'up_next' => array(),
      ),
      'template' => 'templates/usanetwork-smnav-now-next',
    ),
    'usanetwork_menu_full_episodes' => array(
      'variables' => array(
        'items' => array(
          'logo' => NULL,
          'url' => NULL,
          'additional' => NULL,
          'image' => NULL,
        ),
      ),
      'template' => 'templates/usanetwork-menu-full-episodes',
    ),
    'usanetwork_menu_movies' => array(
      'variables' => array(
        'items' => array(
          'title' => NULL,
          'url' => NULL,
          'image' => NULL,
        ),
      ),
      'template' => 'templates/usanetwork-menu-movies',
    ),
    'usanetwork_menu_news' => array(
      'variables' => array(
        'items' => array(
          'title' => NULL,
          'url' => NULL,
          'image' => NULL,
        ),
      ),
      'template' => 'templates/usanetwork-menu-news',
    ),
    'usanetwork_menu_aspot_onnow_tonight' => array(
      'variables' => array(
        'on_now_block_item' => array(
          'on_now' => array(
            'show_title' => NULL,
            'episode_title' => NULL,
            'syndicated_url' => NULL,
            'episode_full_url' => NULL,
            'label_link' => NULL,
            'on_now_caption' => NULL,
            'on_now_live_button' => NULL
          ),
          'up_next' => array(
            'show_title' => NULL,
            'episode_title' => NULL,
            'time' => NULL,
            'day_part' => NULL,
            'syndicated_url' => NULL,
            'episode_full_url' => NULL,
            'label_link' => NULL,
          ),
        ),
        'tonight_block_items' => array(
          0 => array(
            'show_title' => NULL,
            'time' => NULL,
            'day_part' => NULL,
            'syndicated_url' => NULL,
            'episode_full_url' => NULL,
          ),
          1 => array(
            'show_title' => NULL,
            'time' => NULL,
            'day_part' => NULL,
            'syndicated_url' => NULL,
            'episode_full_url' => NULL,
          ),
          2 => array(
            'show_title' => NULL,
            'time' => NULL,
            'day_part' => NULL,
            'syndicated_url' => NULL,
            'episode_full_url' => NULL,
          ),
        ),
      ),
      'template' => 'templates/usanetwork-aspot-onnow-tonight',
    ),
    'usanetwork_menu_consumptionator_video' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'episode' => array(
          'caption' => NULL,
          'image_url' => NULL,
          'title' => NULL,
          'season_number' => NULL,
          'episode_number' => NULL,
          'running_time' => NULL,
          'description' => NULL,
        ),
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_video',
    ),
    'usanetwork_menu_consumptionator_catchall' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'catchall_name' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_catchall',
    ),
    'usanetwork_menu_consumptionator_gallery' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'gallery_name' => NULL,
        'details' => array(),
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_gallery',
    ),
    'usanetwork_menu_consumptionator_timeline_gallery' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'gallery_name' => NULL,
        'details' => array(),
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_timeline_gallery',
    ),
    'usanetwork_menu_consumptionator_episode_guide' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'episode_name' => NULL,
        'details' => array(),
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_episode_guide',
    ),
    'usanetwork_menu_consumptionator_person' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'person_name' => NULL,
        'details' => array(),
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_person',
    ),
    'usanetwork_menu_consumptionator_quiz' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'person_name' => NULL,
        'details' => array(),
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_quiz',
    ),
    'usanetwork_menu_consumptionator_post' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'h1' => NULL,
        'details' => array(),
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_post',
    ),
    'usanetwork_menu_consumptionator_top3_gallery' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'h1' => NULL,
        'details' => array(),
        'title' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-consumptionator_top3_gallery',
    ),
    'usanetwork_menu_consumptionator_live_video' => array(
      'variables' => array(
        'main_url' => NULL,
        'authbar' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-consumptionator-live-video',
    ),
    'usanetwork_menu_static_page_header' => array(
      'variables' => array(
        'title' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-static-page-header',
    ),
    'usanetwork_menu_consumptionator_microsite_catchall' => array(
      'variables' => array(
        'show_url' => NULL,
        'show_name' => NULL,
        'catchall_name' => NULL,
      ),
      'template' => 'templates/usanetwork-menu-microsite-consumptionator_catchall',
    ),
  );
}

/**
 * Implements hook_image_default_styles().
 */
function usanetwork_menu_image_default_styles() {
  $styles = array();

  $styles['339x68'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 339,
          'height' => 68,
        ),
        'weight' => 0,
      ),
    ),
  );

  $styles['full_episodes_633x356'] = array(
    'name' => '633x356',
    'label' => '633x356',
    'effects' => array(
      array(
        'name' => 'focal_point_scale_and_crop',
        'data' => array(
          'width' => 633,
          'height' => 356,
        ),
        'weight' => 0,
      ),
      array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 633,
          'height' => 356,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}


/**
 * Alter gigya share settings.
 */
function usanetwork_menu_gigya_sharebar_alter(&$share_settings, $context) {
  if (!empty($context['display']['share_settings']) ) {
    $share_settings['gigyaSharebar']['ua'] = array_merge($share_settings['gigyaSharebar']['ua'], $context['display']['share_settings']);
  }
  if ($context['entity_type'] == 'node') {
    $node = $context['entity'];
    $node_wrapper = entity_metadata_wrapper('node', $node);
    if (!empty($node->field_share_title)) {
      $share_settings['gigyaSharebar']['ua']['title'] = $node_wrapper->field_share_title->value();
    }
    if (!empty($node->field_share_description)) {
      $share_settings['gigyaSharebar']['ua']['description'] = $node_wrapper->field_share_description->value();
    }
  }
}

/**
 * Render header main menu block
 */
function _usanetwork_menu_main_menu_block() {
  drupal_add_js(variable_get('usanetwork_seeit_script_url', USANETWORK_SEEIT_DEFAULT_URL), array(
    'type' => 'external',
    'scope' => 'footer',
  ));

  $menu = menu_load('main-menu');
  if (!$menu) {
    return;
  }
  $menu_links = menu_load_links($menu['menu_name']);

  //menu element for mobile menu on Show Page
  $show = menu_get_object();
  if(usanetwork_core_api_check_field($show, 'field_show_links')) {
    if (isset($show->type) && $show->type == 'tv_show') {
      $items[] = array(
        'data' => l($show->title, 'javascript:void(0)', array(
          'fragment' => '',
          'external' => TRUE,
          'attributes' => array(
            'class' => array(
              'show-color',
              'show-border',
              'active'
            )
          )
        )),
        'class' => array(
          'expanded',
          'header-show-menu',
          'active',
        ),
      );
    }

    if ((isset($show->type) && $show->type == 'consumpt_blog')) {
      $blog_show_id = _usanetwork_get_field_item('node', $show, 'field_show', 'target_id');
      if (!empty($blog_show_id)) {
        $blog_show = node_load($blog_show_id);
        $items[] = array(
          'data' => l($blog_show->title, 'javascript:void(0)', array(
            'fragment' => '',
            'external' => TRUE,
            'attributes' => array(
              'class' => array(
                'show-color',
                'show-border',
                'active'
              )
            )
          )),
          'class' => array(
            'expanded',
            'header-show-menu',
            'active',
          ),
        );
      }
    }
  }

  foreach ($menu_links as $item) {
    if (!$item['hidden']) {
      $items[] = array(
        'data' => l($item['link_title'], $item['link_path'], array('html' => TRUE, 'attributes' => array('class' => array('no-refresh'), 'data-state' => array('')))),
        'class' => array(
          'tab',
        ),
      );
    }
  }
  return theme('usanetwork_item_list', array(
    'title' => NULL,
    'items' => $items,
    'type' => 'ul',
    'attributes' => array(
      'class' => array(
        'menu',
      ),
    ),
    'links_set' => 'category',
  ));
}

/**
 * Render shows menu items
 */
function _usanetwork_menu_all_shows_block($header = TRUE) {
  $query_result = views_get_view_result('usa_nav', 'block');
  $links = array();
  foreach ($query_result as $row) {
    $new = '';
    if (!$header) {
      if ($row->flag_content_node_timestamp) {
        $new = '<span> ' . t('New!') . '</span>';
      }
    }
    $links[] = array(
      'data' => l($row->node_title . $new, 'node/' . $row->nid, array('html' => TRUE)),
      'class' => array(
        'menu-item'
      ),
    );
  }
  return theme('usanetwork_item_list', array(
      'warpper_attributes' => array(
        'class' => array(
          'shows-menu',
        ),
      ),
      'title_tag' => 'h2',
      'title_attributes' => array(
        'class' => array(
          'menu-title',
          'shows-menu-title',
        ),
      ),
      'items' => $links,
      'type' => 'ul',
      'attributes' => array(
        'class' => array(
          'menu'
        )
      ),
    )
  );
}

/**
 * Renders primetime block.
 */
function _usanetwork_menu_show_menu_primetime_block() {
  $elements = array();
  $programs = _usanetwork_tv_schedule_get_primetime_items();

  if (!empty($programs)) {
    foreach ($programs as $program) {
      $elements[] = theme('usanetwork_menu_smnav_primetime_item', array(
        'time' => array(
          'value' => date('g:i', $program->start_time),
          'interval' => date('A', $program->start_time),
        ),
        'show_title' => $program->show_title,
        'show_episode' => $program->title,
        'node_url' => NULL,
        'syndicated_url' => isset($program->nid) ? _usanetwork_menu_get_reminder_url($program->nid) : NULL,
        'episode_full_url' => url('schedule', array('query' => array('guid' => $program->guid))),
        'show_class' => !empty($program->nid)
            ? usanetwork_tv_shows_color_show_css_class($program->nid)
            : 'show-undefined',
      ));
    }
  }

  if (!empty($elements)) {
    return theme('usanetwork_menu_smnav_primetime_container', array(
      'elements' => $elements,
    ));
  }

  return '';
}

/**
 * Renders Show Menu.
 */
function _usanetwork_menu_render_show_menu_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $output = '';

  $panel = panels_mini_load('usanetwork_show_menu');

  if ($panel) {
    $output = panels_render_display($panel->display);
  }

  return $output;
}

/**
 * Renders Footer Menu.
 */
function _usanetwork_menu_render_footer_menu_block() {
  $output = '';

  $panel = panels_mini_load('usanetwork_footer');

  if ($panel) {
    $output = panels_render_display($panel->display);
  }

  return $output;
}

/**
 * Returns current Show node.
 */
function _usanetwork_menu_show_menu_get_current_show_node() {
  $menu_item = menu_get_item();

  if (!empty($menu_item['page_arguments'])) {
    $node = reset($menu_item['page_arguments']);

    if (isset($node->type) && $node->type == 'tv_show') {
      return $node;
    }
  }

  return NULL;
}

/**
 * Returns current entity.
 */
function _usanetwork_menu_get_current_entity() {
  $menu_item = menu_get_item();

  if (!empty($menu_item['page_arguments'])) {
    $entity = reset($menu_item['page_arguments']);

    if (isset($entity->filemime)) {
      $entity->entity_type = 'file';
    }
    else if (isset($entity->type) && isset($entity->nid)) {
      $entity->entity_type = 'node';
    }
    return $entity;
  }

  return FALSE;
}

/**
 * Returns current Episode node.
 */
function _usanetwork_menu_show_menu_get_current_episode_node() {
  $menu_item = menu_get_item();

  if (!empty($menu_item['page_arguments'])) {
    $node = reset($menu_item['page_arguments']);

    if (isset($node->type) && $node->type == 'tv_episode') {
      return $node;
    }
  }

  return NULL;
}

/**
 * Renders "On now & Up next" block.
 */
function _usanetwork_menu_show_menu_now_and_next_block() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $block_form = array();

  $spinner_options = array(
    'path' => drupal_get_path('theme', 'aurora_usa') . '/images/ajax-loader.gif',
    'alt' => t('Please wait...'),
    'title' => t('Please wait'),
    'attributes' => array('class' => 'spinner'),
  );

  $block_form['#attached']['js'][] = libraries_get_path('jstz') . '/jstz-1.0.4.min.js';
  $block_form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.common.js';
  $block_form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.now_and_next.js';
  $block_form['test'] = array(
    '#type' => 'item',
    '#markup' => theme_image($spinner_options),
  );

  return render($block_form);
}

/**
 * Renders AJAX block using users timezone
 */
function usanetwork_menu_render_running_show_ajax($user_timezone, $periods = 'now,next') {
  $data = usanetwork_tv_schedule_get_running_show_ajax($user_timezone, $periods, FALSE);

  if ($data) {
    $theme_variables = array();

    if (!empty($data['now'])) {
      $image_url = _usanetwork_tv_schedule_get_schedule_item_image($data['now']);

      if (empty($image_url)) {
        $image_url = _usanetwork_menu_show_menu_get_image_preview_url($data['now']->nid);
      }

      $theme_variables['on_now'] = array(
        'image' => theme('image_style', array(
              'path' => $image_url,
              'style_name' => '300x169_video',
              'attributes' => array(
                'class' => array(
                  'running-now-show-preview-image'
                ),
              ),
            )),
        'title' => ($data['now']->program_type == 'movie') ? t('USA Movie') :
            (!empty($data['now']->show_title) ? $data['now']->show_title : ''),
        'label_link' => l(t('On now'), 'videos/live'),
        'caption' => !empty($data['now']->title)
            ? $data['now']->title
            : '',
        'description' => !empty($data['now']->program_description)
            ? $data['now']->program_description
            : '',
        'node_url' => !empty($data['now']->nid)
            ? (url('node/' . $data['now']->nid))
            : '',
        'syndicated_url' => ($data['now']->program_type != 'movie') ? _usanetwork_menu_get_reminder_url($data['now']->nid) : '',
        'episode_full_url' => url('schedule', array('query' => array('guid' => $data['now']->guid))),
        'show_class' => !empty($data['now']->nid)
            ? usanetwork_tv_shows_color_show_css_class($data['now']->nid)
            : 'show-undefined',
      );
    }
    if (!empty($data['next'])) {
      $image_url = _usanetwork_tv_schedule_get_schedule_item_image($data['next']);

      if (empty($image_url)) {
        $image_url = _usanetwork_menu_show_menu_get_image_preview_url($data['next']->nid);
      }

      $theme_variables['up_next'] = array(
        'image' => theme('image_style', array(
              'path' => $image_url,
              'style_name' => '300x169_video',
              'attributes' => array(
                'class' => array(
                  'running-next-show-preview-image'
                ),
              ),
            )),
        'title' => ($data['next']->program_type == 'movie') ? t('USA Movie') :
            (!empty($data['next']->show_title) ? $data['next']->show_title : ''),
        'label_link' => !empty($data['next']->nid) ? l(t('Up next'), 'node/' . $data['next']->nid) : t('Up next'),
        'caption' => !empty($data['next']->title)
            ? $data['next']->title
            : '',
        'description' => !empty($data['next']->program_description)
            ? $data['next']->program_description
            : '',
        'time' => !empty($data['next']->start_time)
            ? date('g:i', $data['next']->start_time)
            : '',
        'time_daypart' => !empty($data['next']->start_time)
            ? date('A', $data['next']->start_time)
            : '',
        'node_url' => !empty($data['next']->nid)
            ? (url('node/' . $data['next']->nid))
            : '',
        'syndicated_url' => ($data['next']->program_type != 'movie') ? _usanetwork_menu_get_reminder_url($data['next']->nid) : '',
        'episode_full_url' => url('schedule', array('query' => array('guid' => $data['next']->guid))),
        'show_class' => !empty($data['next']->nid)
            ? usanetwork_tv_shows_color_show_css_class($data['next']->nid)
            : 'show-undefined',
      );
    }

    return drupal_json_output(array(
      'html' => theme('usanetwork_menu_smnav_now_next', $theme_variables),
    ));
  }

  return drupal_json_output(NULL);
}

/**
 * Render Block for Menu Tab "Full Episodes"
 */
function _usanetwork_menu_full_episodes_block() {
  $header_full_episodes_shows = variable_get('header_full_episodes_shows', array());
  if (!empty($header_full_episodes_shows)) {
    $carousel_episodes = array();
    foreach ($header_full_episodes_shows as $needed_show) {
      if (preg_match("/^(.+)\[node:(\d+)\]$/", $needed_show, $matches)) {
        $file = usanetwork_schedule_pull_latest_episodes($matches[2], 1);
        if (!empty($file)) {
          $file = reset($file);
          $carousel_episodes[] = file_load($file->fid);
        }
      }
    }
  } else {
    $episodes = _usanetwork_mpx_video_get_latest_episodes_for_show(USANETWORK_MENU_FULL_EPISODES_NUMBER);
    $carousel_episodes = file_load_multiple(array_keys($episodes));
  }

  $items = array();
  foreach ($carousel_episodes as $episode) {
    $sponsored = FALSE;
    $episode_wrapper = entity_metadata_wrapper('file', $episode);
    $show = !empty($episode->field_show)
      ? $episode_wrapper->field_show->value()
      : NULL;

    if (!empty($show)) {
      $logo = usanetwork_core_api_get_content_image('node', $show, 'banner');
    }
    $episode_season = !empty($episode->field_mpx_season_number)
      ? $episode_wrapper->field_mpx_season_number->value()
      : NULL;
    $episode_number = !empty($episode->field_mpx_episode_number)
      ? $episode_wrapper->field_mpx_episode_number->value()
      : NULL;

    $episode_image = _usanetwork_mpx_video_get_image_path($episode);

    $video_image = theme('image_style', array(
      'path' => $episode_image,
      'style_name' => 'full_episodes_633x356',
    ));

    $sponsored_element = _usanetwork_menu_get_sponsored_file_by_show($show->nid);
    if ($sponsored_element) {
      $sponsored = TRUE;
      $file_path = $sponsored_element;
    }

    $items_variables = array(
      'url' => url('file/' . $episode->fid),
      'logo' => !empty($logo) ? theme('image_style', array('path' => $logo, 'style_name' => '339x68')) : NULL,
      'additional' => t('Season @season Episode @episode_number', array(
        '@season' => $episode_season,
        '@episode_number' => $episode_number
       )),
       'image' => $video_image,
      'sponsored' => $sponsored,
      'icon_type' => usanetwork_core_api_get_media_icon('file', $episode->fid),
      'file_path' => isset($file_path) ? '/file/' . $file_path : NULL,
      'file_name' => $episode->filename,
    );

    $items[] = $items_variables;
  }

  $theme_variables = array(
    'items' => $items,
  );

  return theme('usanetwork_menu_full_episodes', $theme_variables);
}

/*
 * Helper function for get sponsored file by show nid
 */
function _usanetwork_menu_get_sponsored_file_by_show($show_nid) {
  $query = db_select('file_managed', 'f')->fields('f', array('fid'));
  $query->condition('f.type', _pub_mpx_get_mpx_account_video_file_types(TRUE), 'IN');
  $query->leftJoin('field_data_field_show','show_field','show_field.entity_id = f.fid');
  $query->condition('show_field.field_show_target_id', $show_nid);
  $query->leftJoin('mpx_video','v','v.fid = f.fid');
  $query->condition('v.status', 1);
  $query->leftJoin('field_data_field_sponsored','fdfs','fdfs.entity_id = f.fid');
  $query->condition('fdfs.field_sponsored_value', 1);
  $query->orderBy('v.airdate', 'DESC');

  return $query->execute()->fetchField();
}

/**
 * Returns preview image URL.
 */
function _usanetwork_menu_show_menu_get_image_preview_url($nid, $type = 'tv_show') {
  switch ($type) {
    case 'tv_show':
      return _usanetwork_menu_show_menu_show_get_image_preview_url($nid);
    case 'tv_episode':
      return _usanetwork_menu_show_menu_episode_get_image_preview_url($nid);
  }
}

/**
 * Loads previewing image for show.
 */
function _usanetwork_menu_show_menu_show_get_image_preview_url($nid) {
  $query = db_select('field_data_field_logo', 'fl');
  $query->fields('fl', array('field_logo_fid'));
  $query->condition('fl.entity_id', $nid);
  $query->range(0, 1);

  $result = $query->execute()->fetch();

  if ($result) {
    $file = file_load($result->field_logo_fid);
    return $file->uri;
  }

  return;
}

/**
 * Loads previewing image for episode.
 */
function _usanetwork_menu_show_menu_episode_get_image_preview_url($nid) {
  $query = db_select('field_data_field_tv_cover_media', 'fm');
  $query->fields('fm', array('field_cover_media_fid'));
  $query->condition('fm.entity_id', $nid);
  $query->range(0, 1);

  $result = $query->execute()->fetch();

  if ($result) {
    $file = file_load($result->field_cover_media_fid);
    return $file->uri;
  }

  return;
}

/**
 * Render button footer block for Apps & Services
 */
function _usanetwork_menu_footer_apps_services() {

  $menu = menu_load('menu-apps-services');
  if (!$menu) {
    return;
  }
  $menu_links = menu_load_links($menu['menu_name']);
  foreach ($menu_links as $item) {
    $items[] = array(
      'data' => l($item['link_title'], $item['link_path'], array('html' => TRUE)),
      'class' => array(
        'menu-item'
      ),
    );
  }

  return theme('usanetwork_item_list', array(
    'warpper_attributes' => array(
      'class' => array(
        'app-and-services-menu',
      ),
    ),
    'title' => NULL,
    'items' => $items,
    'type' => 'ul',
    'attributes' => array(
      'class' => array(
        'menu',
      )
    ),
  ));
}

/**
 * Renders Consumtionator Menu block.
 */
function _usanetwork_menu_consumptionator_block() {
  if ($entity = menu_get_object('file')) {
    if (isset($entity->type) && (in_array($entity->type, _usanetwork_mpx_video_get_all_file_types()))) {
      return _usanetwork_menu_consumptionator_block_video($entity);
    }
  }
  elseif ($entity = menu_get_object('node')) {
    if (isset($entity->type)) {
      if ($entity->type == 'catchall_page') {
        return _usanetwork_menu_consumptionator_block_catchall($entity);
      }
      elseif ($entity->type == 'media_gallery') {
        return _usanetwork_menu_consumptionator_block_gallery($entity);
      }
      elseif ($entity->type == 'person') {
        return _usanetwork_menu_consumptionator_block_person($entity);
      }
      elseif ($entity->type == 'tv_episode') {
        return _usanetwork_menu_consumptionator_episode_guide($entity);
      }
      elseif ($entity->type == 'timeline_gallery') {
        return _usanetwork_menu_consumptionator_block_timeline_gallery($entity);
      }
      elseif ($entity->type == 'quiz') {
        return _usanetwork_menu_consumptionator_block_quiz($entity);
      }
      elseif ($entity->type == 'consumpt_post') {
        return _usanetwork_menu_consumptionator_block_consumpt_post($entity);
      }
      elseif ($entity->type == 'top3_gallery') {
        return _usanetwork_menu_consumptionator_block_top3_gallery($entity);
      }
      elseif ($entity->type == 'usanetwork_microsite') {
        return _usanetwork_menu_consumptionator_usanetwork_microsite($entity);
      }
    }
  }
  else { // Process like "Live video" block
    return _usanetwork_menu_consumptionator_block_live_video();
  }
}

/**
 * Renders Consumtionator Menu block for catchall.
 */
function _usanetwork_menu_consumptionator_block_catchall($node) {

  if (!empty($node)) {

    $entity_wrapper = entity_metadata_wrapper('node', $node);
    if (!empty($node->field_usa_og_image)) {
      $image = $entity_wrapper->field_usa_og_image->value();
    }
    $description = !empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() : '';
    $advert_block = module_invoke('usanetwork_tve_video', 'block_view', 'usanetwork_tve_video_auth_menu');
    if (!empty($advert_block['content'])) {
      $authbar = render($advert_block['content']);
    }
    $tv_content_node = usanetwork_core_api_get_tv_content_node($node);
    $tv_content_fields = usanetwork_core_api_get_tv_content_fields_names();
    if (!empty($tv_content_node->type)) {
      $field = !empty($tv_content_fields[$tv_content_node->type]) ? $tv_content_fields[$tv_content_node->type] : NULL;
    }
    $theme_variables = array(
      'main_url' => url('<front>'),
      'authbar' => isset($authbar) ? $authbar : NULL,
      'show_url' => isset($field) ? (!empty($node->{$field}) ? url('node/' . $entity_wrapper->{$field}->value()->nid) : '') : '',
      'show_name' => isset($field) ? (!empty($node->{$field}) ? $entity_wrapper->{$field}->value()->title : '') : '',
      'catchall_name' => $node->title,
      'h1' => !empty($node->field_seo_h1) ? $entity_wrapper->field_seo_h1->value() : '',
      'details' => array(
        'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
        'description' => $description,
        'sharebar' => usanetwork_menu_render_sharebar($node, 'node', t('Share'), $node->title, $description),
      ),
    );
    return theme('usanetwork_menu_consumptionator_catchall', $theme_variables);
  }
  return '';
}

/**
 * Renders Consumtionator Menu block for gallery.
 */
function _usanetwork_menu_consumptionator_block_gallery($node) {

  if (!empty($node)) {

    $entity_wrapper = entity_metadata_wrapper('node', $node);
    if (!empty($node->field_usa_og_image)) {
      $image = $entity_wrapper->field_usa_og_image->value();
    }
    elseif (!empty($node->field_cover_item)) {
      $image = $entity_wrapper->field_cover_item->value();
    }
    $description = !empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() :
      (!empty($node->body) ? $entity_wrapper->body->value->value() : '');
    if (!empty($node->field_episode)) {
      $episode = $entity_wrapper->field_episode->value();
      if ($episode_num_items = field_get_items('node', $episode, 'field_episode_number')) {
        $episode_num_items = reset($episode_num_items);
        $episode_num = $episode_num_items['value'];
      }
      if ($episode->field_season) {
        $season = $entity_wrapper->field_season->value();
        if ($season_num_items = field_get_items('node', $season, 'field_season_id')) {
          $season_num_items = reset($season_num_items);
          $season_num = $season_num_items['value'];
        }
      }
    }
    //Sponsored MPS
    if (!empty($node->field_sponsored)) {
      $field_sponsored = $entity_wrapper->field_sponsored->value();
      if ($field_sponsored == '1') {
        $sponsored = TRUE;
        $node_path = '/node/' . $node->nid;
      }
    }
    $advert_block = module_invoke('usanetwork_tve_video', 'block_view', 'usanetwork_tve_video_auth_menu');
    if (!empty($advert_block['content'])) {
      $authbar = render($advert_block['content']);
    }
    $tv_content_node = usanetwork_core_api_get_tv_content_node($node);
    $tv_content_fields = usanetwork_core_api_get_tv_content_fields_names();
    $field = (!empty($tv_content_node)) ? $tv_content_fields[$tv_content_node->type] : NULL;
    $node_title = !empty($node->title) ? $entity_wrapper->title->value() : NULL;
    $gallery_type = !empty($node->field_gallery_type) ? $entity_wrapper->field_gallery_type->value() : '';
    if (!empty($episode_num) && !empty($season_num)) {
      $title = t('S@season EP@episode: @title', array(
        '@season' => $season_num,
        '@episode' => $episode_num,
        '@title' => $node_title,
      ));
    }
    else {
      $title = $node_title;
    }
    $is_multiple_gallery = _usanetwork_media_gallery_is_multiple($node);
    $is_show_related = usanetwork_core_api_is_related_with_tv_content($node);
    $theme_variables = array(
      'is_multilple' => !(empty($is_multiple_gallery)) ? TRUE : FALSE,
      'is_show_related' => $is_show_related,
      'main_url' => url('<front>'),
      'authbar' => isset($authbar) ? $authbar : NULL,
      'show_url' => !empty($node->{$field}) ? url('node/' . $entity_wrapper->{$field}->value()->nid) : '',
      'show_name' => !empty($node->{$field}) ? $entity_wrapper->{$field}->value()->title : '',
      'gallery_name' => $title,
      'h1' => !empty($node->field_seo_h1) ? $entity_wrapper->field_seo_h1->value() : '',
      'details' => array(
        'sharebar' => usanetwork_menu_render_sharebar($node, 'node', t('Share this gallery'), $node->title, $description),
        'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
        'description' => $description,
        'gallery_type' => $gallery_type,
        'episode_info' => !empty($episode) ? array(
            'episode_title' => $episode->title,
            'season_number' => !empty($season_num) ? $season_num : '',
            'episode_number' => !empty($episode_num) ? $episode_num : '',
          ) : NULL,
      ),
      'sponsored' => isset($sponsored) ? $sponsored : FALSE,
      'node_path' => isset($node_path) ? $node_path : FALSE,
    );
    return theme('usanetwork_menu_consumptionator_gallery', $theme_variables);
  }
  return '';
}


/**
 * Renders Consumtionator Menu block for gallery.
 */
function _usanetwork_menu_consumptionator_block_timeline_gallery($node) {

  if (!empty($node)) {

    $entity_wrapper = entity_metadata_wrapper('node', $node);

    if (!empty($node->field_usa_og_image)) {
      $image = $entity_wrapper->field_usa_og_image->value();
    }
    elseif (!empty($node->field_cover_item)) {
      $image = $entity_wrapper->field_cover_item->value();
    }
    $description = !empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() :
      (!empty($node->field_summary) ? $entity_wrapper->field_summary->value() : '');
    $share_description = !empty($node->field_share_description) ? $entity_wrapper->field_share_description->value() :
      (!empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() : '');
    $theme_variables = array(
      'main_url' => url('<front>'),
      'show_url' => !empty($node->field_show) ? url('node/' . $entity_wrapper->field_show->value()->nid) : '',
      'show_name' => !empty($node->field_show) ? $entity_wrapper->field_show->value()->title : '',
      'gallery_name' => !empty($node->title) ? $node->title : '',
      'h1' => !empty($node->field_seo_h1) ? $entity_wrapper->field_seo_h1->value() : '',
      'details' => array(
        'sharebar' => usanetwork_menu_render_sharebar($node, 'node', t('Share this gallery'), $node->title, $share_description),
        'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
        'description' => $description,
        'gallery_type' => t('Timeline Gallery'),
      ),
    );
    return theme('usanetwork_menu_consumptionator_timeline_gallery', $theme_variables);
  }
  return '';
}

/**
 * Renders Consumtionator Menu block for episode guide.
 */
function _usanetwork_menu_consumptionator_episode_guide($node) {

  if (!empty($node)) {

    $entity_wrapper = entity_metadata_wrapper('node', $node);
    if (!empty($node->field_tv_cover_media)) {
      $image = $entity_wrapper->field_tv_cover_media->value();
    }
    $description = !empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() :
      (!empty($node->body) ? $entity_wrapper->body->value()['value'] : '');
    $description = preg_replace('/\[usa_embed:(\w+):(\w+):(\d+):(\w+)(:*)(\w*)\]/', '', $description);
    if (!empty($node->field_season)) {
      $season = $entity_wrapper->field_season->value();
      if ($season_num_items = field_get_items('node', $season, 'field_season_id')) {
        $season_num_items = reset($season_num_items);
        $season_num = $season_num_items['value'];
      }
    }
    $advert_block = module_invoke('usanetwork_tve_video', 'block_view', 'usanetwork_tve_video_auth_menu');
    if (!empty($advert_block['content'])) {
      $authbar = render($advert_block['content']);
    }
    $theme_variables = array(
      'authbar' => isset($authbar) ? $authbar : NULL,
      'main_url' => url('<front>'),
      'show_url' => !empty($node->field_show) ? url('node/' . $entity_wrapper->field_show->value()->nid) : '',
      'show_name' => !empty($node->field_show) ? $entity_wrapper->field_show->value()->title : '',
      'episode_name' => _usanetwork_core_get_node_title($node),
      'h1' => !empty($node->field_seo_h1) ? $entity_wrapper->field_seo_h1->value() : '',
      'details' => array(
        'sharebar' => usanetwork_menu_render_sharebar($node, 'node', t('Share this Episode Guide'), $node->title, $description),
        'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
        'description' => $description,
        'episode_type' => !empty($node->field_tv_episode_type) ? $entity_wrapper->field_tv_episode_type->name->value() : '',
        'episode_info' => array(
            'season_number' => !empty($season_num) ? $season_num : '',
            'episode_number' => !empty($node->field_episode_number) ? $entity_wrapper->field_episode_number->value() : '',
          ),
      ),
    );
    return theme('usanetwork_menu_consumptionator_episode_guide', $theme_variables);
  }
  return '';
}

/**
 * Renders Consumtionator Menu block for person.
 */
function _usanetwork_menu_consumptionator_block_person($node) {

  if (!empty($node)) {

    $entity_wrapper = entity_metadata_wrapper('node', $node);
    if (!empty($node->field_usa_og_image)) {
      $image = $entity_wrapper->field_usa_og_image->value();
    }
    elseif (!empty($node->field_usa_character_thumb)) {
      $image = $entity_wrapper->field_usa_character_thumb->value();
    }
    $description = !empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() :
      (!empty($node->body) ? $entity_wrapper->body->value->value() : '');
    $advert_block = module_invoke('usanetwork_tve_video', 'block_view', 'usanetwork_tve_video_auth_menu');
    if (!empty($advert_block['content'])) {
      $authbar = render($advert_block['content']);
    }
    $tv_content_node = usanetwork_core_api_get_tv_content_node($node);
    $tv_content_fields = usanetwork_core_api_get_tv_content_fields_names();
    $field = $tv_content_fields[$tv_content_node->type];
    $theme_variables = array(
      'authbar' => isset($authbar) ? $authbar : NULL,
      'main_url' => url('<front>'),
      'show_url' => !empty($node->{$field}) ? url('node/' . $entity_wrapper->{$field}->value()->nid) : '',
      'show_name' => !empty($node->{$field}) ? $entity_wrapper->{$field}->value()->title : '',
      'person_name' => !empty($node->title) ? $node->title : '',
      'h1' => !empty($node->field_seo_h1) ? $entity_wrapper->field_seo_h1->value() : '',
      'details' => array(
        'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
        'description' => $description,
        'sharebar' => usanetwork_menu_render_sharebar($node, 'node', t('Share this bio'), $node->title, $description),
      ),
    );
    return theme('usanetwork_menu_consumptionator_person', $theme_variables);
  }
  return '';
}

/**
 * Renders Consumtionator Menu block for person.
 */
function _usanetwork_menu_consumptionator_block_quiz($node) {

  if (!empty($node)) {

    $entity_wrapper = entity_metadata_wrapper('node', $node);
    if (!empty($node->field_usa_og_image)) {
      $image = $entity_wrapper->field_usa_og_image->value();
    }
    $description = !empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() :
      (!empty($node->body) ? $entity_wrapper->body->value->value() : '');
//    $description = preg_replace('/\[usa_embed:(\w+):(\w+):(\d+):(\w+)(:*)(\w*)\]/', '', $description)
    $description = preg_replace('/<iframe.*?>(.*)<\/iframe>/', '', $description);
    $tv_content_node = usanetwork_core_api_get_tv_content_node($node);
    $tv_content_fields = usanetwork_core_api_get_tv_content_fields_names();
    $field = $tv_content_fields[$tv_content_node->type];
    $theme_variables = array(
      'main_url' => url('<front>'),
      'show_url' => !empty($node->{$field}) ? url('node/' . $entity_wrapper->{$field}->value()->nid) : '',
      'show_name' => !empty($node->{$field}) ? $entity_wrapper->{$field}->value()->title : '',
      'quiz_name' => !empty($node->title) ? $node->title : '',
      'h1' => !empty($node->field_seo_h1) ? $entity_wrapper->field_seo_h1->value() : '',
      'details' => array(
        'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
        'description' => $description,
        'sharebar' => usanetwork_menu_render_sharebar($node, 'node', t('Share this quiz'), $node->title, $description),
      ),
    );
    return theme('usanetwork_menu_consumptionator_quiz', $theme_variables);
  }
  return '';
}

/**
 * Renders Consumtionator Menu block for person.
 */
function _usanetwork_menu_consumptionator_block_consumpt_post($node) {

  if (!empty($node)) {

    $entity_wrapper = entity_metadata_wrapper('node', $node);
    if (!empty($node->field_usa_og_image)) {
      $image = $entity_wrapper->field_usa_og_image->value();
    }
    elseif (!empty($node->field_post_cover)) {
      $image = $entity_wrapper->field_post_cover->value();
    }
    $description = !empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() :
      (!empty($node->field_summary) ? $entity_wrapper->field_summary->value->value() : '');

    //Sponsored MPS
    if (!empty($node->field_sponsored)) {
      $field_sponsored = $entity_wrapper->field_sponsored->value();
      if ($field_sponsored == '1') {
        $sponseored_node_path = '/node/' . $node->nid;
      }
    }
    $theme_variables = array(
      'main_url' => url('<front>'),
      'show_url' => !empty($node->field_show) ? url('node/' . $entity_wrapper->field_show->value()->nid) : url('news'),
      'show_name' => !empty($node->field_show) ? $entity_wrapper->field_show->value()->title : 'News',
      'post_name' => !empty($node->title) ? $node->title : '',
      'h1' => !empty($node->field_seo_h1) ? $entity_wrapper->field_seo_h1->value() : '',
      'details' => array(
        'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
        'description' => $description,
        'sharebar' => usanetwork_menu_render_sharebar($node, 'node', t('Share this post'), $node->title, $description),
      ),
      'sponseored_node_path' => isset($sponseored_node_path) ? $sponseored_node_path : NULL,
    );
    return theme('usanetwork_menu_consumptionator_post', $theme_variables);
  }
  return '';
}

function _usanetwork_menu_consumptionator_block_top3_gallery($node) {
  if (!empty($node)) {

    $entity_wrapper = entity_metadata_wrapper('node', $node);
    if (!empty($node->field_usa_og_image)) {
      $image = $entity_wrapper->field_usa_og_image->value();
    }
    elseif (!empty($node->field_post_cover)) {
      $image = $entity_wrapper->field_post_cover->value();
    }
    $description = !empty($node->field_usa_og_description) ? $entity_wrapper->field_usa_og_description->value() :
        (!empty($node->body) ? $entity_wrapper->body->value->value() : '');
    $theme_variables = array(
      'main_url' => url('<front>'),
      'show_url' => !empty($node->field_show) ? url('node/' . $entity_wrapper->field_show->value()->nid) : '',
      'show_name' => !empty($node->field_show) ? $entity_wrapper->field_show->value()->title : '',
      'title' => !empty($node->title) ? t('TOP 3: ') . $node->title : '',
      'h1' => !empty($node->field_seo_h1) ? $entity_wrapper->field_seo_h1->value() : '',
      'details' => array(
        'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
        'description' => $description,
        'sharebar' => usanetwork_menu_render_sharebar($node, 'node', t('Share this Top3'), $node->title, $description),
      ),
    );
    return theme('usanetwork_menu_consumptionator_top3_gallery', $theme_variables);
  }
  return '';
}

/**
 * Renders Consumtionator Menu block for video.
 */
function _usanetwork_menu_consumptionator_block_video($file) {

  if (!empty($file)) {


    $auth_block = module_invoke('usanetwork_tve_video', 'block_view', 'usanetwork_tve_video_auth_menu');
    if (!empty($auth_block['content'])) {
      $authbar = render($auth_block['content']);
    }

    $file_wrapper = entity_metadata_wrapper('file', $file);

    $episode_image_uri = _usanetwork_mpx_video_get_image_path($file);

    //Sponsored MPS
    if (!empty($file->field_sponsored)) {
      $field_sponsored = $file_wrapper->field_sponsored->value();
      if ($field_sponsored == '1') {
        $sponsored = TRUE;
        $file_id = '/file/' . $file->fid;
      }
    }
    $description = !empty($file->field_usa_og_description) ? $file_wrapper->field_usa_og_description->value() :
      (!empty($file->field_mpx_description)
        ? $file_wrapper->field_mpx_description->value()
        : '');
    $tv_content_node = usanetwork_core_api_get_tv_content_node($file);
    $tv_content_fields = usanetwork_core_api_get_tv_content_fields_names();
    $field = $tv_content_fields[$tv_content_node->type];
    $is_show_related = ($tv_content_node->type == 'tv_show') ? TRUE : FALSE;
    $theme_variables = array(
      'sharebar' => usanetwork_menu_render_sharebar($file, 'file', t('Share this video'), $file_wrapper->name->value(), $description),
      'authbar' => !empty($authbar) ? ($authbar) : '',
      'main_url' => url('<front>'),
      'show_url' => $is_show_related
          ? (!empty($file->{$field})
            ? url('node/' . $file_wrapper->{$field}->value()->nid)
            : '')
          : url('movies'),
      'show_name' => $is_show_related
        ? (!empty($file->{$field})
          ? $file_wrapper->{$field}->value()->title
          : '')
        : t('Movies'),
      'h1' => !empty($file->field_seo_h1) ? $file_wrapper->field_seo_h1->value() : '',
      'episode' => array(
        'is_show_related' => $is_show_related,
        'video_type' => $is_show_related
          ? (!empty($file->field_mpx_full_episode)
            ? ($file_wrapper->field_mpx_full_episode->value()
              ? t('Full Episode')
              : t('Video'))
            : '')
          : t('Movie'),
        'image_url' => !empty($episode_image_uri)
          ? image_style_url('300x169_video', $episode_image_uri)
          : '',
        'full_title' => !empty($file->field_mpx_title)
          ? $file_wrapper->field_mpx_title->value()
          : '',
        'title' => _usanetwork_core_get_video_title($file),
        'season_number' => !empty($file->field_mpx_season_number)
          ? $file_wrapper->field_mpx_season_number->value()
          : '',
        'episode_number' => !empty($file->field_mpx_episode_number)
          ? $file_wrapper->field_mpx_episode_number->value()
          : '',
        'running_time' => !empty($file->field_mpx_duration)
          ? gmdate('H:i:s', $file_wrapper->field_mpx_duration->value())
          : '',
        'description' => $description,
      ),
      'sponsored' => isset($sponsored) ? $sponsored : FALSE,
      'file_path' => isset($file_id) ? $file_id : FALSE,
    );
    return theme('usanetwork_menu_consumptionator_video', $theme_variables);
  }
  return '';
}

function _usanetwork_menu_consumptionator_usanetwork_microsite($node) {
  if (!empty($node)) {
    $menu_type = usanetwork_microsite_process_setting_data('consumptionator_menu');
    if ($menu_type == 'catchall_page') {
      $entity_wrapper = entity_metadata_wrapper('node', $node);
      $section_wrapper = _usanetwork_microsite_get_section_wrapper_by_section_type($node, 'home');
      $image = $section_wrapper->field_usa_og_image->value();
      $sharebar = '
                  <h3 class="field-label">Share</h3>
                  <div class="field field-name-field-gigya-share-bar field-type-gigya-sharebar field-label-above">
                    <div id="menu-gigya-share"></div>
                  </div>
      ';
      $seo_h1 =  _usanetwork_microsite_get_h1_tag($section_wrapper);
      $description = $section_wrapper->field_usa_og_description->value();
      $theme_variables = array(
        'main_url' => url('<front>'),
        'show_url' => !empty($node->field_show) ? url('node/' . $entity_wrapper->field_show->value()->nid) : '',
        'show_name' => !empty($node->field_show) ? $entity_wrapper->field_show->value()->title : '',
        'catchall_name' => $node->title,
        'h1' => !empty($seo_h1) ? $seo_h1 : '',
        'details' => array(
          'image' => !empty($image) ? image_style_url('300x250', $image['uri']) : '',
          'description' => !empty($description) ? $description : '',
          'sharebar' => !empty($sharebar) ? render($sharebar) : '',
        ),
      );
      return theme('usanetwork_menu_consumptionator_microsite_catchall', $theme_variables);
    }
    return '';
  }
}

/**
 * Renders Consumtionator Menu block for static pages
 */
function _usanetwork_menu_static_page_header_block() {
  $node = menu_get_object('node');
  if (!empty($node)) {
    return theme('usanetwork_menu_static_page_header', array(
      'title' => $node->title,
    ));
  }
  return theme('usanetwork_menu_static_page_header', array(
    'title' => drupal_get_title(),
  ));
}

function _usanetwork_menu_render_live_video_header_ajax($offset) {
  $on_now_item = usanetwork_schedule_pull_on_now_item($offset, 'show_title');
  if (!empty($on_now_item)) {
    $image_url = NULL;

    if (is_array($on_now_item)) {
      $on_now_item = reset($on_now_item);
    }

    if (!empty($on_now_item->nid)) {
      $image_url = usanetwork_core_api_get_content_image('node', $on_now_item->nid);
    }

    $additional = '';
    if (!empty($on_now_item->season_number) && !empty($on_now_item->season_episode_number)) {
      $additional = '<span>S' . $on_now_item->season_number . ' episode ' . $on_now_item->season_episode_number . '</span>';
    }
    elseif (!empty($on_now_item->season_number)) {
      $additional = '<span>S' . $on_now_item->season_number . '</span>';
    }
    elseif (!empty($on_now_item->season_episode_number)) {
      $additional = '<span>episode ' . $on_now_item->season_episode_number . '</span>';
    }
    $on_now_variables = array(
      'show_url' => !empty($on_now_item->nid)
        ? url('node/' . $on_now_item->nid)
        : url('<front>'),
      'show_name' => ($on_now_item->program_type == 'movie') ? t('USA Movie') :
          (!empty($on_now_item->show_title) ? $on_now_item->show_title : ''),
      'episode' => array(
        'image_url' => !empty($image_url)
          ? image_style_url('300x250', $image_url)
          : '',
        'title' => !empty($on_now_item->title)
          ? t('Live: !title', array('!title' => $on_now_item->title))
          : '',
        'video_type' => $on_now_item->program_type,
        'additional' => !empty($additional) ? $additional : '',
        'running_time' => (!empty($on_now_item->start_time) && !empty($on_now_item->end_time))
          ? gmdate('H:i:s', $on_now_item->end_time - $on_now_item->start_time)
          : '',
        'description' => !empty($on_now_item->program_description)
          ? $on_now_item->program_description
          : '',
        'episode_class' => !empty($on_now_item->nid)
            ? usanetwork_tv_shows_color_show_css_class($on_now_item->nid)
            : NULL,
      ),
    );
    $on_now_variables = json_encode($on_now_variables);
    return drupal_json_output(array(
      'on_now_vars' => $on_now_variables));
  }

  return '';
}

function _usanetwork_menu_consumptionator_block_live_video() {
  if (!module_exists('usanetwork_tv_schedule')) {
    return '';
  }

  drupal_add_js(drupal_get_path('module', 'usanetwork_tv_schedule') . '/js/jstz-1.0.4.min.js');
  drupal_add_js(drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.common.js');
  drupal_add_js(drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.live_video_header.js');
  drupal_add_js(
    array(
      'usanetwork_menu' => array(
        'usa_live_tv_img' => file_create_url('sites/usanetwork/themes/aurora_usa/images/usa_liveTV.jpg'),
      )
    ),
    'setting'
  );
  $advert_block = module_invoke('usanetwork_tve_video', 'block_view', 'usanetwork_tve_video_auth_menu');
  if (!empty($advert_block['content'])) {
    $authbar = render($advert_block['content']);
  }

  $query = db_select('file_managed', 'fm')
    ->fields('fm', array('fid'))
    ->condition('fm.type', _pub_mpx_get_mpx_account_video_file_types(TRUE), 'IN');
  $query->leftJoin('field_data_field_usa_video_terms' , 'fdfuvt', 'fdfuvt.entity_id = fm.fid');
  $query->innerJoin('taxonomy_term_data', 'ttd', 'fdfuvt.field_usa_video_terms_target_id = ttd.tid');
  $query->leftJoin('mpx_video', 'mv', 'fm.fid = mv.fid');
  $query->condition('mv.status', 1);
  $query->condition('ttd.name', 'Live');
  $live_video_fid = $query->execute()->fetchField();
  $live_video = file_load($live_video_fid);
  $gygia = field_view_field('file', $live_video, 'field_gigya_share_bar');

  $theme_variables = array(
    'authbar' => !empty($authbar) ? $authbar : NULL,
    'main_url' => url('<front>'),
  );
  return theme('usanetwork_menu_consumptionator_live_video', $theme_variables);
}

/**
 * Renders OnNow, Tonight at the bottom of the A-Spot carousel.
 */
function _usanetwork_menu_aspot_onnow_tonight_block() {

  if (path_is_admin(current_path())) {
    return '';
  }

  $block_form = array();

  $spinner_options = array(
    'path' => drupal_get_path('theme', 'aurora_usa') . '/images/ajax-loader.gif',
    'alt' => t('Please wait...'),
    'title' => t('Please wait'),
    'attributes' => array('class' => 'spinner'),
  );

  $block_form['#attached']['js'][] = libraries_get_path('jstz') . '/jstz-1.0.4.min.js';
  $block_form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.common.js';
  $block_form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_menu') . '/js/usanetwork_menu.onnow_tonight.js';
  $block_form['test'] = array(
    '#type' => 'item',
    '#markup' => theme_image($spinner_options),
  );

  return render($block_form);
}

function _usanetwork_menu_aspot_onnow_tonight_ajax($time_correlation = 0) {

  if (path_is_admin(current_path())) {
    return drupal_json_output(NULL);
  }

  $on_now = usanetwork_schedule_pull_on_now_item($time_correlation);
  $up_next = usanetwork_schedule_pull_up_next_item($time_correlation);
  $tonight = _usanetwork_tv_schedule_get_primetime_items(3);

  $on_now_block = array();
  $up_next_block = array();
  $tonight_block = array();

  if (!empty($on_now)) {
    if (is_array($on_now)) {
      $on_now = reset($on_now);
    }

    $on_now_block = array(
      'show_title' => ($on_now->program_type == 'movie') ? t('USA Movie') :
          (!empty($on_now->show_title) ? $on_now->show_title : ''),
      'episode_title' => $on_now->title,
      'syndicated_url' => ($on_now->program_type != 'movie') ? _usanetwork_menu_get_reminder_url($on_now->nid) : '',
      'episode_full_url' => url('schedule', array('query' => array('guid' => $on_now->guid))),
      'episode_class' => !empty($on_now->nid)
        ? usanetwork_tv_shows_color_show_css_class($on_now->nid) . ' show-color-border'
        : NULL,
      'label_link' => t('On now'),
      'on_now_caption' => t('Watch now'),
      'on_now_live_button' => t('live'),
    );
  }

  if (!empty($up_next)) {
    if (is_array($up_next)) {
      $up_next = reset($up_next);
    }

    $up_next_block = array(
      'show_title' => ($up_next->program_type == 'movie') ? t('USA Movie') :
          (!empty($up_next->show_title) ? $up_next->show_title : ''),
      'episode_title' => $up_next->title,
      'time' => date('g:i', $up_next->start_time),
      'day_part' => date('A', $up_next->start_time),
      'syndicated_url' => ($up_next->program_type != 'movie') ? _usanetwork_menu_get_reminder_url($up_next->nid) : '',
      'episode_full_url' => url('schedule', array('query' => array('guid' => $up_next->guid))),
      'episode_class' => !empty($up_next->nid)
        ? usanetwork_tv_shows_color_show_css_class($up_next->nid) . ' show-color-border'
        : NULL,
      'label_link' => !empty($up_next->nid) ? l(t('Up next'), 'node/' . $up_next->nid, array('attributes' => array('class' => 'up-next-link'))) : t('Up next'),
    );
  }

  if (!empty($tonight)) {
    foreach ($tonight as $tonight_item) {
      $tonight_block[] = array(
        'show_title' => ($tonight_item->program_type == 'movie') ? t('USA Movie') :
            (!empty($tonight_item->show_title) ? $tonight_item->show_title : ''),
        'time' => date('g:i', $tonight_item->start_time),
        'day_part' => date('A', $tonight_item->start_time),
        'syndicated_url' => ($tonight_item->program_type != 'movie') ? _usanetwork_menu_get_reminder_url($tonight_item->nid) : '',
        'episode_full_url' => url('schedule', array('query' => array('guid' => $tonight_item->guid))),
        'episode_class' => !empty($tonight_item->nid)
          ? usanetwork_tv_shows_color_show_css_class($tonight_item->nid) . ' show-color-border'
          : NULL,
      );
    }
  }

  $theme_data = array(
    'on_now_block_item' => array(
      'on_now' => $on_now_block,
      'up_next' => $up_next_block,
    ),
    'tonight_block_items' => $tonight_block,
  );

  return drupal_json_output(array(
    'html' => theme('usanetwork_menu_aspot_onnow_tonight', $theme_data),
  ));
}

/**
 * Returns reminder URL.
 */
function _usanetwork_menu_get_reminder_url($show_nid = NULL) {
  if (empty($show_nid)) {
    return NULL;
  }
  $node = node_load($show_nid);
  $see_it_url = field_get_items('node', $node, 'field_see_it_url');
  if (!empty($see_it_url)) {
    $see_it_url = reset($see_it_url);
    return url(check_plain($see_it_url['value']));
  }
  else {
    $url_alias_field = field_get_items('node', $node, 'field_pathauto_alias');
    if (!empty($url_alias_field)) {
      $alias = $url_alias_field[0]['value'];
      return url('https://see.it/' . $alias);
    }
  }

  return NULL;
}

/*
 * Show with full episodes autocomplete callback
 */
function usanetwork_menu_full_shows_autocomplete($title) {
  $query = db_select('node', 'n');
  $query->fields('n',array('nid','title'));
  $query->condition('n.title', '%' . $title . '%' ,'LIKE');
  $query->condition('n.type', 'tv_show' ,'=');
  $query->join('field_data_field_show', 'fdfs', 'fdfs.field_show_target_id = n.nid');
  $query->join('mpx_video', 'mv', 'mv.fid = fdfs.entity_id');
  $query->condition('mv.status', '1');
  $query->condition('mv.parent_account', '2');
  $query->range(0, 10);
  $result = $query->execute()->fetchAll();

  $output = array();
  if (!empty($result) && is_array($result)) {
    foreach($result as $row) {
      $row->title = check_plain($row->title);
      $key = $row->title . ' [node:' . $row->nid . ']';
      $output[$key] = $row->title;
    }
  }
  drupal_json_output($output);
}

/*
 * Show with full episodes autocomplete callback.
 */
function usanetwork_menu_shows_autocomplete($title) {
  $query = db_select('node', 'n');
  $query->fields('n',array('nid', 'title'));
  $query->condition('n.title', '%' . $title . '%', 'LIKE');
  $query->condition('n.type', 'tv_show', '=');
  $query->condition('n.status', NODE_PUBLISHED, '=');
  $query->range(0, 10);
  $result = $query->execute()->fetchAll();

  $output = array();
  if (!empty($result) && is_array($result)) {
    foreach($result as $row) {
      $row->title = check_plain($row->title);
      $key = $row->title . ' [node:' . $row->nid . ']';
      $output[$key] = $row->title;
    }
  }
  drupal_json_output($output);
}

function usanetwork_menu_movies_autocomplete($title) {
  $query = db_select('node', 'n');
  $query->fields('n',array('nid', 'title'));
  $query->condition('n.title', '%' . $title . '%', 'LIKE');
  $query->condition('n.type', 'movie', '=');
  $query->condition('n.status', NODE_PUBLISHED, '=');
  $query->range(0, 10);
  $result = $query->execute()->fetchAll();

  $output = array();
  if (!empty($result) && is_array($result)) {
    foreach($result as $row) {
      $row->title = check_plain($row->title);
      $key = $row->title . ' [node:' . $row->nid . ']';
      $output[$key] = $row->title;
    }
  }
  return $output;
}

/**
 *  Return shows landing page control form.
 */
function usanetwork_menu_shows_landing_main_form($form, &$form_state) {
  $header_shows = variable_get('shows_landing_shows', array());

  $form['header_shows'] = array(
    '#type' => 'fieldset',
    '#title' => t('Shows Landing Page Features'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  for ($i = 0; $i < USANETWORK_MENU_SHOWS_LANDING_SHOWS_NUMBER; $i++) {
    $form['header_shows']['usa_show_' . $i] = array(
      '#type' => 'textfield',
      '#required' => FALSE,
      '#default_value' => !empty($header_shows[$i])
          ? $header_shows[$i]
          : '',
      '#autocomplete_path' => 'usanetwork_menu/shows/autocomplete',
    );
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save',
  );
  return $form;
}


/**
 *  Return shows landing page control form.
 */
function usanetwork_menu_shows_landing_main_form_submit($form, &$form_state) {
  $header_shows = array();
  for ($i = 0; $i < USANETWORK_MENU_SHOWS_LANDING_SHOWS_NUMBER; $i++) {
    $header_shows[$i] = !empty($form_state['values']['usa_show_' . $i]) ? $form_state['values']['usa_show_' . $i] : '';
  }
  variable_set('shows_landing_shows', $header_shows);
  drupal_set_message(t('All shows page has been successfully updated'));
}

/**
 *  Implements hook_form_FORM_ID_alter().
 */
function usanetwork_menu_form_usanetwork_settings_form_alter(&$form, &$form_state, $form_id) {
  $header_full_episodes_shows = variable_get('header_full_episodes_shows', array());
  $header_movies = variable_get('header_movies', array());

  $form['header_shows'] = array(
    '#type' => 'fieldset',
    '#title' => t('Full Episodes Shows for Header'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  for ($i = 0; $i < USANETWORK_MENU_FULL_EPISODES_NUMBER; $i++) {
    $form['header_shows']['usa_full_episodes_show_' . $i] = array(
      '#type' => 'textfield',
      '#required' => FALSE,
      '#default_value' => !empty($header_full_episodes_shows[$i])
        ? $header_full_episodes_shows[$i]
        : '',
      '#autocomplete_path' => 'usanetwork_menu/full_shows/autocomplete',
    );
  }

  $form['header_movies'] = array(
    '#type' => 'fieldset',
    '#title' => t('Movies for Header'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  for ($i = 0; $i < USANETWORK_MENU_MOVIES_NUMBER; $i++) {
    $form['header_movies']['usa_movie_' . $i] = array(
      '#type' => 'textfield',
      '#required' => FALSE,
      '#default_value' => !empty($header_movies[$i])
        ? $header_movies[$i]
        : '',
      '#autocomplete_path' => 'usanetwork_menu/movies/autocomplete',
    );
  }

  $form['#submit'][] = 'usanetwork_menu_form_usanetwork_settings_form_submit';
}

/**
 * Form submit: functionality for saving shows in header for tab "Full Episodes"
 */
function usanetwork_menu_form_usanetwork_settings_form_submit(&$form, &$form_state) {
  if (!empty($form_state['values'])) {
    $header_full_episodes_shows = array();
    foreach ($form_state['values'] as $value_name => $value) {
      if (strpos($value_name, 'usa_full_episodes_show_') !== FALSE) {
        if (!empty($value)) {
          $header_full_episodes_shows[] = $value;
        }
      }
    }

    $header_movies = array();
    foreach ($form_state['values'] as $value_name => $value) {
      if (strpos($value_name, 'usa_movie_') !== FALSE) {
        if (!empty($value)) {
          $header_movies[] = $value;
        }
      }
    }
  }

  variable_set('header_movies', $header_movies);
  variable_set('header_full_episodes_shows', $header_full_episodes_shows);
}

/*
 * Renders gigya sharebar
 */
function usanetwork_menu_render_sharebar($entity, $entity_type, $label, $title, $description, $image_uri = '') {

  if (isset($entity->field_gigya_share_bar)) {
    $share_settings = array(
      'title' => strip_tags($title),
      'description' => strip_tags($description),
    );
    if (!empty($image)) {
      $share_settings['imageUrl'] = $image_uri;
      $share_settings['imageBhev'] = 'url';
    }
    $sharebar = field_view_field($entity_type, $entity, 'field_gigya_share_bar', array('share_settings' => $share_settings));
    $sharebar['#title'] = $label;
    return !empty($sharebar) ? render($sharebar) : '';
  }
  return '';
}

function _usanetwork_menu_movies_block() {
  $header_movies = variable_get('header_movies', array());
  $items = array();
  $movie_nodes = array();
  if (!empty($header_movies)) {
    foreach ($header_movies as $needed_show) {
      if (preg_match("/^(.+)\[node:(\d+)\]$/", $needed_show, $matches)) {
        $movie_nodes[] = node_load($matches[2]);
      }
    }
  }
  else {
    $movie_nodes = _usanetwork_movie_all_movies_get_movies('NOW&CREATED', USANETWORK_MENU_MOVIES_NUMBER);
  }

  if (!empty($movie_nodes)) {
    foreach ($movie_nodes as $movie_node) {
      if (!empty($movie_node) && $movie_node->type == 'movie') {
        if ($movie_node->status) {
          $movie_file_data = _usanetwork_movie_has_full_episode($movie_node);
          if (!$movie_file_data) {
            continue;
          }
          $movie_file = file_load($movie_file_data->fid);
          $video_image_path = _usanetwork_mpx_video_get_image_path($movie_file);
          $video_image = theme('image_style', array(
            'path' => $video_image_path,
            'style_name' => 'full_episodes_633x356',
          ));
          //$video_image = !empty($cover_media) ? image_style_url('full_episodes_633x356', $cover_media) : NULL;
          $items_variables = array(
            'url' => url('file/' . $movie_file->fid),
            'title' => $movie_node->title,
            'image' => $video_image,
          );
          $items[] = $items_variables;
        }
      }
    }
  }

  $theme_variables = array(
    'items' => $items,
  );

  return theme('usanetwork_menu_movies', $theme_variables);
}

function _usanetwork_menu_news_block() {
  $result = _usanetwork_consumptionator_post_get_posts(NULL, NULL, $limit = 3);

  if (!empty($result)) {
    $posts = entity_load('node', array_keys($result));
    foreach ($posts as $post) {
      $post_image_path = usanetwork_core_api_get_content_image('node', $post, 'main', $limit = 1, TRUE);
      $post_image = theme('image_style', array(
        'path' => $post_image_path,
        'style_name' => 'full_episodes_633x356',
      ));
      $items_variables = array(
        'url' => url('node/' . $post->nid),
        'title' => $post->title,
        'image' => $post_image,
      );
      $items[] = $items_variables;
    }
  }

  $theme_variables = array(
    'items' => $items,
  );

  return theme('usanetwork_menu_news', $theme_variables);
}
