<?php
/**
 * @file
 * Code for the usanetwork_seo_page feature.
 */

include_once 'usanetwork_seo_page.features.inc';

/**
 * Implements hook_theme().
 */
function usanetwork_seo_page_theme() {
  return array(
    'call_to_action_collection' => array(
      'variables' => array(
        'call_to_action' => NULL,
        'language' => NULL
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_node().
 */
function usanetwork_seo_page_preprocess_node(&$vars) {
  if ($vars['type'] == 'catchall_seo_page') {
    $lang = $vars['language'];
    if ($vars['field_h1']) {
      $vars['content']['field_h1'][0]['#markup'] = "<h1>" . $vars['content']['field_h1'][0]['#markup'] . "</h1>";
    }
    if($vars['field_catchall_seo_enable_video'][$lang][0]['value']) {
      if (empty($vars['field_catchall_seo_page_video'])) {
        if ($vars['field_show']) {
          //most recent clip from this show
          $show_id = $vars['field_show'][$lang][0]['target_id'];
          $query = db_select('mpx_video', 'm');
          $query->innerJoin('field_data_field_mpx_full_episode', 'f', 'm.fid = f.entity_id');
          $query->innerJoin('field_data_field_show', 's', 'm.fid = s.entity_id');
          $query->fields('m', array('fid'))
            ->condition('m.status', 1, '=')
            ->condition('f.field_mpx_full_episode_value', 0, '=');
          $query->addExpression("s.field_show_target_id = $show_id", 'order_col');
          $query->orderBy('order_col', 'DESC')
            ->orderBy('m.airdate', 'DESC')
            ->range(0, 1);
          $result = $query->execute();
          $clip = $result->fetchAssoc();
          if ($clip) {
            $video = file_load($clip['fid']);
          }
        } else {
          //most recent clip from all clips
          $query = db_select('mpx_video', 'm');
          $query->innerJoin('field_data_field_mpx_full_episode', 'f', 'm.fid = f.entity_id');
          $query->fields('m', array('fid'))
            ->condition('m.status', 1, '=')
            ->condition('f.field_mpx_full_episode_value', 0, '=')
            ->orderBy('m.airdate', 'DESC')
            ->range(0, 1);
          $result = $query->execute();
          $clip = $result->fetchAssoc();
          if ($clip) {
            $video = file_load($clip['fid']);
          }
        }
        if($video){
          $vars['video'] = theme('pub_mpx_video', array(
            'file' => $video,
            'pub_mpx_player_parameters' => array('autoPlay' => 'true', 'form' => 'html'),
            'player_id' => '4Dl3P2Df_j5l'
          ));
        }
      }
    }
  }
}

/**
 * Theme callback call_to_action_collection
 */
function theme_call_to_action_collection($variables) {
  $cta_block = "";
  $lang = $variables['language'];
  foreach($variables['call_to_action'] as $value){
    switch ($value->field_cta_type[$lang][0]['value']) {
      case 'text':
        if (!empty($value->field_cta_text[$lang][0]['value'])) {
          $cta_block .= '<div class="cta-item cta-text"><a href="' . $value->field_cta_url[$lang][0]['value'] . '">' . $value->field_cta_text[$lang][0]['value'] . '</a></div>';
        }
        break;
      case 'image':
        if (!empty($value->field_cta_image)) {
          $image = theme_image(array('path' => $value->field_cta_image[$lang][0]['uri'], 'attributes' => array('class' => array('cta-image'), 'alt'=>'')));
          $cta_block .= '<div class="cta-item cta-image"><a href="' . $value->field_cta_url[$lang][0]['value'] . '">'. $image .'</a></div>';
        }
        break;
    }
  }
  return $cta_block;
}


/**
 * Implements hook_preprocess_field()
 */
function usanetwork_seo_page_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_call_to_action') {
    $lang = $variables['element']['#language'];
    foreach ($variables['items'] as $item) {
      $call_to_action[] = field_collection_item_load(key($item['entity']['field_collection_item']));
    }
    if($call_to_action){
      $cta_block = theme('call_to_action_collection', array(
        'call_to_action' => $call_to_action,
        'language' => $lang
      ));
      $variables['cta_block'] = $cta_block;
    }
  }
  if ($variables['element']['#field_name'] == 'field_catchall_seo_page_video') {
    $lang = $variables['element']['#language'];
    if ($variables['element']['#object']->field_catchall_seo_enable_video[$lang][0]['value']) {
      $video = ($variables['element']['#items'][0]);
      if (!empty($video)) {
        $variables['video'] = theme('pub_mpx_video', array(
          'file' => $video,
          'pub_mpx_player_parameters' => array('autoPlay' => 'true', 'form' => 'html'),
          'player_id' => '4Dl3P2Df_j5l'
        ));
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function usanetwork_seo_page_form_catchall_seo_page_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][]= 'usanetwork_seo_page_validate';
  $form['#attached']['js'][] = drupal_get_path('module', 'usanetwork_seo_page').'/js/seo_page_form.js';
}

/**
 * Implements hook_validate().
 */
function usanetwork_seo_page_validate(&$form, &$form_state) {
  $lang = $form['language']['#value'];
  if(isset($form_state['values']['field_call_to_action'][$lang])) {
    $cta_array = $form_state['values']['field_call_to_action'][$lang];
    array_pop($cta_array);
    foreach ($cta_array as $key => $value) {
      $cta_type = $value['field_cta_type'][$lang][0]['value'];
      $cta_url = $value['field_cta_url'][$lang][0]['value'];
      $cta_text = $value['field_cta_text'][$lang][0]['value'];
      $cta_image = $value['field_cta_image'][$lang][0]['value'];
      if($value['field_cta_type'][$lang][0]['value'] == NULL && ($value['field_cta_url'][$lang][0]['value'] || $value['field_cta_text'][$lang][0]['value'] || $value['field_cta_image'][$lang][0]['value'])) {

      }
      switch ($cta_type) {
        case '':
          if (!empty($cta_url) || !empty($cta_text) || !empty($cta_image)) {
            form_error($form['field_call_to_action'][$lang][$key]['field_cta_type'], t('Choose the type for Call to all.'));
          }
          break;
        case 'text':
          if (empty($cta_text)) {
            form_error($form['field_call_to_action'][$lang][$key]['field_cta_text'], t('CTA Text is required for selected CTA type.'));
          }
          if (empty($cta_url)) {
            form_error($form['field_call_to_action'][$lang][$key]['field_cta_url'], t('CTA URL is required for selected CTA type.'));
          } else {
            if(!filter_var($cta_url, FILTER_VALIDATE_URL)){
              form_error($form['field_call_to_action'][$lang][$key]['field_cta_url'], t('This is not a correct URL.'));
            }
          }
          break;
        case 'image':
          if (empty($cta_image)) {
            form_error($form['field_call_to_action'][$lang][$key]['field_cta_image'], t('CTA Image is required for selected CTA type.'));
          }
          if (empty($cta_url)) {
            form_error($form['field_call_to_action'][$lang][$key]['field_cta_url'], t('CTA URL is required for selected CTA type.'));
          } else {
            if(!filter_var($cta_url, FILTER_VALIDATE_URL)){
              form_error($form['field_call_to_action'][$lang][$key]['field_cta_url'], t('This is not a correct URL.'));
            }
          }
          break;
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function usanetwork_seo_page_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] = 'views-exposed-form-browser-plugin-for-clips-default') {
    $form['status']['#default_value'] = 'Published';
  }
}

