<?php

/**
 * @file
 *
 * USA Network SURF Integration module file.
 *
 */

/**
 * Implements hook_library().
 */
function usanetwork_surf_library() {

  $libraries['usanetwork_surf'] = array(
    'title' => 'USA Network Surf',
    'website' => 'http://www.usanetwork.com/',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'usanetwork_surf') . '/usanetwork_surf.js' => array(
        'type' => 'file',
        'group' => JS_LIBRARY,
        'scope' => 'footer',
      ),
    ),
    'dependencies' => array(
      array('surf', 'jquery.tmpl'),
      array('surf', 'surf.session'),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_surf_settings_alter().
 */
function usanetwork_surf_surf_settings_alter(&$data) {
  $data['responsive'] = FALSE;
  $data['smallDisplay'] = 400;
  $data['element'] = 'surf-content';
}


/**
 * Implements hook_block_info().
 */
function usanetwork_surf_block_info() {

  $blocks['surf-login'] = array(
    'info' => t('Surf'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['surf-content'] = array(
    'info' => t('Surf Content'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @param string $delta
 *
 * @return array
 */
function usanetwork_surf_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'surf-login':
      $block['subject'] = '';
      $block['content'] = array(
        '#theme' => 'surf_actions_block',
      );
      break;
    case 'surf-content':
      $block['subject'] = '';
      $block['content'] = array(
        '#theme' => 'surf_content_block',
      );
      break;
  }

  return $block;
}

/**
 * Implement hook_theme().
 *
 * @return array
 */
function usanetwork_surf_theme() {
  return array(
    'surf_actions_block' => array(
      'variables' => array(),
      'template' => 'templates/surf-actions'
    ),
    'surf_content_block' => array(
      'variables' => array(),
      'template' => 'templates/surf-content'
    ),
  );
}
