<?php
/**
 * @file
 * Code for the usanetwork_catchall feature.
 */

include_once 'usanetwork_catchall.features.inc';

/**
 * Implements hook_preprocess_HOOK().
 */
function usanetwork_catchall_preprocess_html(&$vars) {
  // Load node
  $node = menu_get_object();
  if ($node && $node->type == 'catchall_page') {
    $fixedwidth_field = field_get_items('node', $node, 'field_usa_catchall_fixedwidth');
    // add a body class if this checkbox has been selected
    if ($fixedwidth_field[0]['value'] == '1') {
      $vars['classes_array'][] = 'usa-fixed-width';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function usanetwork_catchall_preprocess_page(&$vars) {
  // Load node, hide title on the frontend
  $node = menu_get_object();
  if ($node && $node->type == 'catchall_page') {
    $vars['title'] = '';
  }
}

