<?php
/**
 * @file
 * Code for the usanetwork_catchall feature.
 */

include_once 'usanetwork_catchall.features.inc';
define('USA_CATCHALL_RELATED_CONTENT_ITEMS', 6);

/**
 *  Implements hook_menu().
 */
function usanetwork_catchall_menu() {
  $items = array();
  $items['ajax/usanetwork-catchall/get-related/%node/%/%'] = array(
    'title' => 'Related content',
    'page callback' => 'usanetwork_catchall_get_related_content_ajax',
    'page arguments' => array(3, 4, 5),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implements hook_preprocess_HOOK().
 */
function usanetwork_catchall_preprocess_html(&$vars) {
  // Load node
  $node = menu_get_object();
  if ($node && $node->type == 'catchall_page') {
    $fixedwidth_field = field_get_items('node', $node, 'field_usa_catchall_fixedwidth');
    // add a body class if this checkbox has been selected
    if ($fixedwidth_field[0]['value'] == '1') {
      $vars['classes_array'][] = 'usa-fixed-width';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function usanetwork_catchall_preprocess_page(&$vars) {
  // Load node, hide title on the frontend
  $node = menu_get_object();
  if ($node && $node->type == 'catchall_page') {
    $vars['title'] = '';

    //Settings for MPS reloadable Ad
    $field_automatic_refresh = _usanetwork_get_field_item('node', $node, 'field_automatic_refresh' ,'value');
    if ($field_automatic_refresh && $field_automatic_refresh == '1') {
      $field_refresh_time = _usanetwork_get_field_item('node', $node, 'field_refresh_time' ,'value');
      drupal_add_js(array('CatchallRefreshSettings' => array('time' => ($field_refresh_time) ? $field_refresh_time : '')), 'setting');
    }
  }
}

/*
 * Returns content for usanetwork_catchall_related_content_content block.
 */
function _usanetwork_catchall_related_content() {
  if (path_is_admin(current_path())) {
    return '';
  }

  $content = menu_get_object('node');
  if (!empty($content) && $content->type == 'catchall_page') {
    if (empty($content->field_tvs_show_latest_feed)) {
      return '';
    }
    else {
      $latest_content_flag_field = field_get_items('node', $content, 'field_tvs_show_latest_feed');

      if ($latest_content_flag_field[0]['value'] == 0) {
        return '';
      }
    }
    $node = usanetwork_core_api_get_tv_content_node($content);
    if (!empty($node)) {
      $related_content = usanetwork_related_content_get_related_content_for_consumpt_page($content, $node);
      if (!empty($related_content)) {
        $function = 'usanetwork_' . $node->type . '_consumptionator_render_related_content_items_block';
        $block_of_items = $function($related_content);
        $load_more_link = &drupal_static('load_more_link');
        $load_more_link = TRUE;
        return theme('usanetwork_' . $node->type . '_consumptionator_related_items_container', array(
          'related_items_block' => $block_of_items,
          'load_more_link' => $load_more_link,
          'show_nid' => $node->nid,
          'items_pre_page_limit' => USA_CATCHALL_RELATED_CONTENT_ITEMS,
        ));
      }
    }
  }
  return '';
}


function usanetwork_catchall_get_related_content_ajax($node, $start_from = 0, $limit = 1) {
  return usanetwork_related_content_get_related_content_ajax('catchall_page', $node, $start_from, $limit);
}
